import type { Product } from '../types';

export const campingProducts: Product[] = [

  /* ── 1. כיסא שטח Heavy Duty ────────────────────────────────────── */
  {
    id: 'prod-101',
    name: 'כיסא שטח Heavy Duty 150 ק"ג',
    slug: 'camp-chair-hd',
    category: 'קמפינג וציוד שטח',
    categorySlug: 'camping',
    price: 149,
    originalPrice: 199,
    rating: 4.8,
    reviewCount: 134,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-CHR-001',
    brand: 'KingCamp',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://www.kingcampoutdoors.com/products/adjustable-heavy-duty-camping-chair',
    image: 'https://www.kingcampoutdoors.com/cdn/shop/products/KingCampAdjustbleHeavyDutyCampingChairs_1.jpg?v=1655372260&width=1600',
    images: [
      'https://www.kingcampoutdoors.com/cdn/shop/products/KingCampAdjustbleHeavyDutyCampingChairs_1.jpg?v=1655372260&width=1600',
      'https://www.kingcampoutdoors.com/cdn/shop/products/KingCampAdjustbleHeavyDutyCampingChairs_2.jpg?v=1655372261&width=1400',
      'https://www.kingcampoutdoors.com/cdn/shop/products/KingCampAdjustbleHeavyDutyCampingChairs_3.jpg?v=1655372260&width=1400',
    ],
    videoUrl: null,
    shortDescription: 'כיסא שטח איתן לעומס עד 150 ק"ג. ידיות מרופדות, גב גבוה, מתקפל בשנייה לשקית נשיאה.',
    description: 'כיסא שטח מאלומיניום 7075 עם בד 600D אוקספורד. מחזיק עד 150 ק"ג, גב גבוה ותומך, ידיות מרופדות. מתקפל בשנייה לשקית נשיאה קומפקטית עם רצועת כתף.',
    benefits: [
      'עומס מקסימלי 150 ק"ג — יציב לכל הגדלים',
      'בד 600D אוקספורד — עמיד לשמש, אבק ושפשוף',
      'רגליים עם תושבות גומי — לא שוקעות בחול',
      'מתקפל ב-10 שניות לשקית נשיאה עם רצועת כתף',
    ],
    specs: [
      { label: 'עומס מקסימלי', value: '150 ק"ג' },
      { label: 'חומר מסגרת', value: 'אלומיניום 7075' },
      { label: 'בד', value: '600D אוקספורד' },
      { label: 'משקל', value: '1.8 ק"ג' },
      { label: 'ממדים פתוח', value: '57 × 62 × 95 ס"מ' },
    ],
    faqs: [
      {
        question: 'כמה זמן לוקח להרכיב?',
        answer: 'פחות מ-10 שניות — פתיחה בפעולה אחת, ללא כלים.',
      },
    ],
    seoTitle: 'כיסא שטח Heavy Duty 150 ק"ג | קמפינג ישראל | CampIL',
    seoDescription: 'כיסא שטח איתן מאלומיניום 7075 לעומס 150 ק"ג. בד 600D, מתקפל בשנייה. ₪149.',
    tags: ['כיסא קמפינג', 'כיסא שטח', 'ציוד קמפינג'],
    relatedSlugs: ['camp-table-fold', 'tarp-uv-3x3'],
  },

  /* ── 2. שולחן שטח מתקפל ────────────────────────────────────────── */
  {
    id: 'prod-102',
    name: 'שולחן שטח אלומיניום מתקפל 120 ס"מ',
    slug: 'camp-table-fold',
    category: 'קמפינג וציוד שטח',
    categorySlug: 'camping',
    price: 189,
    originalPrice: 249,
    rating: 4.7,
    reviewCount: 89,
    badge: 'sale',
    inStock: true,
    sku: 'CAMP-TBL-001',
    brand: 'KingCamp',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://www.kingcampoutdoors.com/products/bamaura-folding-table',
    image: 'https://www.kingcampoutdoors.com/cdn/shop/files/KingCamp_BamAura_Folding_Roll-Top_Aluminum_Table_with_Bamboo_Extensions.jpg?v=1748500718&width=1600',
    images: [
      'https://www.kingcampoutdoors.com/cdn/shop/files/KingCamp_BamAura_Folding_Roll-Top_Aluminum_Table_with_Bamboo_Extensions.jpg?v=1748500718&width=1600',
      'https://www.kingcampoutdoors.com/cdn/shop/files/20250228-103300.jpg?v=1740712999&width=1600',
    ],
    videoUrl: null,
    shortDescription: 'שולחן שטח אלומיניום 120×60 ס"מ. גובה מתכוונן ב-3 מצבים, עומס 60 ק"ג, מתקפל שטוח.',
    description: 'שולחן שטח קל מאלומיניום 6061 עם משטח 120×60 ס"מ ורגליים מתכווננות בגובה. מחזיק עד 60 ק"ג, מתקפל שטוח לשקית גב.',
    benefits: [
      'משטח 120×60 ס"מ — מקום נוח לארוחה ולכל הציוד',
      'גובה מתכוונן ב-3 מצבים: 45, 60, 70 ס"מ',
      '3.2 ק"ג בלבד — קל לנשיאה',
      'מתקפל שטוח — נישא כגב תיק',
    ],
    specs: [
      { label: 'ממדים פתוח', value: '120 × 60 × 70 ס"מ' },
      { label: 'עומס מקסימלי', value: '60 ק"ג' },
      { label: 'משקל', value: '3.2 ק"ג' },
      { label: 'חומר', value: 'אלומיניום 6061' },
      { label: 'גובה', value: '45 / 60 / 70 ס"מ' },
    ],
    faqs: [
      {
        question: 'האם יציב בקרקע לא ישרה?',
        answer: 'הרגליים מתכווננות בנפרד לכל פינה — מתאימות גם לשטח לא מישורי.',
      },
    ],
    seoTitle: 'שולחן שטח אלומיניום מתקפל 120 ס"מ | CampIL',
    seoDescription: 'שולחן שטח אלומיניום 3.2 ק"ג, 120×60 ס"מ, גובה מתכוונן, עומס 60 ק"ג. ₪189.',
    tags: ['שולחן קמפינג', 'שולחן שטח', 'ריהוט שטח'],
    relatedSlugs: ['camp-chair-hd', 'tarp-uv-3x3'],
  },

  /* ── 3. טרפ UV 3×3 ────────────────────────────────────────────── */
  {
    id: 'prod-103',
    name: 'טרפ UV מחוזק 3×3 מטר',
    slug: 'tarp-uv-3x3',
    category: 'קמפינג וציוד שטח',
    categorySlug: 'camping',
    price: 149,
    originalPrice: 199,
    rating: 4.6,
    reviewCount: 112,
    badge: 'sale',
    inStock: true,
    sku: 'CAMP-TRP-001',
    brand: 'RedCamp',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://redcamp.com/products/tarp',
    image: 'https://redcamp.com/cdn/shop/files/image_1_4dabc27b-900a-4dcd-b938-96e549864474.jpg?v=1743653403',
    images: [
      'https://redcamp.com/cdn/shop/files/image_1_4dabc27b-900a-4dcd-b938-96e549864474.jpg?v=1743653403',
    ],
    videoUrl: null,
    shortDescription: 'טרפ ניילון 3×3 מ׳ עם ציפוי UV ו-18 לולאות מחוזקות. לצל, הגנה מגשם ואוורור בשטח.',
    description: 'טרפ 210D ניילון אוקספורד עם ציפוי PE כפול. 18 לולאות מחוזקות פי-4, עמיד לשמש ולגשם. מתקפל לשקית כף יד.',
    benefits: [
      'ציפוי UV 50+ — צל אמיתי גם בחמסין',
      '18 לולאות מחוזקות — עמידות למתיחה ורוח',
      'עמידות מים 2000 mm',
      'מתקפל לשקית 30×15 ס"מ',
    ],
    specs: [
      { label: 'גודל', value: '3×3 מטר' },
      { label: 'חומר', value: '210D ניילון אוקספורד + PE' },
      { label: 'עמידות מים', value: '2000 mm' },
      { label: 'משקל', value: '680 גרם' },
      { label: 'לולאות', value: '18 — מחוזקות פי-4' },
    ],
    faqs: [
      {
        question: 'איך קושרים אותו בשטח?',
        answer: 'עם פרקורד (נמכר בנפרד) ויתדות. הוראות קשירה בסיסית מצורפות.',
      },
    ],
    seoTitle: 'טרפ UV מחוזק 3×3 מ׳ | 2000 mm | CampIL',
    seoDescription: 'טרפ 210D 3×3 מ׳, 18 לולאות, ציפוי UV, עמיד 2000 mm. ₪149.',
    tags: ['טרפ שטח', 'צל קמפינג', 'כיסוי גשם'],
    relatedSlugs: ['camp-chair-hd', 'paracord-30m'],
  },

  /* ── 4. אתה מתקפלת ─────────────────────────────────────────────── */
  {
    id: 'prod-104',
    name: 'אתה מתקפלת שטח 3 מצבים',
    slug: 'folding-shovel',
    category: 'קמפינג וציוד שטח',
    categorySlug: 'camping',
    price: 79,
    originalPrice: 109,
    rating: 4.6,
    reviewCount: 91,
    inStock: true,
    sku: 'CAMP-SHV-001',
    brand: 'RedCamp',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://redcamp.com/products/folding-shovel',
    image: 'https://redcamp.com/cdn/shop/products/folding-shovel-main-5.webp?v=1743651526',
    images: [
      'https://redcamp.com/cdn/shop/products/folding-shovel-main-5.webp?v=1743651526',
      'https://redcamp.com/cdn/shop/files/folding-shovel-scene-webp_2.jpg?v=1743651528',
    ],
    videoUrl: null,
    shortDescription: 'אתה מתקפלת פלדת פחמן 3 מצבים. לחפירת אוגן, פינוי חול וחילוץ רכב. נישאת בכיס.',
    description: 'אתה מתקפלת פלדת פחמן עם ציפוי אנטי-חלודה ב-3 מצבים: ישרה, 90° ו-45°. אורך פתוח 60 ס"מ. מגיע עם נרתיק MOLLE לחגורה.',
    benefits: [
      '3 מצבי פתיחה — אתה, מגרדת וחפירה בכיוון',
      'פלדת פחמן — חזקה לחפירה קשה',
      'ידית ארגונומית — לא מחליקה עם כפפות',
      'נרתיק MOLLE כלול',
    ],
    specs: [
      { label: 'חומר', value: 'פלדת פחמן + ציפוי שחור' },
      { label: 'אורך פתוח', value: '60 ס"מ' },
      { label: 'אורך סגור', value: '22 ס"מ' },
      { label: 'משקל', value: '490 גרם' },
      { label: 'מצבים', value: '0° / 45° / 90°' },
    ],
    faqs: [
      {
        question: 'עמידה לחפירה בקרקע קשה?',
        answer: 'כן — פלדת פחמן עמידה לחמרה, חצץ ועפר דחוס.',
      },
    ],
    seoTitle: 'אתה מתקפלת שטח 3 מצבים | פלדת פחמן | CampIL',
    seoDescription: 'אתה מתקפלת פלדת פחמן 3 מצבים, 60 ס"מ, 490 גרם. נרתיק MOLLE כלול. ₪79.',
    tags: ['אתה שטח', 'ציוד חירום', 'קמפינג'],
    relatedSlugs: ['multi-tool-pro', 'paracord-30m'],
  },

  /* ── 5. מולטי-טול 21 כלים ──────────────────────────────────────── */
  {
    id: 'prod-105',
    name: 'מולטי-טול 21 כלים נירוסטה',
    slug: 'multi-tool-pro',
    category: 'קמפינג וציוד שטח',
    categorySlug: 'camping',
    price: 149,
    originalPrice: 199,
    rating: 4.7,
    reviewCount: 156,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-MTP-001',
    brand: 'Leatherman',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://www.leatherman.com/wave-plus-multi-tool-832524.html',
    image: 'https://www.leatherman.com/cdn/shop/files/wave_20260402201902_5dib.jpg?v=1777562829',
    images: [
      'https://www.leatherman.com/cdn/shop/files/wave_20260402201902_5dib.jpg?v=1777562829',
      'https://www.leatherman.com/cdn/shop/files/wave_20260402201904_tasy.jpg?v=1777562847',
      'https://www.leatherman.com/cdn/shop/files/wave_20260402201902_thhv.jpg?v=1777562882',
      'https://www.leatherman.com/cdn/shop/files/wave_20260402201904_oekn.jpg?v=1777562856',
    ],
    videoUrl: null,
    shortDescription: '21 כלים בפלייר אחד מנירוסטה 420HC. פלייר, מספריים, מברגים, פותחן, מסור. נרתיק עור כלול.',
    description: 'מולטי-טול מנירוסטה 420HC עם 21 כלים: פלייר, סכין, מספריים, מברגים, פותחן, מפתח, מסור ועוד. כולל נרתיק עור לחגורה.',
    benefits: [
      '21 כלים — מחליף תיבת כלים שלמה',
      'נירוסטה 420HC — לא מחלידה, שומרת חדות',
      'כל הכלים נפתחים חד-ידית',
      'נרתיק עור קשיח כלול',
    ],
    specs: [
      { label: 'חומר', value: 'נירוסטה 420HC' },
      { label: 'כמות כלים', value: '21' },
      { label: 'אורך סגור', value: '10.5 ס"מ' },
      { label: 'משקל', value: '265 גרם' },
    ],
    faqs: [
      {
        question: 'עובר ביטחון בשדה התעופה?',
        answer: 'לא — מולטי-טול עם להב מעל 6 ס"מ אסור בנשיאת יד. יש לשים בכבודה.',
      },
    ],
    seoTitle: 'מולטי-טול 21 כלים 420HC | שטח | CampIL',
    seoDescription: 'מולטי-טול 21 כלים נירוסטה 420HC. פלייר, מספריים, מברגים. נרתיק עור כלול. ₪149.',
    tags: ['מולטי-טול', 'כלי שטח', 'קמפינג'],
    relatedSlugs: ['folding-shovel', 'camp-chair-hd'],
  },

  /* ── 6. מטרייה חוף UV50+ 2 מטר ────────────────────────────────── */
  {
    id: 'prod-106',
    name: 'מטריית חוף ושטח UV50+ קוטר 2 מ׳',
    slug: 'beach-umbrella-2m',
    category: 'קמפינג וציוד שטח',
    categorySlug: 'camping',
    price: 149,
    originalPrice: 199,
    rating: 4.7,
    reviewCount: 143,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-UMB-001',
    brand: 'KingCamp',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://www.kingcampoutdoors.com/products/sun-shade',
    image: 'https://www.kingcampoutdoors.com/cdn/shop/products/KingCamp_sunshade_1.jpg?v=1699086001&width=1500',
    images: [
      'https://www.kingcampoutdoors.com/cdn/shop/products/KingCamp_sunshade_1.jpg?v=1699086001&width=1500',
      'https://www.kingcampoutdoors.com/cdn/shop/files/51EvCknEtJL._AC_SL1500.jpg?v=1778482572&width=1500',
      'https://www.kingcampoutdoors.com/cdn/shop/products/KingCamp_sunshade_7.jpg?v=1699086001&width=1500',
    ],
    videoUrl: null,
    shortDescription: 'מטרייה קוטר 2 מ׳ עם UPF 50+. עמוד אלומיניום 3 שלבים, עוגן חול, מחזיקה ברוח עד 40 קמ"ש.',
    description: 'מטרייה גדולה לחוף ושטח, קוטר 2 מ׳, בד ניילון 170T עם ציפוי UPF 50+. עמוד אלומיניום 3 שלבים, עוגן ברגה לחול. כולל שקית נשיאה.',
    benefits: [
      'קוטר 2 מ׳ — מספיק לכיסא ושולחן',
      'UPF 50+ — מפחית קרינה ב-98%',
      'עמוד 3 שלבים — ניתן לכוון לגובה ולזווית',
      'עוגן חול ברגה — לא מתהפכת ברוח',
    ],
    specs: [
      { label: 'קוטר', value: '2 מטר' },
      { label: 'בד', value: 'ניילון 170T + UPF 50+' },
      { label: 'עמוד', value: 'אלומיניום 3 שלבים' },
      { label: 'גובה', value: 'עד 2.1 מטר' },
      { label: 'משקל', value: '1.1 ק"ג' },
    ],
    faqs: [
      {
        question: 'עובדת על קרקע קשה?',
        answer: 'כן — בקרקע קשה ניתן לנעוץ יתד ייעודית (כלולה).',
      },
    ],
    seoTitle: 'מטריית חוף ושטח UV50+ קוטר 2 מ׳ | CampIL',
    seoDescription: 'מטרייה חוף 2 מ׳ UPF 50+. עמוד אלומיניום, עוגן חול. ₪149.',
    tags: ['מטרייה חוף', 'צל שטח', 'קמפינג'],
    relatedSlugs: ['camp-chair-hd', 'tarp-uv-3x3'],
  },

  /* ── 7. פרקורד 550 30 מטר ──────────────────────────────────────── */
  {
    id: 'prod-107',
    name: 'פרקורד 550 MIL-SPEC 30 מטר',
    slug: 'paracord-30m',
    category: 'קמפינג וציוד שטח',
    categorySlug: 'camping',
    price: 39,
    originalPrice: 59,
    rating: 4.7,
    reviewCount: 203,
    badge: 'sale',
    inStock: true,
    sku: 'CAMP-PCR-001',
    brand: 'Gear Aid',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://www.gearaid.com/products/paracord-550-reflective',
    image: 'https://www.gearaid.com/cdn/shop/products/80672-GA-Paracord-550-Reflective-Orange-Comp-01_e105ee40-6080-445d-9bc7-dd5ed5ac3a5c.jpg?v=1546456863&width=3000',
    images: [
      'https://www.gearaid.com/cdn/shop/products/80672-GA-Paracord-550-Reflective-Orange-Comp-01_e105ee40-6080-445d-9bc7-dd5ed5ac3a5c.jpg?v=1546456863&width=3000',
    ],
    videoUrl: null,
    shortDescription: 'פרקורד Type III MIL-SPEC 550 — עמיד ל-250 ק"ג. 30 מטר. לקשירת ציוד, טרפ, ואוגן.',
    description: 'פרקורד Type III MIL-SPEC 550 עם 7 חוטי ניילון פנימיים. עמידות 250 ק"ג, לא נרקב, לא מחליד. 30 מטר ב-5 צבעים.',
    benefits: [
      'MIL-SPEC 550 — סטנדרט צבאי אמריקאי',
      'עמיד 250 ק"ג — לכל צורך בשטח',
      '7 חוטים פנימיים — ניתן להפריד לשימושים דקים',
      'עמיד UV ולחות',
    ],
    specs: [
      { label: 'סטנדרט', value: 'Type III MIL-C-5040H' },
      { label: 'אורך', value: '30 מטר' },
      { label: 'עומס שבירה', value: '250 ק"ג' },
      { label: 'קוטר', value: '4 מ"מ' },
    ],
    faqs: [
      {
        question: 'אפשר להשתמש כחבל לטרפ?',
        answer: 'כן — עמיד 250 ק"ג, מספיק לטרפ 3×3 גם בסערה.',
      },
    ],
    seoTitle: 'פרקורד 550 MIL-SPEC 30 מטר | CampIL',
    seoDescription: 'פרקורד 550 MIL-SPEC 30 מטר, 7 חוטים, עמיד 250 ק"ג. ₪39.',
    tags: ['פרקורד', 'חבל שטח', 'קמפינג'],
    relatedSlugs: ['tarp-uv-3x3', 'tent-stakes-10'],
  },

  /* ── 8. אוהל משפחתי 6 אנשים ───────────────────────────────────── */
  {
    id: 'prod-108',
    name: 'אוהל משפחתי Dome 6 אנשים 2 חדרים',
    slug: 'family-tent-6p',
    category: 'קמפינג וציוד שטח',
    categorySlug: 'camping',
    price: 449,
    originalPrice: 599,
    rating: 4.7,
    reviewCount: 47,
    badge: 'sale',
    inStock: true,
    sku: 'CAMP-TNT-001',
    brand: 'CORE Equipment',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://www.coreequipment.com/products/core-6-person-dome-tent',
    image: 'https://www.coreequipment.com/cdn/shop/files/core-6-person-dome-tent-main.png?v=1759245175&width=1946',
    images: [
      'https://www.coreequipment.com/cdn/shop/files/core-6-person-dome-tent-main.png?v=1759245175&width=1946',
    ],
    videoUrl: null,
    shortDescription: 'אוהל Dome ל-6 אנשים עם 2 חדרים נפרדים. עמיד 3000 mm, גובה 1.9 מ׳, הגדרה ב-15 דקות.',
    description: 'אוהל Dome דו-חדרי ל-6 אנשים, עמיד 3000 mm. גובה פנימי 1.9 מ׳, 2 כניסות עם רשת חרקים, פתחי אוורור. כולל כל היתדות, מוטות פיברגלס ושקית נשיאה.',
    benefits: [
      'שני חדרים — פרטיות לקבוצה',
      '3000 mm — שורד גשם ישראלי',
      'גובה 1.9 מ׳ — עומדים ישרה בפנים',
      'רשת חרקים בשתי הכניסות',
    ],
    specs: [
      { label: 'קיבולת', value: '6 אנשים / 2 חדרים' },
      { label: 'עמידות מים', value: '3000 mm' },
      { label: 'גובה פנימי', value: '1.9 מטר' },
      { label: 'שטח פנימי', value: '7.2 מ"ר' },
      { label: 'משקל', value: '7.8 ק"ג' },
    ],
    faqs: [
      {
        question: 'כמה שמיכות כפולות נכנסות?',
        answer: 'שלוש שמיכות כפולות — אחת לכל חדר בנוחות.',
      },
    ],
    seoTitle: 'אוהל משפחתי 6 אנשים Dome | 2 חדרים | 3000 mm | CampIL',
    seoDescription: 'אוהל Dome ל-6 אנשים, 2 חדרים, עמיד 3000 mm, גובה 1.9 מ׳. ₪449.',
    tags: ['אוהל משפחתי', 'אוהל 6 אנשים', 'קמפינג'],
    relatedSlugs: ['tent-stakes-10', 'tarp-uv-3x3'],
  },

  /* ── 9. יתדות אוהל אלומיניום ───────────────────────────────────── */
  {
    id: 'prod-109',
    name: 'יתדות אוהל אלומיניום V — ערכת 10',
    slug: 'tent-stakes-10',
    category: 'קמפינג וציוד שטח',
    categorySlug: 'camping',
    price: 49,
    originalPrice: 69,
    rating: 4.8,
    reviewCount: 311,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-STK-001',
    brand: 'MSR',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://www.msrgear.com/tent-accessories/tent-stakes/groundhog-tent-stake-kit/05807.html',
    image: 'https://cascadedesigns.com/cdn/shop/files/05807_msr_groundhog_tent_stakes_kit.jpg?v=1779819211&width=1946',
    images: [
      'https://cascadedesigns.com/cdn/shop/files/05807_msr_groundhog_tent_stakes_kit.jpg?v=1779819211&width=1946',
    ],
    videoUrl: null,
    shortDescription: 'יתדות אלומיניום 7075 חתך-V 18 ס"מ. חזקות פי-3 מפלסטיק. ערכת 10 עם שקית ופטיש מיני.',
    description: 'יתדות אלומיניום 7075 בחתך V לתפיסה מרבית. 18 ס"מ, 17 גרם ליחידה. לא מתכופפות, לא נשברות, לא מחלידות. ערכת 10 עם שקית בד ופטיש מיני.',
    benefits: [
      'אלומיניום 7075 — חזקות פי-3 מפלסטיק',
      'חתך V — תפיסה חזקה גם בחול',
      '17 גרם ליחידה — הקלות בקטגוריה',
      'כולל שקית בד ופטיש מיני',
    ],
    specs: [
      { label: 'חומר', value: 'אלומיניום 7075' },
      { label: 'אורך', value: '18 ס"מ' },
      { label: 'משקל ליחידה', value: '17 גרם' },
      { label: 'כמות', value: '10 + שקית + פטיש' },
    ],
    faqs: [
      {
        question: 'עובדות בקרקע סלעית?',
        answer: 'כן — עמידות לסלע רך. בגרניט קשה — השתמשו בפטיש המצורף.',
      },
    ],
    seoTitle: 'יתדות אוהל אלומיניום 7075 ערכת 10 | CampIL',
    seoDescription: 'יתדות אוהל אלומיניום 7075 חתך-V 18 ס"מ. ערכת 10 עם שקית ופטיש. ₪49.',
    tags: ['יתדות אוהל', 'יתדות אלומיניום', 'ציוד אוהל'],
    relatedSlugs: ['family-tent-6p', 'paracord-30m'],
  },

  /* ── 10. מחסל יתושים UV ────────────────────────────────────────── */
  {
    id: 'prod-110',
    name: 'מחסל יתושים UV חשמלי 40 מ"ר USB-C',
    slug: 'mosquito-killer',
    category: 'קמפינג וציוד שטח',
    categorySlug: 'camping',
    price: 89,
    originalPrice: 129,
    rating: 4.5,
    reviewCount: 88,
    badge: 'new',
    inStock: true,
    sku: 'CAMP-MSQ-001',
    brand: 'Thermacell',
    deliveryTime: '5–10 ימי עסקים',
    image: 'https://adriftallseason.com/cdn/shop/files/1_b8ca668f-a999-44a6-85e2-657370817746.jpg?v=1746216646',
    images: [
      'https://adriftallseason.com/cdn/shop/files/1_b8ca668f-a999-44a6-85e2-657370817746.jpg?v=1746216646',
    ],
    videoUrl: null,
    shortDescription: 'מחסל יתושים UV 360° עם רשת 2200V. USB-C, כיסוי 40 מ"ר, 12 שעות פעולה. ללא כימיקלים.',
    description: 'מנורת UV 360° שמושכת יתושים + רשת חשמלית 2200V — ללא כימיקלים. כיסוי 40 מ"ר, USB-C, 12 שעות פעולה. לאוהל ואיזור ישיבה.',
    benefits: [
      'ללא כימיקלים — בטוח לילדים',
      'UV 360° — מושך מכל כיוון',
      'כיסוי 40 מ"ר',
      'USB-C — טעינה מכל פאוורבנק',
    ],
    specs: [
      { label: 'כיסוי', value: '40 מ"ר' },
      { label: 'מתח רשת', value: '2200V' },
      { label: 'טעינה', value: 'USB-C 5V/1A' },
      { label: 'זמן פעולה', value: '12 שעות' },
      { label: 'משקל', value: '320 גרם' },
    ],
    faqs: [
      {
        question: 'עובד בחוץ?',
        answer: 'כן — יעיל יותר בחלל מוגן. מקמו 2-3 מטר מאיזור הישיבה.',
      },
    ],
    seoTitle: 'מחסל יתושים UV 40 מ"ר USB-C | CampIL',
    seoDescription: 'מחסל יתושים UV 360°, רשת 2200V, ללא כימיקלים, 40 מ"ר, USB-C. ₪89.',
    tags: ['מחסל יתושים', 'הדברה', 'קמפינג'],
    relatedSlugs: ['camp-chair-hd', 'tarp-uv-3x3'],
  },
];
