import type { Product } from '../types';

export const coffeeCookingProducts: Product[] = [

  /* ── 1. מכשיר האספרסו הנייד ─────────────────────────────────────── */
  {
    id: 'prod-001',
    name: 'מכשיר האספרסו הנייד',
    slug: 'espresso-nayad',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 279,
    rating: 4.9,
    reviewCount: 248,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-ESS-001',
    brand: 'Wacaco',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://wacaco.com/products/minipresso-ns',
    image: 'https://www.wacaco.com/cdn/shop/files/preview_images/Minipresso-NS-PNG-001-LD.png?v=1698806676',
    images: [
      'https://www.wacaco.com/cdn/shop/files/preview_images/Minipresso-NS-PNG-001-LD.png?v=1698806676',
      'https://www.wacaco.com/cdn/shop/files/Minipresso-NS-PNG-001-LD_16b447fa-c9b8-4d39-8f46-193a406e4f3a.png?v=1706258553',
      'https://www.wacaco.com/cdn/shop/products/Minipresso-NS-family-Tree-20190821_d67414b1-754f-4830-8d6d-79d8b7590231.png?v=1698806691',
      'https://www.wacaco.com/cdn/shop/products/Minipresso_NS_November_Web-1_REV2_05b8bb7c-5bfa-49f3-859c-764bb25c458f.jpg?v=1698806691',
      'https://www.wacaco.com/cdn/shop/products/Minipresso_NS_November_Web-3_REV2_8d7123de-3905-4742-b5db-6caa581646cb.jpg?v=1698806691',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=-Cev3cHjeUc',
    shortDescription: 'אספרסו אמיתי בשטח — ללא חשמל, ללא גז. 200 גרם. תואם קפסולות Nespresso Standard.',
    description: `כולנו יודעים את הרגע הזה. שש בבוקר בנגב, השמיים מתחילים להצטבע בכתום. מכשיר האספרסו הנייד נולד לרגע הזה.

אין חשמל? לא בעיה. רק מים חמים, קפסולת Nespresso ושתי ידיים. 30 שניות אחר כך יש לכם אספרסו אמיתי עם קרמה — 15 בר לחץ.`,
    benefits: [
      'תואם לכל קפסולות Nespresso Standard',
      'לא דורש חשמל, גז או סוללות',
      'לחץ 15 בר — קרמה אמיתית',
      'נירוסטה 304 — לא מחליד',
      '200 גרם — נכנס לכל כיס',
    ],
    specs: [
      { label: 'משקל', value: '200 גרם' },
      { label: 'קיבולת', value: '50 מ"ל' },
      { label: 'תאימות', value: 'Nespresso Standard' },
      { label: 'לחץ', value: '15 בר' },
      { label: 'חומר', value: 'נירוסטה 304 + BPA-free' },
    ],
    faqs: [
      {
        question: 'איזה קפסולות עובדות?',
        answer: 'כל קפסולות Nespresso Standard. לא עובד עם Vertuo או Dolce Gusto.',
      },
      {
        question: 'אפשר לקחת על מטוס?',
        answer: 'כן — אין בטריות, גז או נוזלים. עובר ביטחון ללא בעיה.',
      },
    ],
    seoTitle: 'מכשיר אספרסו נייד לשטח | Nespresso | ללא חשמל | CampIL',
    seoDescription: 'אספרסו אמיתי בכל מקום. 15 בר, 200 גרם, Nespresso. ללא חשמל וגז. ₪149.',
    tags: ['אספרסו שטח', 'קפה שטח', 'נספרסו נייד'],
    relatedSlugs: ['fire-starter', 'french-press-350', 'camp-stove-single'],
  },

  /* ── 2. כלי הצתה Swedish FireSteel Army 2-in-1 ──────────────────── */
  {
    id: 'prod-002',
    name: 'כלי הצתה Light My Fire Scout FireSteel Army',
    slug: 'fire-starter',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 109,
    rating: 4.9,
    reviewCount: 312,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-FST-001',
    brand: 'Light My Fire',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://lightmyfire.com/collections/fire',
    image: 'https://lightmyfire.com/cdn/shop/files/2111010310-SwedishFireSteel-army-rustyorange.jpg?v=1773136587',
    images: [
      'https://lightmyfire.com/cdn/shop/files/2111010310-SwedishFireSteel-army-rustyorange.jpg?v=1773136587',
      'https://lightmyfire.com/cdn/shop/files/2111011010-SwedishFireSteel-army-slatyblack.jpg?v=1772982251',
      'https://lightmyfire.com/cdn/shop/files/Swedish-FireSteel-InUse-1.jpg?v=1773740194',
      'https://lightmyfire.com/cdn/shop/files/Swedish-FireSteel-InUse-3.jpg?v=1773740194',
      'https://lightmyfire.com/cdn/shop/files/Swedish-FireSteel-InUse-5.jpg?v=1773740194',
    ],
    videoUrl: null,
    shortDescription: 'כלי ההצתה המקורי של השדה. 12,000 ניצוצות. עובד רטוב, קר ובכל גובה. עשוי שבדיה.',
    description: 'Light My Fire Scout FireSteel Army — כלי ההצתה המקורי שמשמש את הצבא השוודי. מגנזיום מיוחד שמייצר ניצוצות ב-2,980°C בכל תנאי מזג אוויר: גשם, קור, גובה ורוח. 12,000 ניצוצות מובטחים. מגיע עם גרדן מובנה.',
    benefits: [
      '12,000 ניצוצות מובטחים — מחזיק שנים',
      'עובד רטוב, קר ובגובה 4,000 מ׳',
      'ניצוצות ב-2,980°C — מדליק כל חומר בעירה',
      'גרדן מובנה — לא צריך כלים נוספים',
      '17 גרם — לא מורגש בכיס',
    ],
    specs: [
      { label: 'חומר', value: 'מגנזיום מיוחד' },
      { label: 'ניצוצות', value: '12,000 (מובטח)' },
      { label: 'טמפרטורת ניצוצות', value: '2,980°C' },
      { label: 'משקל', value: '17 גרם' },
      { label: 'מקור', value: 'שבדיה' },
    ],
    faqs: [
      {
        question: 'עובד בגשם?',
        answer: 'כן — המגנזיום עמיד למים. נגבו את הגרדן ומייצרת ניצוצות גם רטובה.',
      },
      {
        question: 'מה אפשר להדליק עמה?',
        answer: 'כל חומר בעירה: כותנה, עשב יבש, נייר, MayaSticks, אלכוהול ג\'ל, עצי הדלקה.',
      },
    ],
    seoTitle: 'כלי הצתה Light My Fire Scout FireSteel Army | 12,000 ניצוצות | CampIL',
    seoDescription: 'Scout FireSteel Army מקורי מ-Light My Fire. 12,000 ניצוצות, 2,980°C, עובד רטוב. ₪49.',
    tags: ['כלי הצתה', 'Fire Steel', 'הצתה שטח', 'Light My Fire'],
    relatedSlugs: ['espresso-nayad', 'camp-stove-single', 'camp-kettle-1l'],
  },

  /* ── 3. כיריים גז להבה אחת Piezo ───────────────────────────────── */
  {
    id: 'prod-201',
    name: 'כיריים גז שטח להבה אחת Piezo',
    slug: 'camp-stove-single',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 199,
    rating: 4.7,
    reviewCount: 176,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-STV-001',
    brand: 'MSR',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://cascadedesigns.com/products/pocketrocket-2-stove',
    image: 'https://cascadedesigns.com/cdn/shop/files/09884_MSR_PocketRocket2.jpg?v=1724820262',
    images: [
      'https://cascadedesigns.com/cdn/shop/files/09884_MSR_PocketRocket2.jpg?v=1724820262',
      'https://cascadedesigns.com/cdn/shop/files/09884_msr_pocketrocket_2_packed_2.jpg?v=1724820262',
      'https://cascadedesigns.com/cdn/shop/files/09884_msr_pocketrocket_2_packed_1.jpg?v=1724820261',
      'https://cascadedesigns.com/cdn/shop/files/2016-msr-pocketrocket2-cascades-rinckenberger-4241.jpg?v=1726592291',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=EJ98BB5CQhs',
    shortDescription: 'כיריים גז שטח קומפקטיות 2600W עם הצתה פיזו. עובדות עם כלי גז EN417, 215 גרם.',
    description: 'כיריים גז שטח 2600W, הצתה פיזו אוטומטית ורגליות מתקפלות. תואמות לכלי גז Butane/Propane EN417. מרתיחות ליטר מים ב-3.5 דקות.',
    benefits: [
      '2600W — ליטר מים רותח ב-3.5 דקות',
      'הצתה פיזו — לא צריך מצית',
      'ראש עם מגן רוח',
      '215 גרם — נכנסות לכיס',
    ],
    specs: [
      { label: 'עוצמה', value: '2600W' },
      { label: 'תאימות', value: 'Butane/Propane EN417' },
      { label: 'משקל', value: '215 גרם (ללא גז)' },
      { label: 'ממדים מקופל', value: '9×5 ס"מ' },
    ],
    faqs: [
      {
        question: 'איזה גז להשתמש?',
        answer: 'כלי גז Butane/Propane EN417. נמכר בחנויות קמפינג.',
      },
    ],
    seoTitle: 'כיריים גז שטח Piezo 2600W | 215 גרם | CampIL',
    seoDescription: 'כיריים גז שטח 2600W, Piezo, 215 גרם, EN417. ₪149.',
    tags: ['כיריים שטח', 'גז קמפינג', 'בישול שטח'],
    relatedSlugs: ['espresso-nayad', 'cook-set-4pc', 'camp-kettle-1l'],
  },

  /* ── 4. ערכת בישול 4 חלקים ─────────────────────────────────────── */
  {
    id: 'prod-202',
    name: 'ערכת בישול שטח 4 חלקים אלומיניום',
    slug: 'cook-set-4pc',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 149,
    originalPrice: 199,
    rating: 4.6,
    reviewCount: 122,
    badge: 'sale',
    inStock: true,
    sku: 'CAMP-CKS-001',
    brand: 'GSI Outdoors',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://gsioutdoors.com/products/bugaboo-camper',
    image: 'https://gsioutdoors.com/cdn/shop/products/44221_7_g.jpg?v=1756803758',
    images: [
      'https://gsioutdoors.com/cdn/shop/products/44221_7_g.jpg?v=1756803758',
      'https://gsioutdoors.com/cdn/shop/files/44231--Bugaboo-Camper-set.jpg?v=1756803758',
      'https://gsioutdoors.com/cdn/shop/files/44231--Bugaboo-Camper-plate.jpg?v=1756803758',
      'https://gsioutdoors.com/cdn/shop/files/44231--Bugaboo-Camper-cookset.jpg?v=1756803758',
      'https://gsioutdoors.com/cdn/shop/files/44231--Bugaboo-Camper_40c828a4-573a-435d-b946-9456ebc43e43.jpg?v=1756803758',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=jxMT84gkVRY',
    shortDescription: 'ערכת בישול 4 חלקים: סיר 1.3 ל׳, סיר 1.8 ל׳, מחבת ומכסה. אלומיניום אנודייז, 420 גרם.',
    description: 'ערכת בישול מאלומיניום אנודייז. סיר 1.3 ל׳, סיר 1.8 ל׳, מחבת ומכסה משותף — הכל מתחסס בסיר הגדול. מתאים לכיריים גז ולאש ישירה.',
    benefits: [
      'אלומיניום אנודייז — מוליך חום מהר',
      'מתחסס בסיר הגדול — אחסון מינימלי',
      'ידיות מתקפלות',
      'תואם לאש ישירה ולגז',
    ],
    specs: [
      { label: 'חלקים', value: 'סיר 1.3 ל׳, סיר 1.8 ל׳, מחבת, מכסה' },
      { label: 'חומר', value: 'אלומיניום אנודייז' },
      { label: 'משקל כולל', value: '420 גרם' },
      { label: 'ממדים ממוסה', value: '15×12 ס"מ' },
    ],
    faqs: [
      {
        question: 'עמידה לאש ישירה?',
        answer: 'כן — עמידה לאש ולגז. לא למיקרוגל.',
      },
    ],
    seoTitle: 'ערכת בישול שטח 4 חלקים אלומיניום | CampIL',
    seoDescription: 'ערכת בישול 4 חלקים, 420 גרם, אלומיניום אנודייז. ₪149.',
    tags: ['ערכת בישול', 'כלי בישול שטח', 'קמפינג'],
    relatedSlugs: ['camp-stove-single', 'camp-kettle-1l'],
  },

  /* ── 5. מחבת ברזל יצוק 24 ס"מ ─────────────────────────────────── */
  {
    id: 'prod-203',
    name: 'מחבת ברזל יצוק 24 ס"מ Pre-Seasoned',
    slug: 'cast-iron-24cm',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 199,
    rating: 4.8,
    reviewCount: 95,
    badge: 'new',
    inStock: true,
    sku: 'CAMP-CIP-001',
    brand: 'Lodge',
    deliveryTime: '7–10 ימי עסקים',
    sourceUrl: 'https://www.lodgecastiron.com/products/cast-iron-skillet',
    image: 'https://www.lodgecastiron.com/cdn/shop/files/L10SK3.jpg?v=1734125002',
    images: [
      'https://www.lodgecastiron.com/cdn/shop/files/L10SK3.jpg?v=1734125002',
      'https://www.lodgecastiron.com/cdn/shop/files/l10sk3_td.jpg?v=1742498969',
      'https://www.lodgecastiron.com/cdn/shop/files/l10sk3_l_86111208-924a-4b22-b176-9b575d857287.jpg?v=1742498970',
      'https://www.lodgecastiron.com/cdn/shop/files/l10sk3_s.jpg?v=1742498969',
      'https://www.lodgecastiron.com/cdn/shop/files/L10SK3_L_20d6a348-78a0-404d-bf14-a00e820e5c72.jpg?v=1741188784',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=j2ULSOEUJ30',
    shortDescription: 'מחבת ברזל יצוק 24 ס"מ Pre-Seasoned. לאש, גז וגריל. חלוקת חום אחידה לסטייק מושלם.',
    description: 'מחבת ברזל יצוק 24 ס"מ, Pre-Seasoned — מוכן לשימוש מהקופסה. מתאים לאש ישירה, גז וגריל. חלוקת חום אחידה לאורך כל משטח הבישול.',
    benefits: [
      'Pre-Seasoned — מוכן מהקופסה',
      'לאש, גז וגריל — גמישות מלאה',
      'חלוקת חום אחידה — ללא נקודות קרות',
      'עמידה לדורות',
    ],
    specs: [
      { label: 'קוטר', value: '24 ס"מ' },
      { label: 'חומר', value: 'ברזל יצוק Pre-Seasoned' },
      { label: 'משקל', value: '1.8 ק"ג' },
      { label: 'ידית', value: 'ברזל יצוק + מגן עץ' },
    ],
    faqs: [
      {
        question: 'איך מטפלים אחרי שימוש?',
        answer: 'שוטפים בעדינות, מייבשים מיידית, מורחים שמן דק. לא למדיח.',
      },
    ],
    seoTitle: 'מחבת ברזל יצוק 24 ס"מ Pre-Seasoned לשטח | CampIL',
    seoDescription: 'מחבת ברזל יצוק 24 ס"מ Pre-Seasoned. לאש, גז וגריל. ₪199.',
    tags: ['מחבת ברזל', 'בישול שטח', 'גריל'],
    relatedSlugs: ['camp-stove-single', 'cook-set-4pc'],
  },

  /* ── 6. קומקום טיטניום 1 ל׳ ─────────────────────────────────────── */
  {
    id: 'prod-204',
    name: 'קומקום שטח טיטניום 1 ל׳',
    slug: 'camp-kettle-1l',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 199,
    rating: 4.7,
    reviewCount: 87,
    inStock: true,
    sku: 'CAMP-KTL-001',
    brand: 'TOAKS',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://www.toaksoutdoor.com/products/pot-1100',
    image: 'https://www.toaksoutdoor.com/cdn/shop/files/1100_main.png?v=1747238195',
    images: [
      'https://www.toaksoutdoor.com/cdn/shop/files/1100_main.png?v=1747238195',
      'https://www.toaksoutdoor.com/cdn/shop/products/POT-1100-02-new.jpg?v=1747238195',
      'https://www.toaksoutdoor.com/cdn/shop/products/POT-1100-03-new.jpg?v=1747238195',
      'https://www.toaksoutdoor.com/cdn/shop/products/POT-1100-04-new.jpg?v=1747238195',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=QB9UsKvwNVk',
    shortDescription: 'קומקום טיטניום 1 ל׳, 180 גרם. פיה מדויקת, רותח ב-3 דקות. לאספרסו ולפרנץ׳ פרס.',
    description: 'קומקום שטח טיטניום טהור 1 ל׳. רותח מהר, 180 גרם, לא מחליד. פיה מדויקת לשפיכה מבוקרת — אידיאלי לאספרסו ול-pour-over.',
    benefits: [
      'טיטניום — קל מאלומיניום',
      '180 גרם — הקל ביותר ל-1 ל׳',
      'פיה מדויקת — לאספרסו ולפרנץ׳ פרס',
      'לא מחליד, לא מעביר טעמים',
    ],
    specs: [
      { label: 'חומר', value: 'טיטניום טהור' },
      { label: 'נפח', value: '1 ל׳' },
      { label: 'משקל', value: '180 גרם' },
      { label: 'זמן רתיחה', value: '~3 דקות' },
    ],
    faqs: [
      {
        question: 'אפשר לחמם ישירות על אש?',
        answer: 'כן — טיטניום עמיד לאש ישירה.',
      },
    ],
    seoTitle: 'קומקום שטח טיטניום 1 ל׳ | 180 גרם | CampIL',
    seoDescription: 'קומקום שטח טיטניום 1 ל׳, 180 גרם, פיה מדויקת. ₪99.',
    tags: ['קומקום שטח', 'קומקום טיטניום', 'קפה שטח'],
    relatedSlugs: ['espresso-nayad', 'french-press-350', 'camp-stove-single'],
  },

  /* ── 7. פרנץ׳ פרס 350 מ"ל ──────────────────────────────────────── */
  {
    id: 'prod-205',
    name: 'פרנץ׳ פרס שטח נירוסטה 350 מ"ל',
    slug: 'french-press-350',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 149,
    rating: 4.8,
    reviewCount: 134,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-FRP-001',
    brand: 'GSI Outdoors',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://gsioutdoors.com/products/glacier-stainless-javapress',
    image: 'https://gsioutdoors.com/cdn/shop/products/65095_0_i.jpg?v=1756803418',
    images: [
      'https://gsioutdoors.com/cdn/shop/products/65095_0_i.jpg?v=1756803418',
      'https://gsioutdoors.com/cdn/shop/products/65095_3_g.jpg?v=1756803418',
      'https://gsioutdoors.com/cdn/shop/products/65095_4_g.jpg?v=1756803418',
      'https://gsioutdoors.com/cdn/shop/products/65095_2_g.jpg?v=1756803418',
      'https://gsioutdoors.com/cdn/shop/products/65095_6_g.jpg?v=1756803418',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=IzQyhLaft-s',
    shortDescription: 'פרנץ׳ פרס נירוסטה כפולת דופן 350 מ"ל. שומר חם 40 דקות. ל-2 כוסות בישרה אחת.',
    description: 'פרנץ׳ פרס שטח מנירוסטה 18/8 כפולת דופן, 350 מ"ל. שומר חם 40 דקות, פילטר דק-רשת 100 מיקרון. נכנס לתוך כוס הטיטניום 500 מ"ל.',
    benefits: [
      'דופן כפולה — שומר חם 40 דקות',
      'נירוסטה 18/8 — לא מחליד',
      'פילטר 100 מיקרון — קפה נקי',
      'מכסה אטום — אפשר לטלטל',
    ],
    specs: [
      { label: 'חומר', value: 'נירוסטה 18/8 כפולת דופן' },
      { label: 'נפח', value: '350 מ"ל (2 כוסות)' },
      { label: 'פילטר', value: '100 מיקרון' },
      { label: 'שמירת חום', value: '40 דקות' },
      { label: 'משקל', value: '235 גרם' },
    ],
    faqs: [
      {
        question: 'כמה זמן להשרות?',
        answer: '4 דקות לקפה בינוני. לאחר הלחיצה — שתו מיד.',
      },
    ],
    seoTitle: 'פרנץ׳ פרס שטח נירוסטה 350 מ"ל | CampIL',
    seoDescription: 'פרנץ׳ פרס שטח נירוסטה 350 מ"ל, דופן כפולה, 40 דקות שמירת חום. ₪99.',
    tags: ['פרנץ פרס', 'קפה שטח', 'כלי קפה'],
    relatedSlugs: ['espresso-nayad', 'camp-kettle-1l'],
  },

  /* ── 8. לוח חיתוך מתקפל PE ─────────────────────────────────────── */
  {
    id: 'prod-206',
    name: 'לוח חיתוך מתקפל PE BPA-free',
    slug: 'cutting-board-fold',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 99,
    rating: 4.5,
    reviewCount: 68,
    inStock: true,
    sku: 'CAMP-CBR-001',
    brand: 'GSI Outdoors',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://gsioutdoors.com/products/folding-cutting-board',
    image: 'https://gsioutdoors.com/cdn/shop/products/76004_0_i.jpg?v=1756803345',
    images: [
      'https://gsioutdoors.com/cdn/shop/products/76004_0_i.jpg?v=1756803345',
      'https://gsioutdoors.com/cdn/shop/products/76004_2_g.jpg?v=1756803345',
    ],
    videoUrl: null,
    shortDescription: 'לוח חיתוך PE מתקפל 35×25 ס"מ עם ידית תלייה. BPA-free, 145 גרם, שטיפה קלה.',
    description: 'לוח חיתוך PE BPA-free, 35×25 ס"מ. מתקפל לשניים לאחסון, ידית תלייה לייבוש. קשיח לחיתוך, רך לשמירת חדות הסכין.',
    benefits: [
      'BPA-free — בטוח למגע מזון',
      'מתקפל — נכנס לסיר',
      'ידית תלייה — ייבוש קל',
      'PE רך — שומר חדות הסכין',
    ],
    specs: [
      { label: 'חומר', value: 'PE (BPA-free)' },
      { label: 'ממדים', value: '35×25 ס"מ' },
      { label: 'עובי', value: '3 מ"מ' },
      { label: 'משקל', value: '145 גרם' },
    ],
    faqs: [
      {
        question: 'אפשר לשטוף עם סבון?',
        answer: 'כן — PE עמיד לסבון ומים חמים. לא בתנור מיקרוגל.',
      },
    ],
    seoTitle: 'לוח חיתוך מתקפל PE BPA-free לשטח | CampIL',
    seoDescription: 'לוח חיתוך PE מתקפל 35×25 ס"מ, BPA-free, ידית תלייה. ₪49.',
    tags: ['לוח חיתוך', 'כלי בישול שטח', 'קמפינג'],
    relatedSlugs: ['cook-set-4pc', 'camp-stove-single'],
  },

  /* ── 9. כוסות אמייל ערכת 4 ─────────────────────────────────────── */
  {
    id: 'prod-207',
    name: 'כוסות אמייל שטח 300 מ"ל — ערכת 4',
    slug: 'enamel-cups-set',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 79,
    rating: 4.6,
    reviewCount: 201,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-CUP-001',
    brand: 'Falcon Enamelware',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://us.falconenamelware.com/products/enamel-mug',
    image: 'https://us.falconenamelware.com/cdn/shop/files/Mug_900x.jpg?v=12454795270939318282',
    images: [
      'https://us.falconenamelware.com/cdn/shop/files/Mug_900x.jpg?v=12454795270939318282',
      'https://us.falconenamelware.com/cdn/shop/products/falcon-mug-original_white_blue-pkg-rgb_653cfd94-028f-40ce-ae4a-36b08a52f29a_1024x.jpg?v=1653665799',
      'https://gsioutdoors.com/cdn/shop/products/13208_0_i.jpg?v=1756803456',
      'https://gsioutdoors.com/cdn/shop/products/08308_4_g.jpg?v=1756803456',
    ],
    videoUrl: null,
    shortDescription: 'ערכת 4 כוסות אמייל קלאסיות 300 מ"ל. עמידות לאש, לא מעבירות טעמים.',
    description: 'ארבע כוסות אמייל קלאסיות 300 מ"ל — עמידות לחום ולאש ישירה. ציפוי אמייל כפול על בסיס פלדה. לקפה, תה, שוקולד חם ומרק.',
    benefits: [
      'עמידות לאש — חמות כוס ישירות על פח',
      'אמייל כפול — לא מעביר טעמים',
      'ידית נוחה גם לשתייה חמה',
      'ערכת 4 — לכל הקבוצה',
    ],
    specs: [
      { label: 'נפח', value: '300 מ"ל לכוס' },
      { label: 'חומר', value: 'פלדה + אמייל כפול' },
      { label: 'משקל', value: '110 גרם לכוס' },
      { label: 'כמות', value: '4 כוסות' },
    ],
    faqs: [
      {
        question: 'עמידות למדיח?',
        answer: 'לא מומלץ — שטיפה ידנית שומרת את הציפוי.',
      },
    ],
    seoTitle: 'כוסות אמייל שטח 300 מ"ל ערכת 4 | CampIL',
    seoDescription: 'ערכת 4 כוסות אמייל 300 מ"ל. עמידות לאש, לא מחלידות. ₪79.',
    tags: ['כוסות אמייל', 'כלי שתייה שטח', 'קמפינג'],
    relatedSlugs: ['french-press-350', 'espresso-nayad'],
  },

  /* ── 10. גריל שולחני נייד ─────────────────────────────────────── */
  {
    id: 'prod-208',
    name: 'גריל BBQ נייד Weber Go-Anywhere 37 ס"מ',
    slug: 'tabletop-grill',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 369,
    originalPrice: 449,
    rating: 4.7,
    reviewCount: 63,
    badge: 'sale',
    inStock: true,
    sku: 'CAMP-GRL-001',
    brand: 'Weber',
    deliveryTime: '7–10 ימי עסקים',
    sourceUrl: 'https://www.weber.com/US/en/grills/charcoal-grills/go-anywhere-charcoal-grill/1500763.html',
    image: 'https://product-images.weber.com/Grill-Images/Charcoal/1500763B-1800x1800-781d0b1.png',
    images: [
      'https://product-images.weber.com/Grill-Images/Charcoal/1500763B-1800x1800-781d0b1.png',
      'https://product-images.weber.com/Grill-Images/Charcoal/Lifestyles/01_1500763_GoAnywhere_1800x1800.jpg',
      'https://product-images.weber.com/Grill-Images/Charcoal/Lifestyles/02_1500763_GoAnywhere_1800x1800.jpg',
      'https://product-images.weber.com/Grill-Images/Charcoal/Lifestyles/03_1500763_GoAnywhere_1800x1800.jpg',
      'https://product-images.weber.com/Grill-Images/Charcoal/Lifestyles/04_1500763_GoAnywhere_1800x1800.jpg',
    ],
    videoUrl: null,
    shortDescription: 'גריל פחמים נייד Weber Go-Anywhere 37×22 ס"מ. רגליות מתקפלות, ידית נשיאה, לאש ופחמים.',
    description: 'גריל פחמים נייד Weber Go-Anywhere בגודל 37×22 ס"מ — הגריל הנייד הכי ידוע בעולם. מכסה ציפוי-פורצלן, רגליות מתקפלות כנעילה, ידית נשיאה מובנית. עמיד לכל מזג אוויר.',
    benefits: [
      'פורצלן מצופה — לא מחליד',
      'רגליות נועלות — בטוח לנשיאה',
      'ידית מובנית — נוח לשאת',
      'Weber — 70 שנות אמינות',
    ],
    specs: [
      { label: 'חומר', value: 'פלדה מצופה פורצלן' },
      { label: 'ממדי שבכה', value: '37×22 ס"מ' },
      { label: 'גובה', value: '37 ס"מ עם רגליות' },
      { label: 'משקל', value: '2 ק"ג' },
    ],
    faqs: [
      {
        question: 'כמה זמן להחמין פחמים?',
        answer: '15-20 דקות. לאש ישירה — מוכן מיד.',
      },
    ],
    seoTitle: 'גריל BBQ נייד Weber Go-Anywhere | 37 ס"מ | CampIL',
    seoDescription: 'גריל פחמים נייד Weber Go-Anywhere, 37×22 ס"מ, רגליות מתקפלות. ₪199.',
    tags: ['גריל קמפינג', 'BBQ שטח', 'גריל נייד'],
    relatedSlugs: ['cast-iron-24cm', 'camp-stove-single'],
  },

  /* ── 11. כיריים גז 2 להבות ─────────────────────────────────────── */
  {
    id: 'prod-209',
    name: 'כיריים גז שטח 2 להבות + מגן רוח',
    slug: 'camp-stove-double',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 179,
    rating: 4.7,
    reviewCount: 88,
    inStock: true,
    sku: 'CAMP-STV-002',
    brand: 'Camp Chef',
    deliveryTime: '7–10 ימי עסקים',
    sourceUrl: 'https://www.campchef.com/collections/camp-stoves/products/everest-2x',
    image: 'https://www.campchef.com/cdn/shop/files/b1835a4b0ede6d513c9508b4f29531896573d9d1.jpg?v=1768053691',
    images: [
      'https://www.campchef.com/cdn/shop/files/b1835a4b0ede6d513c9508b4f29531896573d9d1.jpg?v=1768053691',
      'https://www.campchef.com/cdn/shop/files/a84cdb0ff4b089f51c007b0a7b73bdf328b4ea4e.jpg?v=1768053691',
      'https://www.campchef.com/cdn/shop/files/fe8b5b55a8683e71fa7a2daa2e605d796cfed7cb.jpg?v=1768053691',
    ],
    videoUrl: null,
    shortDescription: 'כיריים גז שטח 2 להבות 3200W+2000W עם מגן רוח מובנה. לבישול משפחתי שלם.',
    description: 'כיריים גז 2 להבות: ראשית 3200W, קטנה 2000W. מגן רוח מובנה, כפתורים כפולים. תואם לגלילי 227 ו-450 גרם.',
    benefits: [
      '3200W + 2000W — סיר ומחבת בו-זמנית',
      'מגן רוח מובנה — עובד בשדה פתוח',
      'כפתורים כפולים — שליטה עדינה',
      'תואם לגלילי 227 ו-450 גרם',
    ],
    specs: [
      { label: 'להבה ראשית', value: '3200W' },
      { label: 'להבה שנייה', value: '2000W' },
      { label: 'תאימות', value: 'Butane/Propane EN417' },
      { label: 'ממדים', value: '38×26×8 ס"מ' },
      { label: 'משקל', value: '1.1 ק"ג' },
    ],
    faqs: [
      {
        question: 'אפשר להשתמש מחוץ לרכב?',
        answer: 'כן — על משטח יציב. לא לשימוש בסביבה סגורה.',
      },
    ],
    seoTitle: 'כיריים גז שטח 2 להבות 3200W | מגן רוח | CampIL',
    seoDescription: 'כיריים גז שטח 2 להבות 3200W+2000W, מגן רוח. ₪179.',
    tags: ['כיריים שטח', 'גז קמפינג', 'בישול משפחתי'],
    relatedSlugs: ['cook-set-4pc', 'cast-iron-24cm'],
  },

  /* ── 12. כלי אכילה טיטניום ──────────────────────────────────────── */
  {
    id: 'prod-210',
    name: 'ערכת כלי אכילה טיטניום 3 חלקים',
    slug: 'titanium-cutlery',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 129,
    rating: 4.6,
    reviewCount: 109,
    badge: 'new',
    inStock: true,
    sku: 'CAMP-CTL-001',
    brand: 'Light My Fire',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://lightmyfire.com/products/spork-kit-titanium',
    image: 'https://lightmyfire.com/cdn/shop/files/4218101110-SwedishSpork-KitTitanium_c76e6e03-8fda-4d2b-b077-383122477cfd.jpg',
    images: [
      'https://lightmyfire.com/cdn/shop/files/4218101110-SwedishSpork-KitTitanium_c76e6e03-8fda-4d2b-b077-383122477cfd.jpg',
      'https://lightmyfire.com/cdn/shop/files/SwedishSpork-KitTitanium-InUse-Photo-1.jpg',
      'https://lightmyfire.com/cdn/shop/files/SwedishSpork-KitTitanium-InUse-Photo-3.jpg',
      'https://lightmyfire.com/cdn/shop/files/SwedishSpork-KitTitanium-InUse-Photo-5.jpg',
    ],
    videoUrl: null,
    shortDescription: 'כף, מזלג ומרית טיטניום. 47 גרם לסט. לא מחלידים, לא מעבירים טעמים. כולל קייס.',
    description: 'ערכת כלי אכילה טיטניום 3 חלקים: כף, מזלג ומרית. 47 גרם לסט — קל פי-3 מנירוסטה. לא מחלידים, לא מעבירים טעמים. כולל קייס מיקרופייבר.',
    benefits: [
      'טיטניום — קל פי-3 מנירוסטה',
      '47 גרם לסט — לא מורגש בתיק',
      'לא מחלידים ולא מעבירים טעמים',
      'קייס מיקרופייבר כלול',
    ],
    specs: [
      { label: 'חומר', value: 'טיטניום Grade 2' },
      { label: 'חלקים', value: 'כף + מזלג + מרית' },
      { label: 'משקל', value: '47 גרם' },
      { label: 'אורך', value: '18 ס"מ' },
    ],
    faqs: [
      {
        question: 'עמידים לסירים נון-סטיק?',
        answer: 'כן — קצוות מלוטשים לא פוגעים בציפוי.',
      },
    ],
    seoTitle: 'כלי אכילה טיטניום שטח | 47 גרם | ערכת 3 | CampIL',
    seoDescription: 'כלי אכילה טיטניום 3 חלקים, 47 גרם, קייס כלול. ₪99.',
    tags: ['כלי אכילה טיטניום', 'כלי שטח', 'קמפינג'],
    relatedSlugs: ['cook-set-4pc', 'enamel-cups-set'],
  },
];
