import type { Product } from '../types';

// NOTE: picsum.photos seeds are development placeholders.
// Replace with actual product supplier photos before going live.

export const coffeeCookingProducts: Product[] = [

  /* ── 1. מכשיר האספרסו הנייד (מוצר קיים) ──────────────────────── */
  {
    id: 'prod-001',
    name: 'מכשיר האספרסו הנייד',
    slug: 'espresso-nayad',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 149,
    originalPrice: 199,
    rating: 4.9,
    reviewCount: 248,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-ESS-001',
    image: '/images/products/espresso-maker.webp',
    images: [
      '/images/products/espresso-maker.webp',
      '/images/products/espresso-maker-2.webp',
    ],
    videoUrl: null,
    shortDescription: 'אספרסו אמיתי בשטח — ללא חשמל, ללא גז. 200 גרם. תואם קפסולות Nespresso Standard.',
    description: `כולנו יודעים את הרגע הזה. שש בבוקר בנגב, השמיים מתחילים להצטבע בכתום. מכשיר האספרסו הנייד נולד לרגע הזה.

אין חשמל? לא בעיה. רק מים חמים, קפסולת Nespresso ושתי ידיים. 30 שניות אחר כך יש לכם אספרסו אמיתי עם קרמה — 15 בר לחץ.`,
    benefits: [
      'תואם לכל קפסולות Nespresso Standard',
      'לא דורש חשמל, גז או סוללות',
      'לחץ 15 בר — קרמה אמיתית',
      'נירוסטה 304 — לא מחליד',
      '200 גרם — נכנס לכל כיס',
    ],
    specs: [
      { label: 'משקל', value: '200 גרם' },
      { label: 'קיבולת', value: '50 מ"ל' },
      { label: 'תאימות', value: 'Nespresso Standard' },
      { label: 'לחץ', value: '15 בר' },
      { label: 'חומר', value: 'נירוסטה 304 + BPA-free' },
    ],
    faqs: [
      {
        question: 'איזה קפסולות עובדות?',
        answer: 'כל קפסולות Nespresso Standard. לא עובד עם Vertuo או Dolce Gusto.',
      },
      {
        question: 'אפשר לקחת על מטוס?',
        answer: 'כן — אין בטריות, גז או נוזלים. עובר ביטחון ללא בעיה.',
      },
    ],
    seoTitle: 'מכשיר אספרסו נייד לשטח | Nespresso | ללא חשמל | CampIL',
    seoDescription: 'אספרסו אמיתי בכל מקום. 15 בר, 200 גרם, Nespresso. ללא חשמל וגז. ₪149.',
    tags: ['אספרסו שטח', 'קפה שטח', 'נספרסו נייד'],
    relatedSlugs: ['plasma-lighter', 'french-press-350', 'camp-stove-single'],
  },

  /* ── 2. מצית הפלזמה (מוצר קיים) ───────────────────────────────── */
  {
    id: 'prod-002',
    name: 'מצית הפלזמה של השטח',
    slug: 'plasma-lighter',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 79,
    originalPrice: 109,
    rating: 4.8,
    reviewCount: 189,
    badge: 'new',
    inStock: true,
    sku: 'CAMP-LIT-001',
    image: '/images/products/plasma-lighter.jpg',
    images: [
      '/images/products/plasma-lighter.jpg',
    ],
    videoUrl: null,
    shortDescription: 'קשת פלזמה כפולה שמדליקה בכל תנאי. USB-C, 300 הדלקות, גוף אבץ יצוק.',
    description: 'קשת פלזמה כפולה — לא אש, לא גז. עובדת בגשם, קור, גובה ומדבר. USB-C, ~300 הדלקות לטעינה. גוף סגסוגת אבץ יצוקה.',
    benefits: [
      'קשת כפולה — עד 80 קמ"ש רוח',
      'USB-C — 60 דקות לטעינה מלאה',
      'ללא גז — ללא כשלים בגובה',
      'גוף אבץ יצוק — לא פלסטיק',
      '~300 הדלקות לטעינה',
    ],
    specs: [
      { label: 'גוף', value: 'סגסוגת אבץ יצוקה' },
      { label: 'קשת', value: 'פלזמה כפולה' },
      { label: 'טעינה', value: 'USB-C, ~60 דקות' },
      { label: 'הדלקות', value: '~300 לטעינה' },
      { label: 'משקל', value: '68 גרם' },
    ],
    faqs: [
      {
        question: 'עובדת בגובה?',
        answer: 'כן — אין תלות בלחץ אוויר. עובדת בגובה 3,000 מ׳ באותה יעילות.',
      },
    ],
    seoTitle: 'מצית פלזמה כפולה לשטח | USB-C | CampIL',
    seoDescription: 'מצית פלזמה כפולה USB-C, גוף אבץ יצוק, 300 הדלקות. ₪79.',
    tags: ['מצית פלזמה', 'מצית שטח', 'מצית USB'],
    relatedSlugs: ['espresso-nayad', 'camp-stove-single'],
  },

  /* ── 3. כיריים גז להבה אחת Piezo ───────────────────────────────── */
  {
    id: 'prod-201',
    name: 'כיריים גז שטח להבה אחת Piezo',
    slug: 'camp-stove-single',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 149,
    originalPrice: 199,
    rating: 4.7,
    reviewCount: 176,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-STV-001',
    image: 'https://picsum.photos/seed/camp-stove-single/800/600',
    images: [
      'https://picsum.photos/seed/camp-stove-single/800/600',
      'https://picsum.photos/seed/camp-stove-single-2/800/600',
      'https://picsum.photos/seed/camp-stove-single-3/800/600',
    ],
    videoUrl: null,
    shortDescription: 'כיריים גז שטח קומפקטיות 2600W עם הצתה פיזו. עובדות עם כלי גז EN417, 215 גרם.',
    description: 'כיריים גז שטח 2600W, הצתה פיזו אוטומטית ורגליות מתקפלות. תואמות לכלי גז Butane/Propane EN417. מרתיחות ליטר מים ב-3.5 דקות.',
    benefits: [
      '2600W — ליטר מים רותח ב-3.5 דקות',
      'הצתה פיזו — לא צריך מצית',
      'ראש עם מגן רוח',
      '215 גרם — נכנסות לכיס',
    ],
    specs: [
      { label: 'עוצמה', value: '2600W' },
      { label: 'תאימות', value: 'Butane/Propane EN417' },
      { label: 'משקל', value: '215 גרם (ללא גז)' },
      { label: 'ממדים מקופל', value: '9×5 ס"מ' },
    ],
    faqs: [
      {
        question: 'איזה גז להשתמש?',
        answer: 'כלי גז Butane/Propane EN417. נמכר בחנויות קמפינג.',
      },
    ],
    seoTitle: 'כיריים גז שטח Piezo 2600W | 215 גרם | CampIL',
    seoDescription: 'כיריים גז שטח 2600W, Piezo, 215 גרם, EN417. ₪149.',
    tags: ['כיריים שטח', 'גז קמפינג', 'בישול שטח'],
    relatedSlugs: ['espresso-nayad', 'cook-set-4pc', 'camp-kettle-1l'],
  },

  /* ── 4. ערכת בישול 4 חלקים ─────────────────────────────────────── */
  {
    id: 'prod-202',
    name: 'ערכת בישול שטח 4 חלקים אלומיניום',
    slug: 'cook-set-4pc',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 149,
    originalPrice: 199,
    rating: 4.6,
    reviewCount: 122,
    badge: 'sale',
    inStock: true,
    sku: 'CAMP-CKS-001',
    image: 'https://picsum.photos/seed/cook-set-4pc/800/600',
    images: [
      'https://picsum.photos/seed/cook-set-4pc/800/600',
      'https://picsum.photos/seed/cook-set-4pc-2/800/600',
      'https://picsum.photos/seed/cook-set-4pc-3/800/600',
    ],
    videoUrl: null,
    shortDescription: 'ערכת בישול 4 חלקים: סיר 1.3 ל׳, סיר 1.8 ל׳, מחבת ומכסה. אלומיניום אנודייז, 420 גרם.',
    description: 'ערכת בישול מאלומיניום אנודייז. סיר 1.3 ל׳, סיר 1.8 ל׳, מחבת ומכסה משותף — הכל מתחסס בסיר הגדול. מתאים לכיריים גז ולאש ישירה.',
    benefits: [
      'אלומיניום אנודייז — מוליך חום מהר',
      'מתחסס בסיר הגדול — אחסון מינימלי',
      'ידיות מתקפלות',
      'תואם לאש ישירה ולגז',
    ],
    specs: [
      { label: 'חלקים', value: 'סיר 1.3 ל׳, סיר 1.8 ל׳, מחבת, מכסה' },
      { label: 'חומר', value: 'אלומיניום אנודייז' },
      { label: 'משקל כולל', value: '420 גרם' },
      { label: 'ממדים ממוסה', value: '15×12 ס"מ' },
    ],
    faqs: [
      {
        question: 'עמידה לאש ישירה?',
        answer: 'כן — עמידה לאש ולגז. לא למיקרוגל.',
      },
    ],
    seoTitle: 'ערכת בישול שטח 4 חלקים אלומיניום | CampIL',
    seoDescription: 'ערכת בישול 4 חלקים, 420 גרם, אלומיניום אנודייז. ₪149.',
    tags: ['ערכת בישול', 'כלי בישול שטח', 'קמפינג'],
    relatedSlugs: ['camp-stove-single', 'camp-kettle-1l'],
  },

  /* ── 5. מחבת ברזל יצוק 24 ס"מ ─────────────────────────────────── */
  {
    id: 'prod-203',
    name: 'מחבת ברזל יצוק 24 ס"מ Pre-Seasoned',
    slug: 'cast-iron-24cm',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 199,
    originalPrice: 269,
    rating: 4.8,
    reviewCount: 95,
    badge: 'new',
    inStock: true,
    sku: 'CAMP-CIP-001',
    image: 'https://picsum.photos/seed/cast-iron-24cm/800/600',
    images: [
      'https://picsum.photos/seed/cast-iron-24cm/800/600',
      'https://picsum.photos/seed/cast-iron-24cm-2/800/600',
      'https://picsum.photos/seed/cast-iron-24cm-3/800/600',
    ],
    videoUrl: null,
    shortDescription: 'מחבת ברזל יצוק 24 ס"מ Pre-Seasoned. לאש, גז וגריל. חלוקת חום אחידה לסטייק מושלם.',
    description: 'מחבת ברזל יצוק 24 ס"מ, Pre-Seasoned — מוכן לשימוש מהקופסה. מתאים לאש ישירה, גז וגריל. חלוקת חום אחידה לאורך כל משטח הבישול.',
    benefits: [
      'Pre-Seasoned — מוכן מהקופסה',
      'לאש, גז וגריל — גמישות מלאה',
      'חלוקת חום אחידה — ללא נקודות קרות',
      'עמידה לדורות',
    ],
    specs: [
      { label: 'קוטר', value: '24 ס"מ' },
      { label: 'חומר', value: 'ברזל יצוק Pre-Seasoned' },
      { label: 'משקל', value: '1.8 ק"ג' },
      { label: 'ידית', value: 'ברזל יצוק + מגן עץ' },
    ],
    faqs: [
      {
        question: 'איך מטפלים אחרי שימוש?',
        answer: 'שוטפים בעדינות, מייבשים מיידית, מורחים שמן דק. לא למדיח.',
      },
    ],
    seoTitle: 'מחבת ברזל יצוק 24 ס"מ Pre-Seasoned לשטח | CampIL',
    seoDescription: 'מחבת ברזל יצוק 24 ס"מ Pre-Seasoned. לאש, גז וגריל. ₪199.',
    tags: ['מחבת ברזל', 'בישול שטח', 'גריל'],
    relatedSlugs: ['camp-stove-single', 'cook-set-4pc'],
  },

  /* ── 6. קומקום טיטניום 1 ל׳ ─────────────────────────────────────── */
  {
    id: 'prod-204',
    name: 'קומקום שטח טיטניום 1 ל׳',
    slug: 'camp-kettle-1l',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 99,
    originalPrice: 139,
    rating: 4.7,
    reviewCount: 87,
    inStock: true,
    sku: 'CAMP-KTL-001',
    image: 'https://picsum.photos/seed/camp-kettle-1l/800/600',
    images: [
      'https://picsum.photos/seed/camp-kettle-1l/800/600',
      'https://picsum.photos/seed/camp-kettle-1l-2/800/600',
    ],
    videoUrl: null,
    shortDescription: 'קומקום טיטניום 1 ל׳, 180 גרם. פיה מדויקת, רותח ב-3 דקות. לאספרסו ולפרנץ׳ פרס.',
    description: 'קומקום שטח טיטניום טהור 1 ל׳. רותח מהר, 180 גרם, לא מחליד. פיה מדויקת לשפיכה מבוקרת — אידיאלי לאספרסו ול-pour-over.',
    benefits: [
      'טיטניום — קל מאלומיניום',
      '180 גרם — הקל ביותר ל-1 ל׳',
      'פיה מדויקת — לאספרסו ולפרנץ׳ פרס',
      'לא מחליד, לא מעביר טעמים',
    ],
    specs: [
      { label: 'חומר', value: 'טיטניום טהור' },
      { label: 'נפח', value: '1 ל׳' },
      { label: 'משקל', value: '180 גרם' },
      { label: 'זמן רתיחה', value: '~3 דקות' },
    ],
    faqs: [
      {
        question: 'אפשר לחמם ישירות על אש?',
        answer: 'כן — טיטניום עמיד לאש ישירה.',
      },
    ],
    seoTitle: 'קומקום שטח טיטניום 1 ל׳ | 180 גרם | CampIL',
    seoDescription: 'קומקום שטח טיטניום 1 ל׳, 180 גרם, פיה מדויקת. ₪99.',
    tags: ['קומקום שטח', 'קומקום טיטניום', 'קפה שטח'],
    relatedSlugs: ['espresso-nayad', 'french-press-350', 'camp-stove-single'],
  },

  /* ── 7. פרנץ׳ פרס 350 מ"ל ──────────────────────────────────────── */
  {
    id: 'prod-205',
    name: 'פרנץ׳ פרס שטח נירוסטה 350 מ"ל',
    slug: 'french-press-350',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 99,
    originalPrice: 139,
    rating: 4.8,
    reviewCount: 134,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-FRP-001',
    image: 'https://picsum.photos/seed/french-press-350/800/600',
    images: [
      'https://picsum.photos/seed/french-press-350/800/600',
      'https://picsum.photos/seed/french-press-350-2/800/600',
      'https://picsum.photos/seed/french-press-350-3/800/600',
    ],
    videoUrl: null,
    shortDescription: 'פרנץ׳ פרס נירוסטה כפולת דופן 350 מ"ל. שומר חם 40 דקות. ל-2 כוסות בישרה אחת.',
    description: 'פרנץ׳ פרס שטח מנירוסטה 18/8 כפולת דופן, 350 מ"ל. שומר חם 40 דקות, פילטר דק-רשת 100 מיקרון. נכנס לתוך כוס הטיטניום 500 מ"ל.',
    benefits: [
      'דופן כפולה — שומר חם 40 דקות',
      'נירוסטה 18/8 — לא מחליד',
      'פילטר 100 מיקרון — קפה נקי',
      'מכסה אטום — אפשר לטלטל',
    ],
    specs: [
      { label: 'חומר', value: 'נירוסטה 18/8 כפולת דופן' },
      { label: 'נפח', value: '350 מ"ל (2 כוסות)' },
      { label: 'פילטר', value: '100 מיקרון' },
      { label: 'שמירת חום', value: '40 דקות' },
      { label: 'משקל', value: '235 גרם' },
    ],
    faqs: [
      {
        question: 'כמה זמן להשרות?',
        answer: '4 דקות לקפה בינוני. לאחר הלחיצה — שתו מיד.',
      },
    ],
    seoTitle: 'פרנץ׳ פרס שטח נירוסטה 350 מ"ל | CampIL',
    seoDescription: 'פרנץ׳ פרס שטח נירוסטה 350 מ"ל, דופן כפולה, 40 דקות שמירת חום. ₪99.',
    tags: ['פרנץ פרס', 'קפה שטח', 'כלי קפה'],
    relatedSlugs: ['espresso-nayad', 'camp-kettle-1l'],
  },

  /* ── 8. לוח חיתוך מתקפל PE ─────────────────────────────────────── */
  {
    id: 'prod-206',
    name: 'לוח חיתוך מתקפל PE BPA-free',
    slug: 'cutting-board-fold',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 49,
    originalPrice: 69,
    rating: 4.5,
    reviewCount: 68,
    inStock: true,
    sku: 'CAMP-CBR-001',
    image: 'https://picsum.photos/seed/cutting-board-fold/800/600',
    images: [
      'https://picsum.photos/seed/cutting-board-fold/800/600',
      'https://picsum.photos/seed/cutting-board-fold-2/800/600',
    ],
    videoUrl: null,
    shortDescription: 'לוח חיתוך PE מתקפל 35×25 ס"מ עם ידית תלייה. BPA-free, 145 גרם, שטיפה קלה.',
    description: 'לוח חיתוך PE BPA-free, 35×25 ס"מ. מתקפל לשניים לאחסון, ידית תלייה לייבוש. קשיח לחיתוך, רך לשמירת חדות הסכין.',
    benefits: [
      'BPA-free — בטוח למגע מזון',
      'מתקפל — נכנס לסיר',
      'ידית תלייה — ייבוש קל',
      'PE רך — שומר חדות הסכין',
    ],
    specs: [
      { label: 'חומר', value: 'PE (BPA-free)' },
      { label: 'ממדים', value: '35×25 ס"מ' },
      { label: 'עובי', value: '3 מ"מ' },
      { label: 'משקל', value: '145 גרם' },
    ],
    faqs: [
      {
        question: 'אפשר לשטוף עם סבון?',
        answer: 'כן — PE עמיד לסבון ומים חמים. לא בתנור מיקרוגל.',
      },
    ],
    seoTitle: 'לוח חיתוך מתקפל PE BPA-free לשטח | CampIL',
    seoDescription: 'לוח חיתוך PE מתקפל 35×25 ס"מ, BPA-free, ידית תלייה. ₪49.',
    tags: ['לוח חיתוך', 'כלי בישול שטח', 'קמפינג'],
    relatedSlugs: ['cook-set-4pc', 'camp-stove-single'],
  },

  /* ── 9. כוסות אמייל ערכת 4 ─────────────────────────────────────── */
  {
    id: 'prod-207',
    name: 'כוסות אמייל שטח 300 מ"ל — ערכת 4',
    slug: 'enamel-cups-set',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 79,
    originalPrice: 109,
    rating: 4.6,
    reviewCount: 201,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-CUP-001',
    image: 'https://picsum.photos/seed/enamel-cups-set/800/600',
    images: [
      'https://picsum.photos/seed/enamel-cups-set/800/600',
      'https://picsum.photos/seed/enamel-cups-set-2/800/600',
      'https://picsum.photos/seed/enamel-cups-set-3/800/600',
    ],
    videoUrl: null,
    shortDescription: 'ערכת 4 כוסות אמייל קלאסיות 300 מ"ל. עמידות לאש, לא מעבירות טעמים.',
    description: 'ארבע כוסות אמייל קלאסיות 300 מ"ל — עמידות לחום ולאש ישירה. ציפוי אמייל כפול על בסיס פלדה. לקפה, תה, שוקולד חם ומרק.',
    benefits: [
      'עמידות לאש — חמות כוס ישירות על פח',
      'אמייל כפול — לא מעביר טעמים',
      'ידית נוחה גם לשתייה חמה',
      'ערכת 4 — לכל הקבוצה',
    ],
    specs: [
      { label: 'נפח', value: '300 מ"ל לכוס' },
      { label: 'חומר', value: 'פלדה + אמייל כפול' },
      { label: 'משקל', value: '110 גרם לכוס' },
      { label: 'כמות', value: '4 כוסות' },
    ],
    faqs: [
      {
        question: 'עמידות למדיח?',
        answer: 'לא מומלץ — שטיפה ידנית שומרת את הציפוי.',
      },
    ],
    seoTitle: 'כוסות אמייל שטח 300 מ"ל ערכת 4 | CampIL',
    seoDescription: 'ערכת 4 כוסות אמייל 300 מ"ל. עמידות לאש, לא מחלידות. ₪79.',
    tags: ['כוסות אמייל', 'כלי שתייה שטח', 'קמפינג'],
    relatedSlugs: ['french-press-350', 'espresso-nayad'],
  },

  /* ── 10. גריל שולחני נייד ──────────────────────────────────────── */
  {
    id: 'prod-208',
    name: 'גריל שולחני נייד נירוסטה BBQ 40 ס"מ',
    slug: 'tabletop-grill',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 199,
    originalPrice: 269,
    rating: 4.7,
    reviewCount: 63,
    badge: 'sale',
    inStock: true,
    sku: 'CAMP-GRL-001',
    image: 'https://picsum.photos/seed/tabletop-grill/800/600',
    images: [
      'https://picsum.photos/seed/tabletop-grill/800/600',
      'https://picsum.photos/seed/tabletop-grill-2/800/600',
      'https://picsum.photos/seed/tabletop-grill-3/800/600',
    ],
    videoUrl: null,
    shortDescription: 'גריל שולחני נירוסטה 40×25 ס"מ. לאש ופחמים. רגליות מתכווננות, מגש לטפטוף, מתקפל שטוח.',
    description: 'גריל שולחני נירוסטה 304 בגודל 40×25 ס"מ, שבכה כפולה, מגש טפטוף ורגליות מתכווננות. עמיד לטמפרטורות גבוהות, מתקפל שטוח לאחסון.',
    benefits: [
      'נירוסטה 304 — לא מחליד',
      'שבכה כפולה — חום אחיד',
      'מגש טפטוף — שולחן נשאר נקי',
      'מתקפל שטוח',
    ],
    specs: [
      { label: 'חומר', value: 'נירוסטה 304' },
      { label: 'ממדי שבכה', value: '40×25 ס"מ' },
      { label: 'גובה', value: '12-18 ס"מ (מתכוונן)' },
      { label: 'משקל', value: '1.4 ק"ג' },
    ],
    faqs: [
      {
        question: 'כמה זמן להחמין פחמים?',
        answer: '15-20 דקות. לאש ישירה — מוכן מיד.',
      },
    ],
    seoTitle: 'גריל שולחני נייד נירוסטה BBQ | 40×25 ס"מ | CampIL',
    seoDescription: 'גריל שולחני נירוסטה 304, 40×25 ס"מ, מגש טפטוף, רגליות מתכווננות. ₪199.',
    tags: ['גריל קמפינג', 'BBQ שטח', 'גריל נייד'],
    relatedSlugs: ['cast-iron-24cm', 'camp-stove-single'],
  },

  /* ── 11. כיריים גז 2 להבות ─────────────────────────────────────── */
  {
    id: 'prod-209',
    name: 'כיריים גז שטח 2 להבות + מגן רוח',
    slug: 'camp-stove-double',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 179,
    originalPrice: 239,
    rating: 4.7,
    reviewCount: 88,
    inStock: true,
    sku: 'CAMP-STV-002',
    image: 'https://picsum.photos/seed/camp-stove-double/800/600',
    images: [
      'https://picsum.photos/seed/camp-stove-double/800/600',
      'https://picsum.photos/seed/camp-stove-double-2/800/600',
    ],
    videoUrl: null,
    shortDescription: 'כיריים גז שטח 2 להבות 3200W+2000W עם מגן רוח מובנה. לבישול משפחתי שלם.',
    description: 'כיריים גז 2 להבות: ראשית 3200W, קטנה 2000W. מגן רוח מובנה, כפתורים כפולים. תואם לגלילי 227 ו-450 גרם.',
    benefits: [
      '3200W + 2000W — סיר ומחבת בו-זמנית',
      'מגן רוח מובנה — עובד בשדה פתוח',
      'כפתורים כפולים — שליטה עדינה',
      'תואם לגלילי 227 ו-450 גרם',
    ],
    specs: [
      { label: 'להבה ראשית', value: '3200W' },
      { label: 'להבה שנייה', value: '2000W' },
      { label: 'תאימות', value: 'Butane/Propane EN417' },
      { label: 'ממדים', value: '38×26×8 ס"מ' },
      { label: 'משקל', value: '1.1 ק"ג' },
    ],
    faqs: [
      {
        question: 'אפשר להשתמש מחוץ לרכב?',
        answer: 'כן — על משטח יציב. לא לשימוש בסביבה סגורה.',
      },
    ],
    seoTitle: 'כיריים גז שטח 2 להבות 3200W | מגן רוח | CampIL',
    seoDescription: 'כיריים גז שטח 2 להבות 3200W+2000W, מגן רוח. ₪179.',
    tags: ['כיריים שטח', 'גז קמפינג', 'בישול משפחתי'],
    relatedSlugs: ['cook-set-4pc', 'cast-iron-24cm'],
  },

  /* ── 12. כלי אכילה טיטניום ──────────────────────────────────────── */
  {
    id: 'prod-210',
    name: 'ערכת כלי אכילה טיטניום 3 חלקים',
    slug: 'titanium-cutlery',
    category: 'קפה ובישול שטח',
    categorySlug: 'camp-kitchen',
    price: 99,
    originalPrice: 139,
    rating: 4.6,
    reviewCount: 109,
    badge: 'new',
    inStock: true,
    sku: 'CAMP-CTL-001',
    image: 'https://picsum.photos/seed/titanium-cutlery/800/600',
    images: [
      'https://picsum.photos/seed/titanium-cutlery/800/600',
      'https://picsum.photos/seed/titanium-cutlery-2/800/600',
    ],
    videoUrl: null,
    shortDescription: 'כף, מזלג ומרית טיטניום. 47 גרם לסט. לא מחלידים, לא מעבירים טעמים. כולל קייס.',
    description: 'ערכת כלי אכילה טיטניום 3 חלקים: כף, מזלג ומרית. 47 גרם לסט — קל פי-3 מנירוסטה. לא מחלידים, לא מעבירים טעמים. כולל קייס מיקרופייבר.',
    benefits: [
      'טיטניום — קל פי-3 מנירוסטה',
      '47 גרם לסט — לא מורגש בתיק',
      'לא מחלידים ולא מעבירים טעמים',
      'קייס מיקרופייבר כלול',
    ],
    specs: [
      { label: 'חומר', value: 'טיטניום Grade 2' },
      { label: 'חלקים', value: 'כף + מזלג + מרית' },
      { label: 'משקל', value: '47 גרם' },
      { label: 'אורך', value: '18 ס"מ' },
    ],
    faqs: [
      {
        question: 'עמידים לסירים נון-סטיק?',
        answer: 'כן — קצוות מלוטשים לא פוגעים בציפוי.',
      },
    ],
    seoTitle: 'כלי אכילה טיטניום שטח | 47 גרם | ערכת 3 | CampIL',
    seoDescription: 'כלי אכילה טיטניום 3 חלקים, 47 גרם, קייס כלול. ₪99.',
    tags: ['כלי אכילה טיטניום', 'כלי שטח', 'קמפינג'],
    relatedSlugs: ['cook-set-4pc', 'enamel-cups-set'],
  },
];
