import type { Product } from '../types';

export const lightingPowerProducts: Product[] = [

  /* ── 1. פנס ראש BioLite Range 300 ────────────────────────────────── */
  {
    id: 'prod-401',
    name: 'פנס ראש נטען BioLite Range 300 USB-C',
    slug: 'headlamp-range-300',
    category: 'תאורה וחשמל',
    categorySlug: 'lighting-power',
    price: 249,
    originalPrice: 299,
    rating: 4.7,
    reviewCount: 312,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-LGT-001',
    brand: 'BioLite',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://www.bioliteenergy.com/products/range-300-headlamp',
    image: 'https://www.bioliteenergy.com/cdn/shop/files/Range300_Carousel__Slate.png?v=1756915544',
    images: [
      'https://www.bioliteenergy.com/cdn/shop/files/Range300_Carousel__Slate.png?v=1756915544',
      'https://www.bioliteenergy.com/cdn/shop/files/Range300_Carousel_1.png?v=1757516948',
      'https://www.bioliteenergy.com/cdn/shop/files/Range-300-Carousel-10_7efe7559-979a-4666-bc60-b58c43ec4168.jpg?v=1756864209',
      'https://www.bioliteenergy.com/cdn/shop/files/Range-300-Carousel-9.jpg?v=1756864209',
      'https://www.bioliteenergy.com/cdn/shop/files/Range-300-Carousel-11.jpg?v=1756864209',
    ],
    videoUrl: null,
    shortDescription: 'פנס ראש נטען 300 לומן, 95 גרם. USB-C, עמיד למים IPX4. אינדיקטור אחורי אדום. אידיאלי לטיולים ולמחנאות.',
    description: 'פנס ראש BioLite Range 300 — 300 לומן, 95 גרם. מטעין ב-USB-C תוך שעה וחצי. אינדיקטור LED אדום אחורי לנראות מאחור. רצועה לא-קופצת (NoBounce) לנוחות בריצה ובטיול. IP X4 עמיד למים.',
    benefits: [
      '300 לומן — מספיק לשביל, למחנה ולאוהל',
      '95 גרם — כמעט לא מרגישים על הראש',
      'USB-C — אותו כבל כמו הטלפון',
      'אינדיקטור אחורי אדום — בטיחות בכביש ובשביל',
    ],
    specs: [
      { label: 'עוצמה מקסימלית', value: '300 לומן' },
      { label: 'משקל', value: '95 גרם (עם סוללה)' },
      { label: 'טעינה', value: 'USB-C (90 דק ל-100%)' },
      { label: 'עמידות מים', value: 'IPX4' },
      { label: 'זמן שריפה', value: '3–120 שעות (תלוי מצב)' },
    ],
    faqs: [
      {
        question: 'כמה זמן זה מחזיק על טעינה אחת?',
        answer: 'ב-300 לומן (מקסימום): כ-3 שעות. ב-50 לומן (שביל לילה): כ-20 שעות. במצב שמירה (10 לומן): עד 120 שעות.',
      },
    ],
    seoTitle: 'פנס ראש נטען BioLite Range 300 USB-C | 300 לומן | CampIL',
    seoDescription: 'פנס ראש BioLite Range 300. 300L, 95 גרם, USB-C, IPX4. אינדיקטור אחורי אדום. ₪89.',
    tags: ['פנס ראש', 'BioLite', 'תאורה', 'קמפינג'],
    relatedSlugs: ['headlamp-nitecore-nu25', 'camp-lantern-mini-core'],
  },

  /* ── 2. פנס ראש Nitecore NU25 ──────────────────────────────────── */
  {
    id: 'prod-402',
    name: 'פנס ראש Nitecore NU25 400 לומן USB-C',
    slug: 'headlamp-nitecore-nu25',
    category: 'תאורה וחשמל',
    categorySlug: 'lighting-power',
    price: 119,
    originalPrice: 159,
    rating: 4.8,
    reviewCount: 241,
    badge: 'new',
    inStock: true,
    sku: 'CAMP-LGT-002',
    brand: 'Nitecore',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://www.nitecore.com/product/nu25',
    image: 'https://www.nitecore.com/storage/images/album/20250314/original_img/202503140943266562_m.png',
    images: [
      'https://www.nitecore.com/storage/images/album/20250314/original_img/202503140943266562_m.png',
      'https://www.nitecore.com/storage/images/album/20250314/original_img/202503140943261254_m.png',
      'https://www.nitecore.com/storage/images/album/20250314/original_img/202503140943262151_m.png',
      'https://www.nitecore.com/storage/images/album/20250314/original_img/202503140943274475_m.png',
      'https://www.nitecore.com/storage/images/album/20250314/original_img/202503140943252597_m.png',
    ],
    videoUrl: null,
    shortDescription: 'פנס ראש Nitecore NU25 — שני קרני אור (ראשי + עזר), 400 לומן, IP66, 56 גרם. USB-C מובנה. לשימוש מקצועי בשטח.',
    description: 'Nitecore NU25 MCT — פנס ראש כפול קרן. קרן ראשית לפנס + קרן עזר לתאורה רחבה בסביבה. 400 לומן בסה"כ, IP66 עמיד לאבק ומים, 56 גרם. מופעל ע"י סוללת Li-ion מובנית 650mAh, טעינה ב-USB-C.',
    benefits: [
      'כפול קרן — ראשי לפנס + עזר לתאורת סביבה',
      'IP66 — עמיד לאבק וגשם כבד',
      '56 גרם — קל במיוחד, לא מרגישים',
      'USB-C מובנה — ישיר מהרכיב, בלי כבל נפרד',
    ],
    specs: [
      { label: 'עוצמה מקסימלית', value: '400 לומן (משולב)' },
      { label: 'משקל', value: '56 גרם' },
      { label: 'סוללה', value: 'Li-ion 650mAh מובנית' },
      { label: 'עמידות', value: 'IP66' },
      { label: 'זמן שריפה', value: '1.5–150 שעות' },
    ],
    faqs: [
      {
        question: 'מה ההבדל בין הקרן הראשית לקרן העזר?',
        answer: 'קרן ראשית (מוקדת): זורקת אור רחוק לשביל. קרן עזר (רחבה): מאירה סביב — לקריאה, לאוהל, למחנה.',
      },
    ],
    seoTitle: 'פנס ראש Nitecore NU25 400 לומן IP66 | USB-C | CampIL',
    seoDescription: 'Nitecore NU25 פנס ראש כפול קרן, 400L, 56 גרם, IP66, USB-C מובנה. ₪119.',
    tags: ['פנס ראש', 'Nitecore', 'תאורה', 'שטח'],
    relatedSlugs: ['headlamp-range-300', 'camp-lantern-600'],
  },

  /* ── 3. מנורת מחנה Goal Zero Lighthouse 600 ─────────────────────── */
  {
    id: 'prod-403',
    name: 'מנורת מחנה Goal Zero Lighthouse 600',
    slug: 'camp-lantern-600',
    category: 'תאורה וחשמל',
    categorySlug: 'lighting-power',
    price: 499,
    originalPrice: 619,
    rating: 4.9,
    reviewCount: 428,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-LGT-003',
    brand: 'Goal Zero',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://www.goalzero.com/products/lighthouse-600-lantern',
    image: 'https://goalzero.com/cdn/shop/products/2a80fdd023ddde5f7476536c35575890_300x.jpg?v=1642615105',
    images: [
      'https://goalzero.com/cdn/shop/products/2a80fdd023ddde5f7476536c35575890_300x.jpg?v=1642615105',
    ],
    videoUrl: null,
    shortDescription: 'מנורת מחנה 600 לומן עם רכזת USB לטעינת מכשירים. תאורה ל-360° ל-48 שעות. מנואל גיבוי ידני.',
    description: 'Goal Zero Lighthouse 600 — מנורת הקמפינג המוכרת ביותר. 600 לומן ל-360 מעלות, 48 שעות בעוצמה בינונית, USB-A × 2 לטעינת מכשירים ממנה. מטעינה ב-USB-C (4 שעות) ויש מנואל גיבוי ידני לחירום.',
    benefits: [
      '600 לומן ל-360° — מאיר כל הסביבה',
      'USB-A × 2 — טוענת טלפון, פנס, ועוד ממנה',
      '48 שעות בעוצמה בינונית — שלושה לילות',
      'מנואל ידני — גיבוי ללא חשמל',
    ],
    specs: [
      { label: 'עוצמה', value: '600 / 300 / 150 לומן' },
      { label: 'זמן שריפה', value: '12–48 שעות' },
      { label: 'טעינה', value: 'USB-C (4 שעות)' },
      { label: 'יציאות', value: 'USB-A × 2 (5V 1A)' },
      { label: 'משקל', value: '385 גרם' },
    ],
    faqs: [
      {
        question: 'אפשר לתלות אותה על ידית האוהל?',
        answer: 'כן — יש וו ידית מובנה בראש. מתלייה גם על עץ, על מוט אוהל, ועל כל קרס S.',
      },
    ],
    seoTitle: 'מנורת מחנה Goal Zero Lighthouse 600 | USB Hub | CampIL',
    seoDescription: 'Goal Zero Lighthouse 600. 600 לומן, USB hub, 48 שעות. מנורת קמפינג מהטובות בשוק. ₪149.',
    tags: ['מנורת מחנה', 'Goal Zero', 'תאורה', 'USB'],
    relatedSlugs: ['camp-lantern-mini-core', 'solar-lantern-crush-light'],
  },

  /* ── 4. מנורת מחנה BioLite AlpenGlow 500 ───────────────────────── */
  {
    id: 'prod-404',
    name: 'מנורת מחנה BioLite AlpenGlow 500',
    slug: 'camp-lantern-alpenglow',
    category: 'תאורה וחשמל',
    categorySlug: 'lighting-power',
    price: 399,
    originalPrice: 489,
    rating: 4.8,
    reviewCount: 187,
    badge: 'new',
    inStock: true,
    sku: 'CAMP-LGT-004',
    brand: 'BioLite',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://www.bioliteenergy.com/products/alpenglow-500-lantern',
    image: 'https://www.bioliteenergy.com/cdn/shop/files/alpenglow-500lnb0100-749729.png?v=1711826915',
    images: [
      'https://www.bioliteenergy.com/cdn/shop/files/alpenglow-500lnb0100-749729.png?v=1711826915',
      'https://www.bioliteenergy.com/cdn/shop/files/alpenglow-500lnb0100-105057.jpg?v=1717774203',
      'https://www.bioliteenergy.com/cdn/shop/files/alpenglow-500lnb0100-643557.jpg?v=1717774203',
      'https://www.bioliteenergy.com/cdn/shop/files/alpenglow-500lnb0100-294581.jpg?v=1717774203',
      'https://www.bioliteenergy.com/cdn/shop/files/alpenglow-500lnb0100-620330.jpg?v=1717774203',
    ],
    videoUrl: null,
    shortDescription: 'מנורת מחנה BioLite AlpenGlow 500. 500 לומן, טמפרטורת צבע מתכווננת. USB-A לטעינת מכשירים. 340 גרם.',
    description: 'מנורת AlpenGlow 500 — 500 לומן, טמפרטורת צבע מתכווננת מאור חם ל-אור קריאה קר. USB-A לטעינת טלפון ממנה. מתלייה על ידית ניתנת לקיפול. נטענת ב-USB-C. 340 גרם.',
    benefits: [
      '500 לומן בטמפרטורת צבע לבחירה — חם לאווירה, קר לקריאה',
      'USB-A לטעינת מכשירים ממנה',
      '340 גרם — קומפקטית',
      'ידית קיפול ותליה מובנית',
    ],
    specs: [
      { label: 'עוצמה מקסימלית', value: '500 לומן' },
      { label: 'טמפרטורת צבע', value: '2700K–5600K (מתכוונן)' },
      { label: 'טעינה', value: 'USB-C' },
      { label: 'יציאה', value: 'USB-A × 1' },
      { label: 'משקל', value: '340 גרם' },
    ],
    faqs: [
      {
        question: 'כמה שעות בטמפרטורת אמצע (250 לומן)?',
        answer: 'כ-14 שעות — יומיים לילה בעוצמה נוחה לשיחה במחנה.',
      },
    ],
    seoTitle: 'מנורת מחנה BioLite AlpenGlow 500 | טמפרטורת צבע | CampIL',
    seoDescription: 'BioLite AlpenGlow 500. 500 לומן, טמפ צבע מתכוונן, USB-A, 340 גרם. ₪149.',
    tags: ['מנורת מחנה', 'BioLite', 'AlpenGlow', 'תאורה'],
    relatedSlugs: ['camp-lantern-600', 'camp-lantern-mini-core'],
  },

  /* ── 5. מנורת שמש LuminAID PackLite Max ──────────────────────────── */
  {
    id: 'prod-405',
    name: 'מנורת שמש LuminAID PackLite Max — מתנפחת',
    slug: 'solar-lantern-luminaid-max',
    category: 'תאורה וחשמל',
    categorySlug: 'lighting-power',
    price: 229,
    originalPrice: 279,
    rating: 4.7,
    reviewCount: 253,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-LGT-005',
    brand: 'LuminAID',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://luminaid.com/products/luminary-max',
    image: 'https://luminaid.com/cdn/shop/files/0196-150_Max_QI_product_image_1_1_1200x.jpg?v=1743106322',
    images: [
      'https://luminaid.com/cdn/shop/files/0196-150_Max_QI_product_image_1_1_1200x.jpg?v=1743106322',
      'https://luminaid.com/cdn/shop/products/50646633472_fbc4e1776e_k_1_1200x.jpg?v=1743106322',
      'https://luminaid.com/cdn/shop/products/PLTNRProductImage_sizerelative_withphone_lightgraybackground_2_1_1000x.jpg?v=1743106320',
    ],
    videoUrl: null,
    shortDescription: 'מנורת שמש מתנפחת LuminAID PackLite Max. 300 לומן, נטענת בשמש (7 שעות) או USB. 75 שעות בעוצמה נמוכה. מתקפלת שטוחה.',
    description: 'LuminAID PackLite Max — 300 לומן, נטענת בשמש 7 שעות או ב-USB-micro תוך שעה. 75 שעות בעוצמה נמוכה. מתנפחת לכדור — מאירה לכל הכיוונים. עמידה למים, נשתלת על תרמיל.',
    benefits: [
      'נטענת בשמש — ללא חשמל, גם בשטח',
      '300 לומן — מאיר כל האוהל',
      '75 שעות בנמוכה — שבוע של לילות',
      'מתקפלת שטוחה לגודל ארנק',
    ],
    specs: [
      { label: 'עוצמה מקסימלית', value: '300 לומן' },
      { label: 'זמן שריפה', value: '4–75 שעות' },
      { label: 'טעינה', value: 'שמש (7 שעות) / USB-C (1 שעה)' },
      { label: 'עמידות מים', value: 'IP67' },
      { label: 'משקל', value: '112 גרם (מקופלת)' },
    ],
    faqs: [
      {
        question: 'עובדת בשמש ישראלית?',
        answer: 'כן — הפאנל הסולארי מותאם לקרינה ישירה. בקיץ טוענת ב-6–7 שעות; בחורף אולי 9–10 שעות.',
      },
    ],
    seoTitle: 'מנורת שמש LuminAID PackLite Max | מתנפחת | IP67 | CampIL',
    seoDescription: 'LuminAID PackLite Max 300 לומן, נטענת שמש, IP67, 75 שעות. מתקפלת שטוחה. ₪79.',
    tags: ['מנורת שמש', 'LuminAID', 'מתנפחת', 'סולארי'],
    relatedSlugs: ['solar-lantern-crush-light', 'solar-panel-40w', 'solar-lantern-survivor'],
  },

  /* ── 6. מנורת כיס Goal Zero Crush Light ─────────────────────────── */
  {
    id: 'prod-406',
    name: 'מנורת כיס סולארית Goal Zero Crush Light',
    slug: 'solar-lantern-crush-light',
    category: 'תאורה וחשמל',
    categorySlug: 'lighting-power',
    price: 49,
    originalPrice: 69,
    rating: 4.6,
    reviewCount: 334,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-LGT-006',
    brand: 'Goal Zero',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://www.goalzero.com/products/crush-light',
    image: 'https://goalzero.com/cdn/shop/products/fd8d33dc55c4ba235c6f06df031dbc51_300x.jpg?v=1642613015',
    images: [
      'https://goalzero.com/cdn/shop/products/fd8d33dc55c4ba235c6f06df031dbc51_300x.jpg?v=1642613015',
    ],
    videoUrl: null,
    shortDescription: 'מנורת כיס סולארית Goal Zero Crush Light. 60 לומן, מתקפלת לפחות מ-1 ס"מ, טוענת בשמש. ל-35 שעות בנמוכה.',
    description: 'Goal Zero Crush Light — מנורת כיס שמתקפלת לפחות מ-1 ס"מ ושוקלת 35 גרם. 60 לומן, פאנל סולארי מובנה, 35 שעות ריצה בנמוכה. מצב נר LED + מצב SOS. עמידה למים. נכנסת לכיס ולארנק.',
    benefits: [
      'מתקפלת לפחות מ-1 ס"מ — כמו כרטיס אשראי בעובי',
      'פאנל סולארי מובנה — ללא כבלים',
      '35 שעות ריצה — לכמה לילות',
      'מצב נר LED וSOS מובנים',
    ],
    specs: [
      { label: 'עוצמה', value: '60 לומן (גבוה) / 30 (נמוך)' },
      { label: 'זמן שריפה', value: '14–35 שעות' },
      { label: 'טעינה', value: 'שמש מובנית' },
      { label: 'משקל', value: '35 גרם' },
      { label: 'עובי מקופל', value: 'פחות מ-1 ס"מ' },
    ],
    faqs: [
      {
        question: 'אפשר להוסיף אותה על הצד של תרמיל?',
        answer: 'כן — יש לולאה ניתנת לתליה. הצמדת אותה לתרמיל בשביל לטעון בזמן ההליכה.',
      },
    ],
    seoTitle: 'מנורת כיס סולארית Goal Zero Crush Light | 60 לומן | CampIL',
    seoDescription: 'Goal Zero Crush Light. 60 לומן, מתקפלת שטוחה, שמש מובנית, 35 שעות. ₪49.',
    tags: ['מנורת כיס', 'Goal Zero', 'סולארי', 'קמפינג'],
    relatedSlugs: ['solar-lantern-luminaid-max', 'solar-panel-40w'],
  },

  /* ── 7. פאנל סולארי מתקפל SunJack 40W ───────────────────────────── */
  {
    id: 'prod-407',
    name: 'פאנל סולארי מתקפל SunJack 40W USB-C',
    slug: 'solar-panel-40w',
    category: 'תאורה וחשמל',
    categorySlug: 'lighting-power',
    price: 499,
    originalPrice: 619,
    rating: 4.8,
    reviewCount: 178,
    badge: 'new',
    inStock: true,
    sku: 'CAMP-LGT-007',
    brand: 'SunJack',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://sunjack.com/products/40-watt-solar-panel',
    image: 'https://sunjack.com/cdn/shop/files/40WMain.png?v=1763060309',
    images: [
      'https://sunjack.com/cdn/shop/files/40WMain.png?v=1763060309',
      'https://sunjack.com/cdn/shop/files/40WGraphic4.jpg?v=1721244455',
      'https://sunjack.com/cdn/shop/files/Graphic3_60cd25a1-dae5-4cde-8e07-21254db42f2b.jpg?v=1721764392',
      'https://sunjack.com/cdn/shop/files/40WGraphic3.jpg?v=1721244455',
    ],
    videoUrl: null,
    shortDescription: 'פאנל סולארי מתקפל SunJack 40W. תאים ETFE, יציאות USB-C QC 3.0 + USB-A. רגליים מתקפלות, 720 גרם.',
    description: 'SunJack 40W — פאנל סולארי מתקפל ל-4 חלקות, תאים ETFE בעמידות UV גבוהה. יציאות USB-C PD 18W + USB-A QC 3.0. יעילות 23.5%. רגלי בד רכות לכיוון אל השמש. 720 גרם.',
    benefits: [
      '40W — מספיק לטעינת פאוורבנק וטלפון בו-זמנית',
      'ETFE — עמיד לשמש ישראלית (UV, חום, גשם)',
      'QC 3.0 + USB-C PD — טעינה מהירה',
      'קל 720 גרם — ניתן לנשיאה ברגל',
    ],
    specs: [
      { label: 'הספק', value: '40W' },
      { label: 'יעילות', value: '23.5%' },
      { label: 'יציאות', value: 'USB-C PD 18W + USB-A QC 3.0' },
      { label: 'חומר תאים', value: 'ETFE (עמיד לUV)' },
      { label: 'משקל', value: '720 גרם' },
    ],
    faqs: [
      {
        question: 'כמה זמן לטעון פאוורבנק 10000mAh?',
        answer: 'בשמש ישירה — כ-2.5–3.5 שעות. בצל חלקי — 5–7 שעות.',
      },
    ],
    seoTitle: 'פאנל סולארי מתקפל SunJack 40W USB-C QC3.0 | CampIL',
    seoDescription: 'SunJack 40W. ETFE, USB-C PD, QC 3.0, 720 גרם. פאנל סולארי לקמפינג. ₪149.',
    tags: ['פאנל סולארי', 'SunJack', 'טעינה', 'שטח'],
    relatedSlugs: ['solar-panel-nomad-10', 'power-bank-venture-35', 'power-station-river-2'],
  },

  /* ── 8. פאוורבנק Goal Zero Venture 35 ────────────────────────────── */
  {
    id: 'prod-408',
    name: 'פאוורבנק עמיד Goal Zero Venture 35 — 9600mAh IP67',
    slug: 'power-bank-venture-35',
    category: 'תאורה וחשמל',
    categorySlug: 'lighting-power',
    price: 349,
    originalPrice: 429,
    rating: 4.8,
    reviewCount: 289,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-LGT-008',
    brand: 'Goal Zero',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://www.goalzero.com/products/venture-35',
    image: 'https://goalzero.com/cdn/shop/products/ddb19c22d100c153382c5eea64c8fb1d_1_300x.jpg?v=1621591406',
    images: [
      'https://goalzero.com/cdn/shop/products/ddb19c22d100c153382c5eea64c8fb1d_1_300x.jpg?v=1621591406',
    ],
    videoUrl: null,
    shortDescription: 'פאוורבנק Goal Zero Venture 35 — 9600mAh, IP67 עמיד לאבק ומים. USB-C PD 18W. פנס LED מובנה 50 לומן.',
    description: 'Goal Zero Venture 35 — פאוורבנק שנבנה לשטח. IP67: מחזיק שקיעה במים עד 1 מ׳. 9600mAh, USB-C PD 18W כניסה ויציאה. פנס LED מובנה 50 לומן לחירום. גומי מגן על הפורטים.',
    benefits: [
      'IP67 — שורד שקיעה במים ועמיד לאבק',
      '9600mAh — טעינות מלאות × 2–3 לטלפון',
      'USB-C PD 18W — טוען מהר גם כניסה גם יציאה',
      'פנס 50 לומן מובנה — לחירום',
    ],
    specs: [
      { label: 'קיבולת', value: '9600mAh / 34.6Wh' },
      { label: 'טעינה', value: 'USB-C PD 18W (3 שעות)' },
      { label: 'יציאה', value: 'USB-C 18W + USB-A 5W' },
      { label: 'עמידות', value: 'IP67 (מים 1 מ׳ / 30 דק)' },
      { label: 'פנס', value: '50 לומן מובנה' },
    ],
    faqs: [
      {
        question: 'כמה טעינות נותן לסמארטפון רגיל?',
        answer: 'כ-2–3 טעינות מלאות לטלפון עם סוללה 3500mAh. בפועל תלוי בגיל הסוללה ובצריכה.',
      },
    ],
    seoTitle: 'פאוורבנק Goal Zero Venture 35 9600mAh IP67 | CampIL',
    seoDescription: 'Goal Zero Venture 35. 9600mAh, IP67, USB-C 18W, פנס מובנה. ₪99.',
    tags: ['פאוורבנק', 'Goal Zero', 'IP67', 'שטח'],
    relatedSlugs: ['power-station-river-2', 'solar-panel-40w', 'solar-panel-nomad-10'],
  },

  /* ── 9. תחנת כוח EcoFlow River 2 ─────────────────────────────────── */
  {
    id: 'prod-409',
    name: 'תחנת כוח ניידת EcoFlow River 2 — 256Wh',
    slug: 'power-station-river-2',
    category: 'תאורה וחשמל',
    categorySlug: 'lighting-power',
    price: 999,
    originalPrice: 1249,
    rating: 4.9,
    reviewCount: 134,
    badge: 'new',
    inStock: true,
    sku: 'CAMP-LGT-009',
    brand: 'EcoFlow',
    deliveryTime: '7–10 ימי עסקים',
    sourceUrl: 'https://www.ecoflow.com/products/river2-portable-power-station',
    image: 'https://us.ecoflow.com/cdn/shop/products/ecoflow-us-ecoflow-river-2-portable-power-station-30042778206281.png?v=1667469867',
    images: [
      'https://us.ecoflow.com/cdn/shop/products/ecoflow-us-ecoflow-river-2-portable-power-station-30042778206281.png?v=1667469867',
      'https://us.ecoflow.com/cdn/shop/products/ecoflow-us-ecoflow-river-2-portable-power-station-30042778075209.png?v=1667469871',
      'https://us.ecoflow.com/cdn/shop/products/ecoflow-us-ecoflow-river-2-portable-power-station-30042778140745.png?v=1667469877',
      'https://us.ecoflow.com/cdn/shop/products/ecoflow-us-ecoflow-river-2-portable-power-station-30042778239049.png?v=1667469875',
      'https://us.ecoflow.com/cdn/shop/products/ecoflow-us-ecoflow-river-2-portable-power-station-standalone-30084930863177.jpg?v=1672890077',
    ],
    videoUrl: null,
    shortDescription: 'תחנת כוח EcoFlow River 2 — 256Wh סוללת LFP, 300W AC. טעינה מלאה ב-60 דק. 3.5 ק"ג. לסוף שבוע בשטח ללא חשמל.',
    description: `תחנת כוח EcoFlow River 2 עם 256Wh סוללת LFP (ליתיום-ברזל-פוספט — לא מתחמם, 3,000 מחזורי חיים). 300W AC מלא, 2 × USB-A, 2 × USB-C PD, שקע DC. טעינה מלאה ב-60 דק ממקרה AC. תואמת פאנל סולארי (110W). 3.5 ק"ג.`,
    benefits: [
      'LFP — לא מתלקחת, 3,000 מחזורי חיים (פי-10 מ-Li-Ion)',
      '300W AC — מריצה נייח, מקרר מיני, מנחם שיא',
      'טעינה ב-60 דק — מהר כמו טלפון',
      '3.5 ק"ג — ניתן לנשיאה ביד אחת',
    ],
    specs: [
      { label: 'קיבולת', value: '256Wh' },
      { label: 'סוג סוללה', value: 'LiFePO4 (LFP)' },
      { label: 'יציאת AC', value: '300W (surge 600W)' },
      { label: 'טעינה AC', value: '60 דק מ-0 ל-100%' },
      { label: 'משקל', value: '3.5 ק"ג' },
    ],
    faqs: [
      {
        question: 'כמה זמן זה מריץ מניחה שיא 50W?',
        answer: 'כ-4.5 שעות. ברמה 25W — כ-9 שעות. תלוי בצריכה הכוללת של כל המכשירים.',
      },
    ],
    seoTitle: 'תחנת כוח EcoFlow River 2 256Wh LFP | 300W | CampIL',
    seoDescription: 'EcoFlow River 2. 256Wh LFP, 300W AC, טעינה 60 דק, 3.5 ק"ג. ₪499.',
    tags: ['תחנת כוח', 'EcoFlow', 'LFP', 'אנרגיה סולארית'],
    relatedSlugs: ['solar-panel-40w', 'power-bank-venture-35'],
  },

  /* ── 10. מנורת מחנה קטנה Goal Zero Lighthouse Mini Core ─────────── */
  {
    id: 'prod-410',
    name: 'מנורת מחנה קטנה Goal Zero Lighthouse Mini Core',
    slug: 'camp-lantern-mini-core',
    category: 'תאורה וחשמל',
    categorySlug: 'lighting-power',
    price: 299,
    originalPrice: 369,
    rating: 4.7,
    reviewCount: 216,
    inStock: true,
    sku: 'CAMP-LGT-010',
    brand: 'Goal Zero',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://www.goalzero.com/products/lighthouse-mini-core',
    image: 'https://goalzero.com/cdn/shop/products/5788f20d7e9df33ca6b0223947709cd5_300x.jpg?v=1615368977',
    images: [
      'https://goalzero.com/cdn/shop/products/5788f20d7e9df33ca6b0223947709cd5_300x.jpg?v=1615368977',
    ],
    videoUrl: null,
    shortDescription: 'מנורת מחנה קומפקטית 150 לומן, נטענת USB-C. USB-A לטעינת מכשיר. מנואל גיבוי. מאירה ל-50 שעות.',
    description: 'Goal Zero Lighthouse Mini Core — מנורת מחנה קטנה ב-150 לומן, 225 גרם. נטענת ב-USB-C, מוציאה USB-A לטעינת מכשיר ממנה. מנואל גיבוי ידני. מצב אדום SOS. תולה על ידית ניתנת לכיוון.',
    benefits: [
      '150 לומן — מאיר אוהל 4×4 מ׳ בנוחות',
      'USB-A יציאה — טוענת טלפון ממנה',
      '225 גרם — קומפקטית לנסיעות',
      'מנואל גיבוי — גם ללא חשמל לחלוטין',
    ],
    specs: [
      { label: 'עוצמה', value: '150 / 75 / 7 לומן' },
      { label: 'זמן שריפה', value: '6–50 שעות' },
      { label: 'טעינה', value: 'USB-C' },
      { label: 'יציאה', value: 'USB-A 5V 1A' },
      { label: 'משקל', value: '225 גרם' },
    ],
    faqs: [
      {
        question: 'מה ההבדל בינה לבין Lighthouse 600?',
        answer: 'Mini Core: 150 לומן, 225 גרם — לאוהל / זוג. Lighthouse 600: 600 לומן, 385 גרם — לאוהל משפחה / קבוצה.',
      },
    ],
    seoTitle: 'מנורת מחנה Goal Zero Lighthouse Mini Core | 150 לומן | CampIL',
    seoDescription: 'Goal Zero Lighthouse Mini Core. 150 לומן, USB-C, USB-A יציאה, 225 גרם. ₪119.',
    tags: ['מנורת מחנה', 'Goal Zero', 'קומפקטית', 'USB'],
    relatedSlugs: ['camp-lantern-600', 'camp-lantern-alpenglow'],
  },

  /* ── 11. פאנל סולארי כיס Goal Zero Nomad 10 ─────────────────────── */
  {
    id: 'prod-411',
    name: 'פאנל סולארי כיס Goal Zero Nomad 10 — 10W',
    slug: 'solar-panel-nomad-10',
    category: 'תאורה וחשמל',
    categorySlug: 'lighting-power',
    price: 399,
    originalPrice: 499,
    rating: 4.6,
    reviewCount: 143,
    inStock: true,
    sku: 'CAMP-LGT-011',
    brand: 'Goal Zero',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://www.goalzero.com/products/nomad-10',
    image: 'https://goalzero.com/cdn/shop/products/e6b0ebc0796339e8d8839ccfc0e72a79_300x.jpg?v=1617897886',
    images: [
      'https://goalzero.com/cdn/shop/products/e6b0ebc0796339e8d8839ccfc0e72a79_300x.jpg?v=1617897886',
    ],
    videoUrl: null,
    shortDescription: 'פאנל סולארי Goal Zero Nomad 10 — 10W, USB-A. נשתל על גב תרמיל לטעינה בהליכה. 330 גרם, מתקפל לאות.',
    description: 'Goal Zero Nomad 10 — פאנל סולארי 10W קומפקטי, 330 גרם. מתקפל לאות של ספר. USB-A לטעינת טלפון ישירה. נשתל על גב התרמיל ברצועות בד — טוען בזמן ההליכה.',
    benefits: [
      '330 גרם — קל לנשיאה ברגל',
      'נשתל על תרמיל — טוען בזמן ההליכה',
      'USB-A — מתחבר לכל טלפון וכל פאוורבנק',
      'מחבר פנסי Goal Zero — תואם לכל המוצרים',
    ],
    specs: [
      { label: 'הספק', value: '10W' },
      { label: 'יציאה', value: 'USB-A 5V 2.1A' },
      { label: 'משקל', value: '330 גרם' },
      { label: 'ממדים מקופל', value: '24 × 16 × 2 ס"מ' },
      { label: 'תאימות', value: 'Goal Zero Venture / Yeti / כל USB' },
    ],
    faqs: [
      {
        question: 'ישיר לטלפון בלי פאוורבנק?',
        answer: 'כן — אבל עדיף דרך פאוורבנק. ישיר: הטלפון ייטען לאט ועלול לסגור ברגע שהשמש תיחסם. פאוורבנק — חוצץ ושומר על הטעינה.',
      },
    ],
    seoTitle: 'פאנל סולארי Goal Zero Nomad 10 10W USB | CampIL',
    seoDescription: 'Goal Zero Nomad 10. 10W, USB-A, 330 גרם. מתקפל לאות, נשתל על תרמיל. ₪89.',
    tags: ['פאנל סולארי', 'Goal Zero', 'Nomad', 'טיולים'],
    relatedSlugs: ['solar-panel-40w', 'power-bank-venture-35'],
  },

  /* ── 12. מנורת שמש חירום LuminAID Survivor ──────────────────────── */
  {
    id: 'prod-412',
    name: 'מנורת שמש חירום LuminAID Survivor — 3 מצבי צבע',
    slug: 'solar-lantern-survivor',
    category: 'תאורה וחשמל',
    categorySlug: 'lighting-power',
    price: 199,
    originalPrice: 249,
    rating: 4.8,
    reviewCount: 112,
    badge: 'new',
    inStock: true,
    sku: 'CAMP-LGT-012',
    brand: 'LuminAID',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://luminaid.com/products/survivor',
    image: 'https://luminaid.com/cdn/shop/files/SurvivorThumbnail_1024x.jpg?v=1743106276',
    images: [
      'https://luminaid.com/cdn/shop/files/SurvivorThumbnail_1024x.jpg?v=1743106276',
      'https://luminaid.com/cdn/shop/files/3_Color_Modes_1024x.jpg?v=1762543825',
      'https://luminaid.com/cdn/shop/files/Shopify_-_Product_Images_12_1_1024x.jpg?v=1762543801',
    ],
    videoUrl: null,
    shortDescription: 'מנורת שמש מתנפחת LuminAID Survivor. 3 מצבי צבע: לבן בהיר, לבן חם, אדום SOS. נטענת בשמש. לחירום ולמחנאות.',
    description: 'LuminAID Survivor — מנורת שמש מתנפחת ל-3 מצבי צבע: לבן בהיר (עד 75 לומן), לבן חם לאווירה, ואדום SOS להאיתות. נטענת בשמש (7 שעות) או ב-USB. עמידה למים. מתקפלת שטוחה. אידיאלית לחירום, לשטח ולמחנאות.',
    benefits: [
      'אדום SOS מובנה — האיתות בחירום נראה מרחוק',
      'לבן חם לאווירה — לא רק תאורה פונקציונלית',
      'נטענת בשמש — עצמאות אנרגטית בשטח',
      'מתקפלת שטוחה — נכנסת לכיס',
    ],
    specs: [
      { label: 'מצבי צבע', value: 'לבן בהיר / לבן חם / אדום SOS' },
      { label: 'עוצמה מקסימלית', value: '75 לומן (לבן בהיר)' },
      { label: 'טעינה', value: 'שמש (7 שעות) / USB-C (1.5 שעות)' },
      { label: 'עמידות מים', value: 'IP67' },
      { label: 'משקל', value: '90 גרם' },
    ],
    faqs: [
      {
        question: 'כמה רחוק נראה האות האדום בלילה?',
        answer: 'עד כ-100 מ׳ בחושך מוחלט. מספיק לאיתות לצוות חירום בהיקף מחנה.',
      },
    ],
    seoTitle: 'מנורת שמש LuminAID Survivor 3 מצבי צבע | SOS | CampIL',
    seoDescription: 'LuminAID Survivor. 3 מצבי אור, אדום SOS, שמש מובנית, IP67. ₪79.',
    tags: ['מנורת שמש', 'LuminAID', 'חירום', 'SOS', 'מתנפחת'],
    relatedSlugs: ['solar-lantern-luminaid-max', 'solar-lantern-crush-light'],
  },
];
