import type { Product } from '../types';

export const safetyEmergencyProducts: Product[] = [
  {
    id: 'prod-901',
    name: 'ערכת עזרה ראשונה Adventure Medical Kits Ultralight .3',
    slug: 'amk-ultralight-3',
    category: 'ביטחון וחירום',
    categorySlug: 'safety-emergency',
    price: 149,
    rating: 4.8,
    badge: 'bestseller',
    shortDescription: 'ערכת עזרה ראשונה למטייל יחיד — DryFlex אטום, 120 גרם, לטיולי יום ולינה.',
    description:
      'ערכת ה-Ultralight/Watertight .3 של Adventure Medical Kits היא ערכת העזרה הראשונה הקלה ביותר לטייל יחיד. עטופה בשקית DryFlex אטומה לחלוטין, שוקלת 120 גרם ומכילה ציוד לטיפול בחתכים, בשלפוחיות, בכאבי שרירים ובפציעות שטח נפוצות. מאורגנת לפי נושאי פציעה לאיתור מהיר. מק"ט: 0125-0297.',
    benefits: [
      'אטום לחלוטין — שקית DryFlex עמידה למים',
      '120 גרם בלבד — קל לתרמיל',
      'מאורגן לפי נושאי פציעה',
      'כולל הוראות עזרה ראשונה',
      'מתאים לטיול יחיד עד 2 ימים',
    ],
    specs: [
      { label: 'משקל', value: '120 גרם' },
      { label: 'מספר אנשים', value: '1–2 אנשים' },
      { label: 'משך טיול', value: 'עד 2 ימים' },
      { label: 'מק"ט', value: '0125-0297' },
      { label: 'אחסון', value: 'שקית DryFlex אטומה' },
    ],
    faqs: [
      {
        question: 'האם הערכה אטומה לגשם ולהצפה?',
        answer: 'כן — שקית ה-DryFlex אטומה לגשם ולהצפה קצרה. לשקיעה ממושכת מומלצת ערכה ב-Sea to Summit dry bag.',
      },
    ],
    seoTitle: 'Adventure Medical Kits Ultralight .3 — ערכת עזרה ראשונה לטייל יחיד',
    seoDescription:
      'ערכת עזרה ראשונה AMK Ultralight .3 — 120 גרם, אטום, מאורגן לפי פציעה. לרכישה בTrailNest.',
    image:
      'https://adventuremedicalkits.com/cdn/shop/files/191.jpg?v=1764782120',
    images: [
      'https://adventuremedicalkits.com/cdn/shop/files/191.jpg?v=1764782120',
      'https://adventuremedicalkits.com/cdn/shop/files/0125-0297_ultralight_watertight_3_kit_contents.jpg?v=1764782120',
      'https://adventuremedicalkits.com/cdn/shop/files/187.jpg?v=1764782120',
      'https://adventuremedicalkits.com/cdn/shop/files/188.jpg?v=1764782120',
      'https://adventuremedicalkits.com/cdn/shop/files/0125-0297_ultralight_watertight_3_kit_lifestyle2.jpg?v=1764782120',
    ],
    videoUrl: null,
    inStock: true,
    sku: 'AMK-0125-0297',
    brand: 'Adventure Medical Kits',
    deliveryTime: '5–7 ימי עסקים',
    sourceUrl: 'https://adventuremedicalkits.com/products/ultralight-watertight-medical-kit-3',
    tags: ['עזרה ראשונה', 'Adventure Medical Kits', 'AMK', 'שטח', 'בטיחות'],
    relatedSlugs: ['amk-ultralight-7', 'amk-mountain-hiker', 'leatherman-signal'],
  },
  {
    id: 'prod-902',
    name: 'ערכת עזרה ראשונה Adventure Medical Kits Ultralight .7',
    slug: 'amk-ultralight-7',
    category: 'ביטחון וחירום',
    categorySlug: 'safety-emergency',
    price: 199,
    rating: 4.8,
    shortDescription: 'ערכת עזרה ראשונה לזוג טיילים — DryFlex אטום, 167 גרם, 1–4 ימים.',
    description:
      'ערכת ה-Ultralight/Watertight .7 מיועדת לזוג טיילים בטיולים של 1–4 ימים. עטופה בשקית DryFlex אטומה ושוקלת 167 גרם. כוללת ציוד מורחב יותר מה-.3 — טיפול בפצעים עמוקים, שלפוחיות, כוויות, כאבי שרירים, ואלרגיות. מאורגנת בכיסים נפרדים לפי נושאי פציעה. מק"ט: 0125-0291.',
    benefits: [
      'מתאים לזוג עד 4 ימים',
      'אטום לחלוטין — שקית DryFlex',
      '167 גרם — קל ופחוס',
      'ציוד מורחב לפציעות מגוונות',
      'כיסים מאורגנים לפי נושאי פציעה',
    ],
    specs: [
      { label: 'משקל', value: '167 גרם' },
      { label: 'מספר אנשים', value: '1–2 אנשים' },
      { label: 'משך טיול', value: '1–4 ימים' },
      { label: 'מק"ט', value: '0125-0291' },
      { label: 'אחסון', value: 'שקית DryFlex אטומה' },
    ],
    faqs: [
      {
        question: 'מה ההבדל בין .3 ל-.7?',
        answer: 'ה-.7 כוללת ציוד מורחב — יותר חבישות, כדורי כאב, וחומר לטיפול בכוויות — מתאים לטיולים ארוכים יותר.',
      },
    ],
    seoTitle: 'Adventure Medical Kits Ultralight .7 — ערכת עזרה ראשונה לזוג',
    seoDescription:
      'ערכת עזרה ראשונה AMK Ultralight .7 — 167 גרם, אטום, 1–4 ימים. לרכישה בTrailNest.',
    image:
      'https://adventuremedicalkits.com/cdn/shop/files/Shopify_-_Product_Images_19.jpg?v=1764781824',
    images: [
      'https://adventuremedicalkits.com/cdn/shop/files/Shopify_-_Product_Images_19.jpg?v=1764781824',
      'https://adventuremedicalkits.com/cdn/shop/files/0125-0291_ultralight_watertight_7_kit_contents.jpg?v=1764781824',
      'https://adventuremedicalkits.com/cdn/shop/files/0125-0291_ultralight_watertight_7_kit_inside.jpg?v=1764781824',
      'https://adventuremedicalkits.com/cdn/shop/files/Shopify_-_Product_Images_20.jpg?v=1764781824',
      'https://adventuremedicalkits.com/cdn/shop/files/Shopify_-_Product_Images_21.jpg?v=1764781824',
    ],
    videoUrl: null,
    inStock: true,
    sku: 'AMK-0125-0291',
    brand: 'Adventure Medical Kits',
    deliveryTime: '5–7 ימי עסקים',
    sourceUrl: 'https://adventuremedicalkits.com/products/ultralight-watertight-medical-kit-7',
    tags: ['עזרה ראשונה', 'Adventure Medical Kits', 'AMK', 'שטח', 'בטיחות'],
    relatedSlugs: ['amk-ultralight-3', 'amk-mountain-hiker', 'leatherman-signal'],
  },
  {
    id: 'prod-903',
    name: 'ערכת Mountain Series Hiker Adventure Medical Kits',
    slug: 'amk-mountain-hiker',
    category: 'ביטחון וחירום',
    categorySlug: 'safety-emergency',
    price: 299,
    rating: 4.9,
    badge: 'new',
    shortDescription: 'ערכת עזרה ראשונה מקיפה להרים — 1–10 אנשים, 7 ימים, כיסים מאורגנים.',
    description:
      'ערכת Mountain Series Hiker של Adventure Medical Kits מיועדת לקבוצת טיילים בהרים ולטיולים של עד 7 ימים. כוללת ציוד לטיפול בפצעים עמוקים, שברים, כוויות, בעיות עיניים, ותרופות OTC. מגיעה בשקית בד עמידה עם כיסים מאורגנים לפי נושאי פציעה. כוללת מדריך שטח "Backcountry First Aid" של מאמן חירום. מק"ט: 0100-1001.',
    benefits: [
      'מתאים ל-1–10 אנשים עד 7 ימים',
      'כולל מדריך Backcountry First Aid',
      'ציוד מקיף לפציעות הרריות',
      'כיסים מאורגנים לפי נושאי פציעה',
      'כולל תרופות OTC וחומר תחבושת',
    ],
    specs: [
      { label: 'מספר אנשים', value: '1–10 אנשים' },
      { label: 'משך טיול', value: 'עד 7 ימים' },
      { label: 'מק"ט', value: '0100-1001' },
      { label: 'כולל', value: 'מדריך Backcountry First Aid' },
      { label: 'תרופות', value: 'OTC — משחך, אנטיהיסטמין, עוד' },
    ],
    faqs: [
      {
        question: 'האם הערכה מתאימה לגב לבד (solo)?',
        answer: 'כן — ניתן לחצות ל-solo, אך הכמויות מיועדות לקבוצה. לסולו מומלצת ה-.3 הקלה יותר.',
      },
    ],
    seoTitle: 'AMK Mountain Series Hiker — ערכת עזרה ראשונה לקבוצה 7 ימים',
    seoDescription:
      'ערכת עזרה ראשונה AMK Mountain Series Hiker — 1–10 אנשים, 7 ימים. לרכישה בTrailNest.',
    image:
      'https://adventuremedicalkits.com/cdn/shop/files/Mountain_Series_Forest_Kit.jpg?v=1738956082',
    images: [
      'https://adventuremedicalkits.com/cdn/shop/files/Mountain_Series_Forest_Kit.jpg?v=1738956082',
      'https://adventuremedicalkits.com/cdn/shop/files/0100-1001_mountain_hiker_kit_front.jpg?v=1697727271',
      'https://adventuremedicalkits.com/cdn/shop/files/0100-1001_mountain_hiker_kit_opened.jpg?v=1738955893',
      'https://adventuremedicalkits.com/cdn/shop/files/0100-1001_mountain_hiker_kit_contents.jpg?v=1738955893',
      'https://adventuremedicalkits.com/cdn/shop/files/0100-1001_mountain_hiker_kit_lifestyle2.jpg?v=1738955893',
    ],
    videoUrl: null,
    inStock: true,
    sku: 'AMK-0100-1001',
    brand: 'Adventure Medical Kits',
    deliveryTime: '5–7 ימי עסקים',
    sourceUrl: 'https://adventuremedicalkits.com/products/mountain-series-medical-kit-hiker',
    tags: ['עזרה ראשונה', 'Adventure Medical Kits', 'הרים', 'קבוצה', 'בטיחות'],
    relatedSlugs: ['amk-ultralight-3', 'amk-ultralight-7', 'acr-resqlink-400'],
  },
  {
    id: 'prod-904',
    name: 'משואת חירום ACR ResQLink 400 PLB — 406 MHz GPS',
    slug: 'acr-resqlink-400',
    category: 'ביטחון וחירום',
    categorySlug: 'safety-emergency',
    price: 1899,
    rating: 4.9,
    badge: 'bestseller',
    shortDescription: 'משואת חירום אישית ACR ResQLink 400 — 406 MHz + GPS, ללא דמי מנוי, GPS מדויק.',
    description:
      'ה-ResQLink 400 הוא PLB (Personal Locator Beacon) מבית ACR Electronics — משואת חירום אישית המשדרת בתדר 406 MHz לוויין COSPAS-SARSAT, כולל GPS מדויק, ותדר הגעה 121.5 MHz. ללא דמי מנוי חודשיים. אישור FCC ומאושר לשימוש עולמי. סוללה: 7 שנות המתנה, 24 שעות שידור. מק"ט: 2921. עמיד למים: IPX7.',
    benefits: [
      '406 MHz — קליטה לוויינית עולמית',
      'GPS מדויק — קצר זמן חיפוש',
      'ללא דמי מנוי חודשיים',
      'סוללה 7 שנות המתנה / 24 שעות שידור',
      'עמיד למים IPX7 ועף — צף במים',
    ],
    specs: [
      { label: 'תדר', value: '406 MHz + 121.5 MHz' },
      { label: 'GPS', value: 'כן — קצר זמן חיפוש' },
      { label: 'סוללה', value: '7 שנים המתנה / 24 שעות שידור' },
      { label: 'עמידות מים', value: 'IPX7 — צף' },
      { label: 'מק"ט', value: '2921 / PLB-400' },
    ],
    faqs: [
      {
        question: 'האם נדרשת הרשמה?',
        answer: 'כן — יש לרשום ב-NOAA (בארה"ב) או ב-COSPAS-SARSAT הלאומי בישראל לפני השימוש.',
      },
      {
        question: 'האם PLB שונה מ-SPOT/Garmin inReach?',
        answer: 'כן — PLB הוא מכשיר חד-פעמי לחירום בלבד (ללא מסרים ומעקב). SPOT/inReach מאפשרים גם תקשורת שוטפת תמורת מנוי.',
      },
    ],
    seoTitle: 'ACR ResQLink 400 PLB — משואת חירום 406 MHz GPS ללא מנוי',
    seoDescription:
      'משואת חירום ACR ResQLink 400 PLB — 406 MHz, GPS, ללא מנוי, IPX7. לרכישה בTrailNest.',
    image:
      'https://www.acrartex.com/wp-content/uploads/2021/03/PLB-400-Front.png',
    images: [
      'https://www.acrartex.com/wp-content/uploads/2021/03/PLB-400-Front.png',
      'https://www.acrartex.com/wp-content/uploads/2021/03/PLB-400-ANTENNA-DEPLOYED.png',
      'https://www.acrartex.com/wp-content/uploads/2021/03/PLB-400-Left.png',
      'https://www.acrartex.com/wp-content/uploads/2021/04/ACR_-_Product_-_ResQLink_400_-_Right_Side-3.png',
      'https://www.acrartex.com/wp-content/uploads/2021/04/PLB-400_-_Feature_Diagram_2000x2000-3.jpg',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=eSxQpMsIVr8',
    inStock: true,
    sku: 'ACR-2921',
    brand: 'ACR Electronics',
    deliveryTime: '7–10 ימי עסקים',
    sourceUrl: 'https://www.acrartex.com/products/resqlink-400/',
    tags: ['משואת חירום', 'PLB', 'ACR', 'GPS', 'ביטחון שטח'],
    relatedSlugs: ['amk-ultralight-7', 'amk-mountain-hiker', 'leatherman-signal'],
  },
  {
    id: 'prod-905',
    name: 'מולטי-טול חירום Leatherman Signal — 19 כלים + אש + שריקה',
    slug: 'leatherman-signal',
    category: 'ביטחון וחירום',
    categorySlug: 'safety-emergency',
    price: 659,
    originalPrice: 749,
    rating: 4.8,
    badge: 'sale',
    shortDescription: 'מולטי-טול שטח Leatherman Signal — מציתן פרו, שריקת חירום, 19 כלים, ערבות 25 שנה.',
    description:
      'ה-Leatherman Signal הוא מולטי-טול הישרדות הכולל 19 כלים ייחודיים לשטח — ביניהם: מציתן פרו (ferro rod) להצתת אש ללא גפרורים, שריקת חירום נשמעת ממרחק, פטיש, להב משולב, ואינץ׳ מחדד. משקל: 213 גרם. אורך סגור: 11.4 ס"מ. מלוות ערבות Leatherman ל-25 שנה. מק"ט: 833318.',
    benefits: [
      'מציתן פרו — הצתת אש ללא גפרורים',
      'שריקת חירום נשמעת ממרחק',
      '19 כלים — כולל פטיש, להב משולב, אינץ׳ מחדד',
      'ערבות 25 שנה של Leatherman',
      'גוף פלדת 420HC + ידיות אנודייזד',
    ],
    specs: [
      { label: 'משקל', value: '213 גרם' },
      { label: 'אורך סגור', value: '11.4 ס"מ' },
      { label: 'מספר כלים', value: '19' },
      { label: 'מציתן פרו', value: 'Ferro Rod — כלול' },
      { label: 'מק"ט', value: '833318' },
    ],
    faqs: [
      {
        question: 'האם ניתן להחזיר לטיסה?',
        answer: 'לא — מולטי-טול עם להב אסור בקבין. יש לסמן ולשים בכבודה בלבד.',
      },
      {
        question: 'מה ההבדל בין Signal ל-Wave+?',
        answer: 'ה-Signal מכוון לשטח ויישרדות — כולל מציתן פרו, שריקת חירום ואינץ׳ מחדד. ה-Wave+ הוא מולטי-טול כללי יותר.',
      },
    ],
    seoTitle: 'Leatherman Signal — מולטי-טול חירום 19 כלים + אש + שריקה',
    seoDescription:
      'מולטי-טול שטח Leatherman Signal — מציתן פרו, שריקת חירום, 19 כלים, ערבות 25 שנה. לרכישה בTrailNest.',
    image:
      'https://www.leatherman.com/cdn/shop/files/signal_tundrascape_fanned_20260511210824.jpg',
    images: [
      'https://www.leatherman.com/cdn/shop/files/signal_tundrascape_fanned_20260511210824.jpg',
      'https://www.leatherman.com/cdn/shop/files/signal_tundrascape_closed_front_20260511210823.jpg',
      'https://www.leatherman.com/cdn/shop/files/signal_tundrascape_closed_back_20260511210822.jpg',
      'https://www.leatherman.com/cdn/shop/files/signal_tundrascape_beauty_20260511210821.jpg',
      'https://www.leatherman.com/cdn/shop/files/signal_20260402201811_22h7.jpg',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=WwJdQJJPVmU',
    inStock: true,
    sku: 'LM-833318',
    brand: 'Leatherman',
    deliveryTime: '5–7 ימי עסקים',
    sourceUrl: 'https://www.leatherman.com/products/signal',
    tags: ['מולטי-טול', 'Leatherman', 'Signal', 'ישרדות', 'חירום', 'שטח'],
    relatedSlugs: ['amk-ultralight-7', 'amk-mountain-hiker', 'acr-resqlink-400'],
  },

  /* ── 6. AMK Trauma Pak with QuikClot ─────────────────────────────── */
  {
    id: 'prod-906',
    name: 'ערכת עצירת דימום Adventure Medical Kits Trauma Pak עם QuikClot',
    slug: 'amk-trauma-pak-quikclot',
    category: 'ביטחון וחירום',
    categorySlug: 'safety-emergency',
    price: 149,
    originalPrice: 189,
    rating: 4.9,
    reviewCount: 312,
    badge: 'sale',
    inStock: true,
    sku: 'AMK-2064-0294',
    brand: 'Adventure Medical Kits',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://adventuremedicalkits.com/products/trauma-pak-with-quikclot',
    image: 'https://adventuremedicalkits.com/cdn/shop/files/2064-0292-trauma-pak-with-quikclot-front.jpg?v=1697772915',
    images: [
      'https://adventuremedicalkits.com/cdn/shop/files/2064-0292-trauma-pak-with-quikclot-front.jpg?v=1697772915',
      'https://adventuremedicalkits.com/cdn/shop/files/2064-0292-trauma-pak-with-quikclot-contents.jpg?v=1697772915',
    ],
    videoUrl: null,
    shortDescription: 'ערכת עצירת דימום AMK Trauma Pak — QuikClot 25 גרם, חבישת לחץ ישראלית, כפפות, מספריים. לפציעות חמורות בשטח.',
    description: 'Adventure Medical Kits Trauma Pak עם QuikClot Sport — ערכת עצירת דימום חמור. QuikClot 25 גרם (גורם קרישה) + חבישת לחץ ישראלית + גאזות ספוגיות + כפפות לטקס + מספריים EMT. הכל באריזת DryFlex אטומה. לפצעי ירי, דקירות ופציעות ספורט קיצוני.',
    benefits: [
      'QuikClot — עוצר דימום חמור תוך דקות',
      'חבישת לחץ ישראלית — הסטנדרט העולמי',
      'DryFlex אטום — מוכן בכל עת',
      'ערכת חירום מלאה — לא רק חבישה',
    ],
    specs: [
      { label: 'QuikClot', value: '25 גרם' },
      { label: 'חבישה', value: 'Israeli Emergency Bandage 4"' },
      { label: 'משקל', value: '200 גרם' },
      { label: 'אחסון', value: 'DryFlex אטום' },
    ],
    faqs: [
      {
        question: 'QuikClot בטוח לשימוש ביתי?',
        answer: 'כן — QuikClot Sport הוא גרסת הצרכן. נוח לשימוש ללא הכשרה — שמים, לוחצים 3 דקות. מומלץ לעבור הכשרה בסיסית.',
      },
    ],
    seoTitle: 'ערכת עצירת דימום AMK Trauma Pak QuikClot | CampIL',
    seoDescription: 'AMK Trauma Pak QuikClot 25 גרם + חבישה ישראלית. ₪149.',
    tags: ['עזרה ראשונה', 'QuikClot', 'דימום', 'Adventure Medical'],
    relatedSlugs: ['amk-ultralight-3', 'amk-mountain-hiker', 'leatherman-signal'],
  },

  /* ── 7. Garmin inReach Mini 2 ────────────────────────────────────── */
  {
    id: 'prod-907',
    name: 'מכשיר תקשורת לוויין Garmin inReach Mini 2',
    slug: 'garmin-inreach-mini-2',
    category: 'ביטחון וחירום',
    categorySlug: 'safety-emergency',
    price: 1499,
    rating: 4.9,
    reviewCount: 198,
    badge: 'new',
    inStock: true,
    sku: 'GARMIN-010-02602-00',
    brand: 'Garmin',
    deliveryTime: '7–10 ימי עסקים',
    sourceUrl: 'https://www.garmin.com/en-US/p/784374',
    image: 'https://www.pciraceradios.com/cdn/shop/files/pci-race-radios-default-title-garmin-inreach-mini-2-37388344197361.jpg?v=1736203784',
    images: [
      'https://www.pciraceradios.com/cdn/shop/files/pci-race-radios-default-title-garmin-inreach-mini-2-37388344197361.jpg?v=1736203784',
    ],
    videoUrl: null,
    shortDescription: 'מכשיר תקשורת לוויין Garmin inReach Mini 2 — הודעות דו-כיוניות + SOS לוויין + GPS. 100 גרם. לאזורים ללא קליטה.',
    description: 'Garmin inReach Mini 2 — תקשורת לוויין דו-כיוונית ב-100 גרם. שליחת הודעות SMS דרך לוויין Iridium לכל טלפון בעולם — גם ממרחקי נגב, ים המלח וחרמון. SOS לוויין עם מענה 24/7 מ-GEOS. GPS מובנה. סוללה 14 יום.',
    benefits: [
      'הודעות דו-כיוניות בכל מקום — גם בלי קליטה סלולרית',
      'SOS 24/7 — מוקד חירום מועבר למד"א',
      'GPS מובנה — מכשיר ניווט עצמאי',
      '100 גרם — לא מורגש בחגורה',
    ],
    specs: [
      { label: 'רשת לוויין', value: 'Iridium (100% כיסוי עולמי)' },
      { label: 'SOS', value: 'GEOS 24/7 International' },
      { label: 'סוללה', value: '14 יום (מצב עקיבה)' },
      { label: 'משקל', value: '100 גרם' },
      { label: 'עמידות', value: 'IPX7' },
    ],
    faqs: [
      {
        question: 'צריך מינוי חודשי?',
        answer: 'כן — inReach דורש מינוי Garmin (מ-₪39/חודש לתוכנית בסיסית). אפשר מינוי עונתי לחודשי שטח.',
      },
    ],
    seoTitle: 'Garmin inReach Mini 2 | תקשורת לוויין | SOS | CampIL',
    seoDescription: 'Garmin inReach Mini 2. הודעות דו-כיוניות, SOS, GPS, 100 גרם. ₪1,499.',
    tags: ['תקשורת לוויין', 'Garmin', 'inReach', 'SOS', 'חירום'],
    relatedSlugs: ['acr-resqlink-400', 'amk-trauma-pak-quikclot', 'leatherman-signal'],
  },

  /* ── 8. SOL Escape Pro Bivy ──────────────────────────────────────── */
  {
    id: 'prod-908',
    name: 'ביווק חירום SOL Escape Pro Bivy — מחזיר 70% חום',
    slug: 'sol-escape-pro-bivy',
    category: 'ביטחון וחירום',
    categorySlug: 'safety-emergency',
    price: 199,
    rating: 4.7,
    reviewCount: 156,
    inStock: true,
    sku: 'SOL-0140-1224',
    brand: 'SOL',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://surviveoutdoorslonger.com/products/escape-pro-bivy',
    image: 'https://skyviewcamping.com/cdn/shop/products/v34lZssl_1024x1024.jpg?v=1606255342',
    images: [
      'https://skyviewcamping.com/cdn/shop/products/v34lZssl_1024x1024.jpg?v=1606255342',
    ],
    videoUrl: null,
    shortDescription: 'ביווק חירום SOL Escape Pro Bivy — מחזיר 70% חום גוף, נושם (Tyvek), עמיד ל-4 עונות. 198 גרם.',
    description: 'SOL Escape Pro Bivy — ביווק חירום שהוא גם שק שינה לייט. מחזיר 70% חום גוף בזכות ציפוי רדיאנטי. פאנל Tyvek להזעה (breathable). עמיד לרוח ומים. 198 גרם. לחירום, לבריחה עם תרמיל, ולשינה בחוץ בחורף ישראלי.',
    benefits: [
      '70% החזר חום — חלופה אמיתית לשק שינה',
      'Tyvek נושם — לא מתבלל בפנים',
      '198 גרם — פחות מ-200 גרם',
      'עמיד לרוח ומים — 4 עונות',
    ],
    specs: [
      { label: 'משקל', value: '198 גרם' },
      { label: 'החזר חום', value: '70% (רדיאנטי)' },
      { label: 'חומר', value: 'Tyvek + ציפוי רדיאנטי' },
      { label: 'מידות', value: '213 × 76 ס"מ' },
    ],
    faqs: [
      {
        question: 'ב-מה עדיף מ-Emergency Blanket?',
        answer: 'Escape Pro Bivy הוא שק — ידיים ורגליים חמות בתוכו. שמיכה רגילה צריך להחזיק. Bivy: פנוי לידיים, אטום לרוח.',
      },
    ],
    seoTitle: 'ביווק חירום SOL Escape Pro Bivy | 70% חום | 198 גרם | CampIL',
    seoDescription: 'SOL Escape Pro Bivy. 70% החזר חום, Tyvek, 198 גרם. ₪199.',
    tags: ['ביווק חירום', 'SOL', 'שמיכת חירום', 'ישרדות'],
    relatedSlugs: ['amk-ultralight-3', 'amk-trauma-pak-quikclot', 'leatherman-signal'],
  },

  /* ── 9. SOL Emergency Blanket 4-Pack ─────────────────────────────── */
  {
    id: 'prod-909',
    name: 'שמיכות חירום SOL Emergency Blanket — חבילה של 4',
    slug: 'sol-emergency-blanket-4pk',
    category: 'ביטחון וחירום',
    categorySlug: 'safety-emergency',
    price: 79,
    originalPrice: 109,
    rating: 4.6,
    reviewCount: 434,
    badge: 'sale',
    inStock: true,
    sku: 'SOL-0140-1630',
    brand: 'SOL',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://surviveoutdoorslonger.com/products/emergency-blanket-4-pack',
    image: 'https://www.supplycache.com/cdn/shop/files/252-35024.webp?v=1706637872&width=1500',
    images: [
      'https://www.supplycache.com/cdn/shop/files/252-35024.webp?v=1706637872&width=1500',
    ],
    videoUrl: null,
    shortDescription: 'שמיכות חירום SOL — 4 יחידות. מחזירות 90% חום, אות חירום זוהר, 43 גרם לשמיכה. לכל תרמיל ואוהל.',
    description: 'SOL Emergency Blanket — שמיכת חירום אלומיניום קלאסית שמחזירה 90% חום גוף. 43 גרם ליחידה. פס ניראות כתום לאיתות. 4 שמיכות בחבילה — לכל המשפחה/קבוצה. לטיולי יום, לאוהל ולמקרי חירום.',
    benefits: [
      '90% החזר חום — שומרת על גוף חם',
      'פס כתום לאיתות — נראה ממרחק',
      '43 גרם — נכנסת לכיס חגורה',
      '4 יחידות — לכל הקבוצה',
    ],
    specs: [
      { label: 'יחידות', value: '4 שמיכות' },
      { label: 'החזר חום', value: '90%' },
      { label: 'משקל', value: '43 גרם לשמיכה' },
      { label: 'מידות', value: '132 × 213 ס"מ' },
    ],
    faqs: [
      {
        question: 'לשימוש חוזר?',
        answer: 'בפועל — שמיכה אחת שורדת 2–3 שימושים עדינים. לחירום: השתמשו ותחליפו. לא לסתמות שהיא חד-פעמית.',
      },
    ],
    seoTitle: 'שמיכות חירום SOL Emergency Blanket 4 יחידות | CampIL',
    seoDescription: 'SOL Emergency Blanket 4-Pack. 90% חום, 43 גרם, פס כתום. ₪79.',
    tags: ['שמיכת חירום', 'SOL', 'חירום', 'ישרדות'],
    relatedSlugs: ['sol-escape-pro-bivy', 'amk-ultralight-3', 'amk-trauma-pak-quikclot'],
  },

  /* ── 10. AMK Blister Medic ───────────────────────────────────────── */
  {
    id: 'prod-910',
    name: 'ערכת טיפול שלפוחיות Adventure Medical Kits Blister Medic',
    slug: 'amk-blister-medic',
    category: 'ביטחון וחירום',
    categorySlug: 'safety-emergency',
    price: 79,
    rating: 4.7,
    reviewCount: 278,
    inStock: true,
    sku: 'AMK-0155-0700',
    brand: 'Adventure Medical Kits',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://adventuremedicalkits.com/products/blister-medic',
    image: 'https://adventuremedicalkits.com/cdn/shop/files/0155-0667_blister_medic_kit_front.jpg?v=1697704851',
    images: [
      'https://adventuremedicalkits.com/cdn/shop/files/0155-0667_blister_medic_kit_front.jpg?v=1697704851',
    ],
    videoUrl: null,
    shortDescription: 'ערכת טיפול שלפוחיות AMK Blister Medic — Moleskin, SpeedStrips, מחט עקר, גאזה. לכל יום הליכה.',
    description: 'Adventure Medical Kits Blister Medic — ערכת טיפול שלפוחיות מלאה. Moleskin (רפידות הגנה), SpeedStrips, מחט עקרה לניקוב מבוקר, גאזה, אנטיספטיק. הכל בקמה עם רוכסן. לטיולים רגליים, לטרקים ולמרתונים.',
    benefits: [
      'Moleskin — הגנה לפני שמתנפחת',
      'SpeedStrips — פלסטר מגביר חיכוך',
      'מחט עקרה — ניקוב בטוח',
      'קומפקטי — מכנס לכיס חגורה',
    ],
    specs: [
      { label: 'כלולים', value: 'Moleskin + SpeedStrips + מחט עקרה + גאזה' },
      { label: 'משקל', value: '50 גרם' },
      { label: 'אחסון', value: 'קמה עם רוכסן' },
    ],
    faqs: [
      {
        question: 'מתי להשתמש ב-Moleskin?',
        answer: 'כשיש "hot spot" — אזור שמתחיל להתחמם אבל עדיין לא שלפוחית. הדביקו לפני הנפיחה.',
      },
    ],
    seoTitle: 'ערכת שלפוחיות AMK Blister Medic | Moleskin | CampIL',
    seoDescription: 'AMK Blister Medic. Moleskin, SpeedStrips, מחט עקרה, 50 גרם. ₪79.',
    tags: ['שלפוחיות', 'Adventure Medical', 'Blister Medic', 'הליכה'],
    relatedSlugs: ['amk-ultralight-3', 'amk-ultralight-7', 'amk-mountain-hiker'],
  },
];
