import type { Product } from '../types';

export const sleepingComfortProducts: Product[] = [
  {
    id: 'prod-701',
    name: 'מזרן קמפינג Therm-a-Rest NeoAir XLite NXT — R-Value 4.5',
    slug: 'neoair-xlite-nxt',
    category: 'שינה ונוחות',
    categorySlug: 'sleeping-comfort',
    price: 1299,
    originalPrice: 1449,
    rating: 4.9,
    badge: 'bestseller',
    shortDescription: 'המזרן האולטראלייט הכי שקט ומבודד לטיולי תרמיל — R-Value 4.5 ב-354 גרם בלבד.',
    description:
      'ה-NeoAir XLite NXT של Therm-a-Rest הוא אחד ממזרני הקמפינג הקלים ביותר בשוק עם R-Value מרשים של 4.5 — מתאים לכל עונות השנה. שיפור של 83% ברעש לעומת הדגם הקודם הופך אותו לנוח ושקט, ושסתום ה-WingLock מאפשר ניפוח מהיר וריקון חד. משקל: 354 גרם (Regular). מידות: 183 × 51 × 7.5 ס"מ.',
    benefits: [
      'R-Value 4.5 — מבודד לכל עונות השנה',
      'שקט 83% יותר מהדגם הקודם',
      'משקל 354 גרם בלבד (Regular)',
      'עובי 7.5 ס"מ לנוחות מקסימלית',
      'שסתום WingLock לניפוח וריקון מהיר',
    ],
    specs: [
      { label: 'משקל', value: '354 גרם (Regular)' },
      { label: 'R-Value', value: '4.5' },
      { label: 'מידות פרוס', value: '183 × 51 × 7.5 ס"מ' },
      { label: 'חומר', value: '15D / 20D ריפסטופ ניילון' },
      { label: 'שסתום', value: 'WingLock' },
    ],
    faqs: [
      {
        question: 'כמה זמן לוקח לנפח את המזרן?',
        answer: 'כ-10–15 נשיפות בלבד הודות לשסתום WingLock המתקדם.',
      },
      {
        question: 'האם מתאים לשינה צדדית?',
        answer: 'כן — עובי 7.5 ס"מ מספק תמיכה מעולה גם לישני צד.',
      },
    ],
    seoTitle: 'Therm-a-Rest NeoAir XLite NXT — מזרן קמפינג אולטראלייט R-Value 4.5',
    seoDescription:
      'מזרן קמפינג Therm-a-Rest NeoAir XLite NXT — 354 גרם, R-Value 4.5, שסתום WingLock. ניתן לרכוש באתר TrailNest.',
    image:
      'https://cascadedesigns.com/cdn/shop/files/11627_thermarest_neoair_xlite_nxt_solarflare_regular_angle.jpg?v=1724820257',
    images: [
      'https://cascadedesigns.com/cdn/shop/files/11627_thermarest_neoair_xlite_nxt_solarflare_regular_angle.jpg?v=1724820257',
      'https://cascadedesigns.com/cdn/shop/files/11627_thermarest_neoair_xlite_nxt_solarflare_regular_top.jpg?v=1724820256',
      'https://cascadedesigns.com/cdn/shop/files/11627_thermarest_neoair_xlite_nxt_solarflare_regular_ssack.jpg?v=1724820256',
      'https://cascadedesigns.com/cdn/shop/files/11627-thermarest-neoair-xlite-nxt-solarflare-regular-contents.jpg?v=1724820256',
      'https://cascadedesigns.com/cdn/shop/files/11627_2022_TR_Xlite_NXT_rinckenberger_perputual_01_e34a758c-92cd-4a45-b55e-a0a69e37e097.jpg?v=1724820257',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=Uvv_wZLAP3c',
    inStock: true,
    sku: 'TR-14010',
    brand: 'Therm-a-Rest',
    deliveryTime: '5–7 ימי עסקים',
    sourceUrl: 'https://cascadedesigns.com/products/neoair-xlite-nxt-sleeping-pad',
    tags: ['מזרן קמפינג', 'אולטראלייט', 'Therm-a-Rest', 'sleeping pad', 'NeoAir'],
    relatedSlugs: ['z-lite-sol', 'nemo-tensor-all-season', 'sts-spark-down-sleeping-bag'],
  },
  {
    id: 'prod-702',
    name: 'מזרן קצף Therm-a-Rest Z Lite SOL — קומפקטי ועמיד',
    slug: 'z-lite-sol',
    category: 'שינה ונוחות',
    categorySlug: 'sleeping-comfort',
    price: 299,
    rating: 4.7,
    badge: 'bestseller',
    shortDescription: 'מזרן קצף מתקפל אקורדיון מבית Therm-a-Rest — עמיד, ללא ניפוח, צד כסף לחימום.',
    description:
      'ה-Z Lite SOL הוא מזרן הקצף הקלאסי של Therm-a-Rest — קל, עמיד ותמיד מוכן לשימוש ללא ניפוח. צד כסף מחזיר קרינת גוף לחימום נוסף. מתקפל אקורדיון לחיבור מהיר לתרמיל. R-Value: 2.0. משקל: 410 גרם (Regular). מתאים לקמפינג קיצי ולניסיוני כשכבת בידוד נוספת מתחת למזרן מתנפח.',
    benefits: [
      'ללא ניפוח — מוכן לשימוש מיידי',
      'צד כסף מחזיר קרינה לחימום נוסף',
      'עמיד לנזק ואינו ניקב',
      'ניתן לחיבור מחוץ לתרמיל',
      'R-Value 2.0 — מתאים לעונות המעבר',
    ],
    specs: [
      { label: 'משקל', value: '410 גרם (Regular)' },
      { label: 'R-Value', value: '2.0' },
      { label: 'מידות פרוס', value: '183 × 51 ס"מ' },
      { label: 'עובי', value: '2 ס"מ' },
      { label: 'חומר', value: 'קצף Ether Foam מחזיר' },
    ],
    faqs: [
      {
        question: 'האם ניתן לשלב עם מזרן מתנפח?',
        answer: 'כן — שילוב מתחת למזרן מתנפח דק מגדיל את ה-R-Value הכולל משמעותית.',
      },
    ],
    seoTitle: 'Therm-a-Rest Z Lite SOL — מזרן קצף לקמפינג ותרמיל',
    seoDescription:
      'מזרן קצף Therm-a-Rest Z Lite SOL — 410 גרם, R-Value 2.0, ללא ניפוח. מתאים לקמפינג עם תרמיל בישראל.',
    image:
      'https://cascadedesigns.com/cdn/shop/files/13267_thermarest_zlite_blue_regular_top.jpg?v=1760733250',
    images: [
      'https://cascadedesigns.com/cdn/shop/files/13267_thermarest_zlite_blue_regular_top.jpg?v=1760733250',
      'https://cascadedesigns.com/cdn/shop/files/06670_tr_zlite_sol_limonsilver_regular_silver_angle_fold.jpg?v=1728427656',
      'https://cascadedesigns.com/cdn/shop/files/06679_tr_zlitesol_limon_reg_folded.jpg?v=1728427641',
      'https://cascadedesigns.com/cdn/shop/files/tr_lifestyle_zlitesol_2.jpg?v=1760733250',
      'https://cascadedesigns.com/cdn/shop/files/tr_lifestyle_zlitesol_5.jpg?v=1760733250',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=tAz4uxLXPqM',
    inStock: true,
    sku: 'TR-06670',
    brand: 'Therm-a-Rest',
    deliveryTime: '5–7 ימי עסקים',
    sourceUrl: 'https://cascadedesigns.com/products/z-lite-sol-sleeping-pad',
    tags: ['מזרן קצף', 'Therm-a-Rest', 'Z Lite', 'sleeping pad'],
    relatedSlugs: ['neoair-xlite-nxt', 'nemo-tensor-all-season', 'sts-aeros-pillow'],
  },
  {
    id: 'prod-703',
    name: 'מזרן קמפינג NEMO Tensor All-Season מבודד — R-Value 4.8',
    slug: 'nemo-tensor-all-season',
    category: 'שינה ונוחות',
    categorySlug: 'sleeping-comfort',
    price: 1199,
    rating: 4.8,
    badge: 'new',
    shortDescription: 'מזרן מתנפח NEMO Tensor All-Season — כרית Vortex, R-Value 4.8, עיצוב מומי.',
    description:
      'ה-NEMO Tensor All-Season מציע איזון מושלם בין חום לנוחות עם R-Value 4.8 ומשקל של 510 גרם (Regular Mummy). כרית ה-Vortex הייחודית מספקת תמיכה מרכזית ומפחיתה לחץ על נקודות בולטות. הצורה המומי המרחיבה ברגליים מאפשרת נוחות לכל סגנון שינה. שסתום Laylow מאפשר ניפוח מהיר. כולל שק Divvy ומשאבת Vortex.',
    benefits: [
      'R-Value 4.8 — מתאים לכל עונות השנה',
      'כרית Vortex מספקת תמיכה מרכזית',
      'צורת מומי מרחיבה ברגליים לחופש תנועה',
      'שסתום Laylow לניפוח וריקון מהיר',
      'כולל שק Divvy ומשאבת Vortex',
    ],
    specs: [
      { label: 'משקל', value: '510 גרם (Regular Mummy)' },
      { label: 'R-Value', value: '4.8' },
      { label: 'מידות פרוס', value: '183 × 53 ס"מ' },
      { label: 'עובי', value: '8.9 ס"מ' },
      { label: 'SKU', value: '811666035127' },
    ],
    faqs: [
      {
        question: 'מה ההבדל בין Tensor ל-Tensor All-Season?',
        answer: 'ה-All-Season כולל שכבת בידוד נוספת ו-R-Value גבוה יותר המתאים לשימוש בחורף.',
      },
    ],
    seoTitle: 'NEMO Tensor All-Season — מזרן קמפינג מבודד R-Value 4.8',
    seoDescription:
      'מזרן קמפינג NEMO Tensor All-Season — R-Value 4.8, 510 גרם, כרית Vortex. לרכישה בTrailNest.',
    image:
      'https://www.nemoequipment.com/cdn/shop/files/Tensor-AllSeason-RegularMummy_811666035127_01-Main.jpg?v=1772661323',
    images: [
      'https://www.nemoequipment.com/cdn/shop/files/Tensor-AllSeason-RegularMummy_811666035127_01-Main.jpg?v=1772661323',
      'https://www.nemoequipment.com/cdn/shop/files/Tensor-AllSeason-RegularMummy_811666035127_02-34.jpg?v=1772661323',
      'https://www.nemoequipment.com/cdn/shop/files/Tensor-AllSeason-RegularMummy_811666035127_03-Side.jpg?v=1772661323',
      'https://www.nemoequipment.com/cdn/shop/files/Tensor-AllSeason-RegularMummy_811666035127_04-Packed.jpg?v=1772661324',
      'https://www.nemoequipment.com/cdn/shop/files/Tensor-AllSeason-RegMummy_811666035127_Annotated-KeyFeatures.jpg?v=1772661323',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=k6gQFJBIP3s',
    inStock: true,
    sku: 'NEMO-811666035127',
    brand: 'NEMO',
    deliveryTime: '5–7 ימי עסקים',
    sourceUrl: 'https://www.nemoequipment.com/products/tensor-all-season-insulated-sleeping-pad',
    tags: ['מזרן קמפינג', 'NEMO', 'Tensor', 'אולטראלייט', 'sleeping pad'],
    relatedSlugs: ['neoair-xlite-nxt', 'z-lite-sol', 'sts-spark-down-sleeping-bag'],
  },
  {
    id: 'prod-704',
    name: 'שק שינה Sea to Summit Spark Down 7°C — אולטראלייט 275 גרם',
    slug: 'sts-spark-down-sleeping-bag',
    category: 'שינה ונוחות',
    categorySlug: 'sleeping-comfort',
    price: 1349,
    originalPrice: 1549,
    rating: 4.8,
    badge: 'sale',
    shortDescription: 'שק שינה ברווז Sea to Summit Spark Down 7°C — 275 גרם, 750FP, נוחות ±13°C.',
    description:
      'שק השינה Spark Down 7°C של Sea to Summit הוא בין שקי השינה הקלים ביותר בשוק. מולא ב-750FP ברווז אירופי מוסמך RDS ושוקל רק 275 גרם (Regular). חזיז 2D נוח עוטף את הרגליים. טמפרטורת נוחות: 13°C, גבול תחתון: 7°C, קיצוני: -8°C. פתח טמפרטורה מאפשר ויסות חום. מגיע בשק אחסון רשת.',
    benefits: [
      '275 גרם בלבד — אחד מהקלים בשוק',
      '750FP ברווז RDS מוסמך',
      'טמפרטורת גבול 7°C / נוחות 13°C',
      'חזיז 2D לנוחות ברגליים',
      'פתח טמפרטורה לויסות חום',
    ],
    specs: [
      { label: 'משקל', value: '275 גרם (Regular)' },
      { label: 'מילוי', value: '750FP ברווז אירופי RDS' },
      { label: 'טמפרטורת נוחות', value: '+13°C' },
      { label: 'גבול תחתון', value: '+7°C' },
      { label: 'SKU', value: 'ASL041072-050101' },
    ],
    faqs: [
      {
        question: 'האם הדאון רטוב מאבד בידוד?',
        answer: 'כן — מומלץ להשתמש עם כיסוי חיצוני לגשם ולאחסן יבש בכל עת.',
      },
      {
        question: 'מה ההבדל בין Spark ל-Spark Pro?',
        answer: 'ה-Spark Pro משתמש ב-850FP ברווז ועמיד יותר ללחות — מתאים לטיולים קשים.',
      },
    ],
    seoTitle: 'Sea to Summit Spark Down 7°C — שק שינה אולטראלייט 275 גרם',
    seoDescription:
      'שק שינה Sea to Summit Spark Down 7°C — 275 גרם, 750FP ברווז, גבול +7°C. לרכישה בTrailNest.',
    image:
      'https://seatosummit.com/cdn/shop/files/SparkDownSleepingBag7C-45FRegular_ASL041072-050101_MODEL_4_WBG.jpg?v=1757432541',
    images: [
      'https://seatosummit.com/cdn/shop/files/SparkDownSleepingBag7C-45FRegular_ASL041072-050101_MODEL_4_WBG.jpg?v=1757432541',
      'https://seatosummit.com/cdn/shop/files/Spark7CReg_WHITE.jpg?v=1719262610',
      'https://seatosummit.com/cdn/shop/files/SparkDownSleepingBag7C-45FRegular_ASL041072-050101_USP_1_WBG.jpg?v=1757432541',
      'https://seatosummit.com/cdn/shop/files/SparkDownSleepingBag7C-45FRegular_ASL041072-050101_USP_3_WBG.jpg?v=1757432541',
      'https://seatosummit.com/cdn/shop/files/SleepingBagZipPositions_Unisex45_F-7_C.jpg?v=1757432541',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=K5vHmfkn6DU',
    inStock: true,
    sku: 'STS-ASL041072',
    brand: 'Sea to Summit',
    deliveryTime: '5–7 ימי עסקים',
    sourceUrl: 'https://seatosummit.com/products/spark-down-sleeping-bag',
    tags: ['שק שינה', 'ברווז', 'Sea to Summit', 'Spark', 'אולטראלייט'],
    relatedSlugs: ['neoair-xlite-nxt', 'sts-aeros-pillow', 'nemo-tensor-all-season'],
  },
  {
    id: 'prod-705',
    name: 'כרית קמפינג Sea to Summit Aeros Ultralight — 57 גרם',
    slug: 'sts-aeros-pillow',
    category: 'שינה ונוחות',
    categorySlug: 'sleeping-comfort',
    price: 199,
    rating: 4.7,
    shortDescription: 'כרית אוויר מתנפחת Aeros Ultralight של Sea to Summit — 57 גרם, שסתום XPRESS.',
    description:
      'הכרית Aeros Ultralight של Sea to Summit היא אחת הכריות הקלות והנוחות ביותר בשוק — 57 גרם בלבד. שסתום XPRESS mini מאפשר ניפוח וריקון מהיר, עם כוונון עובי עד 11 ס"מ. ציפוי טקסטיל מוצלב מונע החלקה ונוח ישירות על העור. מגיע בשק אחסון עם שרוך לחיבור לתרמיל.',
    benefits: [
      '57 גרם בלבד — אחת מהקלות בשוק',
      'שסתום XPRESS mini לניפוח מהיר',
      'כוונון עובי עד 11 ס"מ',
      'ציפוי טקסטיל מוצלב — אינו מחליק',
      'נוח לשינה צדדית וגבית כאחד',
    ],
    specs: [
      { label: 'משקל', value: '57 גרם (Regular)' },
      { label: 'עובי מרבי', value: '11 ס"מ' },
      { label: 'מידות', value: '38 × 24 ס"מ (Regular)' },
      { label: 'שסתום', value: 'XPRESS mini' },
      { label: 'SKU', value: 'STS-045301' },
    ],
    faqs: [
      {
        question: 'כמה זמן מחזיקה ניפוחה?',
        answer: 'כרית מבודקת בקפדנות — אינה אמורה לרדת ניפוחה במהלך לילה שלם.',
      },
    ],
    seoTitle: 'Sea to Summit Aeros Ultralight — כרית קמפינג 57 גרם',
    seoDescription:
      'כרית קמפינג Sea to Summit Aeros Ultralight — 57 גרם, שסתום XPRESS, עד 11 ס"מ עובי. לרכישה בTrailNest.',
    image:
      'https://seatosummit.com/cdn/shop/files/045306_AerosUltralightPillow_Regular_AquaSea_PRIMARY_1500.jpg?v=1769644509',
    images: [
      'https://seatosummit.com/cdn/shop/files/045306_AerosUltralightPillow_Regular_AquaSea_PRIMARY_1500.jpg?v=1769644509',
      'https://seatosummit.com/cdn/shop/files/045305_AerosUltralightPillow_Regular_Moonstruck_MODEL_1_1500.jpg?v=1770747799',
      'https://seatosummit.com/cdn/shop/files/045301_AerosUltralightPillow_Regular_Beluga_USP_1_1500_391e2777-bf69-49b2-9014-1cda15e2aacc.jpg?v=1770404105',
      'https://seatosummit.com/cdn/shop/files/045301_AerosUltralightPillow_Regular_Beluga_ADDITIONAL_1_1500.jpg?v=1772815630',
      'https://seatosummit.com/cdn/shop/files/045305_AerosUltralightPillow_Regular_Moonstruck_USP_1_1500.jpg?v=1772815630',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=CD_KJO5qnSc',
    inStock: true,
    sku: 'STS-045301',
    brand: 'Sea to Summit',
    deliveryTime: '5–7 ימי עסקים',
    sourceUrl: 'https://seatosummit.com/products/aeros-pillow-ultra-light',
    tags: ['כרית קמפינג', 'Sea to Summit', 'Aeros', 'אולטראלייט'],
    relatedSlugs: ['sts-spark-down-sleeping-bag', 'neoair-xlite-nxt', 'z-lite-sol'],
  },

  /* ── 6. מזרן Therm-a-Rest ProLite Plus ───────────────────────────── */
  {
    id: 'prod-706',
    name: 'מזרן שינה עצמי-ניפוח Therm-a-Rest ProLite Plus — R-Value 3.2',
    slug: 'thermarest-prolite-plus',
    category: 'שינה ונוחות',
    categorySlug: 'sleeping-comfort',
    price: 699,
    originalPrice: 849,
    rating: 4.7,
    reviewCount: 289,
    badge: 'bestseller',
    inStock: true,
    sku: 'TAR-11415',
    brand: 'Therm-a-Rest',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://cascadedesigns.com/products/prolite-plus-self-inflating-sleeping-pad',
    image: 'https://cascadedesigns.com/cdn/shop/files/11415_thermarest_prolite_plus_prism_large_angle.jpg?v=1724820257',
    images: [
      'https://cascadedesigns.com/cdn/shop/files/11415_thermarest_prolite_plus_prism_large_angle.jpg?v=1724820257',
      'https://cascadedesigns.com/cdn/shop/files/11415_thermarest_prolite_plus_prism_large_top.jpg?v=1724820257',
      'https://cascadedesigns.com/cdn/shop/files/11415_thermarest_prolite_plus_lifestyle.jpg?v=1724820257',
    ],
    videoUrl: null,
    shortDescription: 'מזרן עצמי-ניפוח Therm-a-Rest ProLite Plus — R-Value 3.2, 3 עונות. עובי 3.8 ס"מ, 510 גרם (Regular).',
    description: 'Therm-a-Rest ProLite Plus — המזרן העצמי-ניפוח הקלאסי לטיולי 3 עונות. פותחים השסתום, המזרן מתנפח לבד תוך 3–5 דקות. R-Value 3.2 לבידוד מהקרקע. עובי 3.8 ס"מ. 510 גרם. מתאים מאביב עד שלגים קלים.',
    benefits: [
      'עצמי-ניפוח — פותחים, מחכים, שוכבים',
      'R-Value 3.2 — 3 עונות כולל לילות קרים',
      'קצף גבוה-צפיפות — מחזיק צורה שנים',
      '510 גרם — קל מספיק לתרמיל',
    ],
    specs: [
      { label: 'R-Value', value: '3.2' },
      { label: 'עובי', value: '3.8 ס"מ' },
      { label: 'משקל', value: '510 גרם (Regular)' },
      { label: 'מידות', value: '183 × 51 ס"מ (Regular)' },
      { label: 'ניפוח', value: 'עצמי-ניפוח + נשיפה לסגירה' },
    ],
    faqs: [
      {
        question: 'מה ההבדל מ-NeoAir XLite?',
        answer: 'ProLite Plus: עצמי-ניפוח (קצף), יותר שקט ופחות יוקרתי — R-Value נמוך יותר ב-1.3. NeoAir XLite: מנופח, קל יותר (354 vs 510 גרם), בידוד גבוה יותר — יקר יותר.',
      },
    ],
    seoTitle: 'מזרן Therm-a-Rest ProLite Plus R-Value 3.2 | CampIL',
    seoDescription: 'Therm-a-Rest ProLite Plus, R-Value 3.2, עצמי ניפוח, 510 גרם. ₪699.',
    tags: ['מזרן שינה', 'Therm-a-Rest', 'ProLite', 'קמפינג'],
    relatedSlugs: ['neoair-xlite-nxt', 'z-lite-sol', 'nemo-tensor-all-season'],
  },

  /* ── 7. שק שינה NEMO Disco 15 Down ───────────────────────────────── */
  {
    id: 'prod-707',
    name: 'שק שינה ברווז NEMO Disco 15 — ספוילר צוואר',
    slug: 'nemo-disco-15-sleeping-bag',
    category: 'שינה ונוחות',
    categorySlug: 'sleeping-comfort',
    price: 1299,
    originalPrice: 1549,
    rating: 4.8,
    reviewCount: 143,
    badge: 'new',
    inStock: true,
    sku: 'NEMO-811666036155',
    brand: 'NEMO Equipment',
    deliveryTime: '7–10 ימי עסקים',
    sourceUrl: 'https://www.nemoequipment.com/products/disco-sleeping-bag',
    image: 'https://www.nemoequipment.com/cdn/shop/files/01_Disco_15_811666036155_Main.jpg?v=1772661411',
    images: [
      'https://www.nemoequipment.com/cdn/shop/files/01_Disco_15_811666036155_Main.jpg?v=1772661411',
      'https://www.nemoequipment.com/cdn/shop/files/03_Disco_15_811666036155_Humanized.jpg?v=1772661411',
      'https://www.nemoequipment.com/cdn/shop/files/05_Disco_15_811666036155_Detail-Footbox.jpg?v=1772661411',
    ],
    videoUrl: null,
    shortDescription: 'שק שינה ברווז NEMO Disco 15 — מרחב נוסף לכתפיים ולרגליים, מרפקי Spoon™, ספוילר צוואר. 3 עונות.',
    description: 'NEMO Disco 15 — שק שינה מוממ ברווז עם מרחב נוסף 15% בחלק הכתפיים (Spoon™ shape) לישני צד ובטן. ספוילר צוואר אחורי חוסם זרם קור. Blanket Fold™ — פתיחה רחבה לתנאי קיץ. ציפוי DWR על הקצף החיצוני.',
    benefits: [
      'Spoon™ Shape — מרחב נוסף 15% לכתפיים ורגליים',
      'ספוילר צוואר — חוסם זרם קור מאחור',
      'Blanket Fold™ — פתיחה רחבה לחום',
      'ברווז 650FP — קל ומבודד',
    ],
    specs: [
      { label: 'טמפרטורה נוחה', value: '+7°C' },
      { label: 'טמפרטורה מינימלית', value: '-9°C' },
      { label: 'מילוי', value: 'ברווז 650FP' },
      { label: 'משקל', value: '1.02 ק"ג (Regular)' },
      { label: 'ציפוי', value: 'DWR מלחמת לחות' },
    ],
    faqs: [
      {
        question: 'מה הכוונה ב-Spoon Shape?',
        answer: 'ה-Spoon™ shape מרחיב את החלק האמצעי של השק — יותר מרחב לכתפיים וברכיים בלי לאבד בידוד בקצות.',
      },
    ],
    seoTitle: 'שק שינה NEMO Disco 15 ברווז | Spoon Shape | CampIL',
    seoDescription: 'NEMO Disco 15. ברווז 650FP, Spoon Shape, ספוילר צוואר. ₪1,299.',
    tags: ['שק שינה', 'NEMO', 'Disco', 'ברווז'],
    relatedSlugs: ['sts-spark-down-sleeping-bag', 'neoair-xlite-nxt', 'thermarest-prolite-plus'],
  },

  /* ── 8. בטנת שק שינה Sea to Summit Reactor Liner ────────────────── */
  {
    id: 'prod-708',
    name: 'בטנת שק שינה Sea to Summit Reactor Thermal Liner',
    slug: 'sts-reactor-sleeping-bag-liner',
    category: 'שינה ונוחות',
    categorySlug: 'sleeping-comfort',
    price: 249,
    originalPrice: 319,
    rating: 4.6,
    reviewCount: 198,
    inStock: true,
    sku: 'STS-ASLR',
    brand: 'Sea to Summit',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://seatosummit.com/products/reactor-sleeping-bag-liner',
    image: 'https://seatosummit.com/cdn/shop/products/ReactorThermolite_Mummy_Red_PRIMARY_1500.jpg?v=1678474359&width=1500',
    images: [
      'https://seatosummit.com/cdn/shop/products/ReactorThermolite_Mummy_Red_PRIMARY_1500.jpg?v=1678474359&width=1500',
      'https://seatosummit.com/cdn/shop/products/ReactorThermolite_Liner_Inuse.jpg?v=1678474359&width=1500',
    ],
    videoUrl: null,
    shortDescription: 'בטנת שק שינה Sea to Summit Reactor Thermal — Thermolite, מוסיפה 7–15°C לשק. 180 גרם. כפולה: שק שינה + מארח.',
    description: 'Sea to Summit Reactor Liner — בטנה תרמית מ-Thermolite® שמוסיפה 7–15 מעלות לכל שק שינה קיים. 180 גרם. מתאים לשימוש עצמאי בקיץ ישראלי כשק לייט, ולהוספת חום בחורף. מתקפלת לשקית קטנה.',
    benefits: [
      'מוסיפה 7–15°C לשק שינה קיים',
      '180 גרם — לא מורגש בתרמיל',
      'Thermolite® — מבודד גם רטוב',
      'שימוש עצמאי בקיץ ישראלי',
    ],
    specs: [
      { label: 'הוספת חום', value: '7–15°C (לפי שק)' },
      { label: 'חומר', value: 'Thermolite® Reactive' },
      { label: 'משקל', value: '180 גרם' },
      { label: 'צורה', value: 'מאמי (Mummy)' },
    ],
    faqs: [
      {
        question: 'אפשר לישון עם הבטנה בלי שק שינה?',
        answer: 'כן — בקיץ ישראלי (לילות 20–25°C) הבטנה לבד מספיקה. בחורף — הוסיפו שק שינה.',
      },
    ],
    seoTitle: 'בטנת שק שינה Sea to Summit Reactor Thermal Liner | CampIL',
    seoDescription: 'Sea to Summit Reactor Liner. Thermolite, +7-15°C, 180 גרם. ₪249.',
    tags: ['בטנת שק שינה', 'Sea to Summit', 'Reactor', 'חום'],
    relatedSlugs: ['sts-spark-down-sleeping-bag', 'nemo-disco-15-sleeping-bag', 'neoair-xlite-nxt'],
  },

  /* ── 9. מזרן רחב Therm-a-Rest Trail King SV 66 ───────────────────── */
  {
    id: 'prod-709',
    name: 'מזרן קמפינג רחב Therm-a-Rest Trail King SV 66 — עצמי-ניפוח',
    slug: 'thermarest-trail-king-sv',
    category: 'שינה ונוחות',
    categorySlug: 'sleeping-comfort',
    price: 499,
    originalPrice: 649,
    rating: 4.7,
    reviewCount: 174,
    inStock: true,
    sku: 'TAR-11250',
    brand: 'Therm-a-Rest',
    deliveryTime: '7–10 ימי עסקים',
    sourceUrl: 'https://cascadedesigns.com/products/trail-king-sv-self-inflating-sleeping-pad',
    image: 'https://cascadedesigns.com/cdn/shop/files/11250_thermarest_trail_king_sv_66_large_angle.jpg?v=1724820257',
    images: [
      'https://cascadedesigns.com/cdn/shop/files/11250_thermarest_trail_king_sv_66_large_angle.jpg?v=1724820257',
      'https://cascadedesigns.com/cdn/shop/files/11250_thermarest_trail_king_sv_66_large_top.jpg?v=1724820257',
    ],
    videoUrl: null,
    shortDescription: 'מזרן עצמי-ניפוח 66 ס"מ רחב לקמפינג רכב — Therm-a-Rest Trail King SV. R-Value 6.0, עובי 6.4 ס"מ.',
    description: 'Therm-a-Rest Trail King SV 66 — מזרן קמפינג רחב (66 ס"מ) למי שלא מוכן לוותר על נוחות. עצמי-ניפוח, R-Value 6.0 לחורף ישראלי, עובי 6.4 ס"מ. שסתום SoftValve לניפוח וריקון שקטים. מתאים לאוהל ולגג ברכב (rooftop tent).',
    benefits: [
      '66 ס"מ רחב — מרחב שינה אמיתי',
      'R-Value 6.0 — מבודד לכל עונה',
      'עובי 6.4 ס"מ — נוחות קרובה למיטה',
      'עצמי-ניפוח — פותחים, מחכים',
    ],
    specs: [
      { label: 'R-Value', value: '6.0' },
      { label: 'עובי', value: '6.4 ס"מ' },
      { label: 'רוחב', value: '66 ס"מ' },
      { label: 'משקל', value: '850 גרם (Large)' },
      { label: 'מידות', value: '196 × 66 ס"מ (Large)' },
    ],
    faqs: [
      {
        question: 'מתאים לרוב הגג (rooftop tent)?',
        answer: 'כן — Trail King SV 66 הוא הגודל הסטנדרטי לאוהלי גג צרים. לאוהלי גג 2 אנשים — בדקו מידות ספציפיות.',
      },
    ],
    seoTitle: 'מזרן Therm-a-Rest Trail King SV 66 | R-Value 6.0 | CampIL',
    seoDescription: 'Therm-a-Rest Trail King SV 66, R-Value 6.0, 6.4 ס"מ עובי. ₪499.',
    tags: ['מזרן שינה', 'Therm-a-Rest', 'Trail King', 'קמפינג רכב'],
    relatedSlugs: ['thermarest-prolite-plus', 'neoair-xlite-nxt', 'z-lite-sol'],
  },

  /* ── 10. כרית NEMO Fillo Luxury Camp Pillow ──────────────────────── */
  {
    id: 'prod-710',
    name: 'כרית קמפינג NEMO Fillo Luxury Camp Pillow — אוושת מיקרוב',
    slug: 'nemo-fillo-pillow',
    category: 'שינה ונוחות',
    categorySlug: 'sleeping-comfort',
    price: 169,
    originalPrice: 219,
    rating: 4.8,
    reviewCount: 312,
    badge: 'bestseller',
    inStock: true,
    sku: 'NEMO-811666020390',
    brand: 'NEMO Equipment',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://www.nemoequipment.com/products/fillo-luxury-camp-pillow',
    image: 'https://www.nemoequipment.com/cdn/shop/files/01_Fillo_811666020390_Main.jpg?v=1772661411',
    images: [
      'https://www.nemoequipment.com/cdn/shop/files/01_Fillo_811666020390_Main.jpg?v=1772661411',
      'https://www.nemoequipment.com/cdn/shop/files/03_Fillo_811666020390_Humanized.jpg?v=1772661411',
      'https://www.nemoequipment.com/cdn/shop/files/09_Fillo_811666020390_Detail.jpg?v=1772661411',
    ],
    videoUrl: null,
    shortDescription: 'כרית קמפינג NEMO Fillo — מיקרוב + חיצוני מנופח. נוחה כמו כרית בית, 75 גרם. לא מחליקה.',
    description: 'NEMO Fillo Luxury Pillow — כרית קמפינג הייברידית: ליבה ממיקרוב (סינתטי) לנוחות קבועה, קצוות מנופחים לתמיכה. 75 גרם. ציפוי מהדק לשק שינה (snap) כדי שלא תחליק בלילה. נגד ריח.',
    benefits: [
      'הייברידית: מיקרוב + ניפוח — הכי קרוב לכרית בית',
      'לא מחליקה — snap מהדק לשק שינה',
      '75 גרם — קל לתרמיל',
      'ציפוי 100% פוליאסטר — נגד ריח',
    ],
    specs: [
      { label: 'משקל', value: '75 גרם' },
      { label: 'מילוי', value: 'מיקרוב + אוויר' },
      { label: 'ממדים פרוס', value: '38 × 25 ס"מ' },
      { label: 'הידוק', value: 'snap לשק שינה' },
    ],
    faqs: [
      {
        question: 'מה ההבדל מה-Aeros Pillow של Sea to Summit?',
        answer: 'Fillo: מיקרוב בפנים — יציבה יותר, פחות "גורמת לגב". Aeros: ניפוח בלבד — קלה יותר (56 גרם vs 75 גרם), פחות נוחה.',
      },
    ],
    seoTitle: 'כרית קמפינג NEMO Fillo Luxury | 75 גרם | CampIL',
    seoDescription: 'NEMO Fillo Luxury Pillow. מיקרוב + ניפוח, 75 גרם, snap לשק. ₪169.',
    tags: ['כרית קמפינג', 'NEMO', 'Fillo', 'שינה'],
    relatedSlugs: ['sts-aeros-pillow', 'neoair-xlite-nxt', 'thermarest-prolite-plus'],
  },
];
