import type { Product } from '../types';

export const storageOrganizationProducts: Product[] = [
  {
    id: 'prod-801',
    name: 'שק אטום Sea to Summit Ultra-Sil Dry Bag 8L — 43 גרם',
    slug: 'sts-ultra-sil-dry-bag-8l',
    category: 'אחסון וארגון',
    categorySlug: 'storage-organization',
    price: 99,
    rating: 4.8,
    badge: 'bestseller',
    shortDescription: 'שק אטום Ultra-Sil של Sea to Summit — 43 גרם, סיליקון 30D, מותאם לכל שקית תרמיל.',
    description:
      'ה-Ultra-Sil Dry Bag של Sea to Summit הוא בין השקים האטומים הקלים ביותר בשוק. עשוי מניילון 30D מצופה סיליקון דו-צדדי עם דירוג עמידות למים של 35,000 מ"מ. סגירת Roll-Top המגולגלת 3 פעמים פחות יוצרת אטימות מלאה. בסיס אובלי מאפשר ניצול יעיל של הנפח. משקל: 43 גרם (8L).',
    benefits: [
      '43 גרם בלבד — קל ופחוס',
      'דירוג עמידות מים 35,000 מ"מ',
      'ניילון 30D מצופה סיליקון דו-צדדי',
      'בסיס אובלי לניצול נפח מרבי',
      'סגירת Roll-Top אמינה',
    ],
    specs: [
      { label: 'משקל', value: '43 גרם (8L)' },
      { label: 'נפח', value: '8 ל׳' },
      { label: 'חומר', value: 'ניילון 30D מצופה סיליקון' },
      { label: 'דירוג מים', value: '35,000 מ"מ' },
      { label: 'סגירה', value: 'Roll-Top' },
    ],
    faqs: [
      {
        question: 'האם השק עומד בשקיעה מלאה במים?',
        answer: 'כן — ה-Ultra-Sil אטום לחלוטין כשהסגירה מגולגלת לפחות 3 פעמים.',
      },
    ],
    seoTitle: 'Sea to Summit Ultra-Sil Dry Bag 8L — שק אטום 43 גרם',
    seoDescription:
      'שק אטום Sea to Summit Ultra-Sil 8L — 43 גרם, 35,000 מ"מ עמידות מים. לרכישה בTrailNest.',
    image:
      'https://seatosummit.com/cdn/shop/products/Ultra-SilDryBag3LSpicyOrange.jpg?v=1741380767',
    images: [
      'https://seatosummit.com/cdn/shop/products/Ultra-SilDryBag3LSpicyOrange.jpg?v=1741380767',
      'https://seatosummit.com/cdn/shop/products/Ultra-SilDryBag_Family.jpg?v=1675205746',
      'https://seatosummit.com/cdn/shop/products/01_Ultra-SilDryBagTarragonOpen.jpg?v=1741380767',
      'https://seatosummit.com/cdn/shop/products/01_Ultra-SilDryBagTarragonRollTop.jpg?v=1741380767',
      'https://seatosummit.com/cdn/shop/products/01_Ultra-SilDryBagTarragonRollWaterproof.jpg?v=1741380767',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=Z1r0VCykdlk',
    inStock: true,
    sku: 'STS-ASG022031',
    brand: 'Sea to Summit',
    deliveryTime: '5–7 ימי עסקים',
    sourceUrl: 'https://seatosummit.com/products/ultra-sil-dry-bag',
    tags: ['שק אטום', 'Sea to Summit', 'Ultra-Sil', 'אחסון', 'אטום'],
    relatedSlugs: ['sts-lightweight-dry-bag-20l', 'sts-big-river-dry-bag-13l', 'sts-evac-compression-dry-bag-8l'],
  },
  {
    id: 'prod-802',
    name: 'שק אטום Sea to Summit Lightweight Dry Bag 20L — 70 גרם',
    slug: 'sts-lightweight-dry-bag-20l',
    category: 'אחסון וארגון',
    categorySlug: 'storage-organization',
    price: 129,
    rating: 4.8,
    shortDescription: 'שק אטום 20L של Sea to Summit — ניילון 70D ממוחזר, עמיד, עם רצועת גב אופציונלית.',
    description:
      'ה-Lightweight Dry Bag 20L של Sea to Summit הוא שק אטום קל ועמיד עשוי מניילון 70D ממוחזר מאושר bluesign עם ציפוי DWR ללא PFAS. דירוג עמידות מים: 10,000 מ"מ. סגירת Roll-Top עם D-Ring לחיבור רצועת כתף. בסיס אובלי. תאמה לרצועת Dry Bag Sling (נמכרת בנפרד) לנשיאה ידנית-חופשית. מגיע ב-6 גדלים (1.5L–35L).',
    benefits: [
      'ניילון 70D ממוחזר מאושר bluesign',
      'דירוג מים 10,000 מ"מ',
      'D-Ring לחיבור רצועת כתף',
      'פנים לבן לנראות מיטבית של התכולה',
      'ניתן לנשיאה על הגב עם רצועת Sling',
    ],
    specs: [
      { label: 'משקל', value: '70 גרם (20L)' },
      { label: 'נפח', value: '20 ל׳' },
      { label: 'חומר', value: 'ניילון 70D ממוחזר' },
      { label: 'דירוג מים', value: '10,000 מ"מ' },
      { label: 'בקרת מפרק', value: 'Hypalon Roll-Top' },
    ],
    faqs: [
      {
        question: 'האם מתאים לנשיאה על הגב?',
        answer: 'בשילוב עם רצועת Dry Bag Sling (נמכרת בנפרד) ניתן לנשוא אותו על הכתף כמו תיק.',
      },
    ],
    seoTitle: 'Sea to Summit Lightweight Dry Bag 20L — שק אטום 70 גרם',
    seoDescription:
      'שק אטום Sea to Summit Lightweight 20L — 70 גרם, 10,000 מ"מ, ניילון ממוחזר. לרכישה בTrailNest.',
    image:
      'https://seatosummit.com/cdn/shop/products/LightweightDryBag_20LBuckle_SurfBlue_2048x2048_f3cf7c8a-0903-44aa-af46-5b0bb81189a7.jpg?v=1741382607',
    images: [
      'https://seatosummit.com/cdn/shop/products/LightweightDryBag_20LBuckle_SurfBlue_2048x2048_f3cf7c8a-0903-44aa-af46-5b0bb81189a7.jpg?v=1741382607',
      'https://seatosummit.com/cdn/shop/files/01_LightweightDryBag20LSurftheWebStraponBack.jpg?v=1741382607',
      'https://seatosummit.com/cdn/shop/files/01_LightweightDryBag20LSurftheWebStraponBackSideView.jpg?v=1741382607',
      'https://seatosummit.com/cdn/shop/files/LightweightDryBag_20LSeam_SurfBlue_2048x2048-1500x1500-f3a2c67.jpg?v=1741382607',
      'https://seatosummit.com/cdn/shop/products/00_LightweightDryBagSurftheWebFamily.jpg?v=1675204821',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=xTiCc_eJEkc',
    inStock: true,
    sku: 'STS-ASG012031',
    brand: 'Sea to Summit',
    deliveryTime: '5–7 ימי עסקים',
    sourceUrl: 'https://seatosummit.com/products/lightweight-dry-bag',
    tags: ['שק אטום', 'Sea to Summit', 'Lightweight', '20L', 'אחסון'],
    relatedSlugs: ['sts-ultra-sil-dry-bag-8l', 'sts-big-river-dry-bag-13l', 'ortlieb-dry-bag-10l'],
  },
  {
    id: 'prod-803',
    name: 'שק אטום Sea to Summit Big River Dry Bag 13L — 420D ניילון',
    slug: 'sts-big-river-dry-bag-13l',
    category: 'אחסון וארגון',
    categorySlug: 'storage-organization',
    price: 189,
    rating: 4.7,
    badge: 'new',
    shortDescription: 'שק אטום עמיד Big River 13L של Sea to Summit — 420D ריפסטופ, עמידות 10,000 מ"מ.',
    description:
      'ה-Big River Dry Bag 13L הוא השק האטום העמיד ביותר בסדרת Sea to Summit — בנוי מניילון ריפסטופ 420D מצופה PU עם דירוג 10,000 מ"מ. מתאים לקאיאקינג, ראפטינג, שטף וקמפינג רטוב. D-Ring בתחתית ובצד לחיבור רצועת Sling. סגירת Roll-Top מגולגלת 3 פעמים. זמין ב-5L, 8L, 13L, 20L, 35L, 65L.',
    benefits: [
      '420D ניילון ריפסטופ — עמיד מאוד',
      'דירוג מים 10,000 מ"מ',
      'D-Ring עליון ותחתון לרצועת Sling',
      'מתאים לספורט מים ומשלחות',
      'זמין בגדלים 5–65 ל׳',
    ],
    specs: [
      { label: 'נפח', value: '13 ל׳' },
      { label: 'חומר', value: '420D ניילון ריפסטופ PU' },
      { label: 'דירוג מים', value: '10,000 מ"מ' },
      { label: 'סגירה', value: 'Roll-Top + אבזם' },
      { label: 'D-Ring', value: 'עליון + תחתון' },
    ],
    faqs: [
      {
        question: 'מה ההבדל בין Big River ל-Lightweight Dry Bag?',
        answer: 'ה-Big River עשוי מניילון 420D כבד יותר ועמיד לשפשוף ולניקוב — מתאים לאתגרי ספורט מים.',
      },
    ],
    seoTitle: 'Sea to Summit Big River Dry Bag 13L — שק אטום עמיד 420D',
    seoDescription:
      'שק אטום Sea to Summit Big River 13L — 420D ריפסטופ, 10,000 מ"מ. לרכישה בTrailNest.',
    image:
      'https://seatosummit.com/cdn/shop/products/BigRiverDryBag_13LBuckle_DullGold_2048x2048_f8db706b-0048-4c9c-865a-d1630adb4509.jpg?v=1741386654',
    images: [
      'https://seatosummit.com/cdn/shop/products/BigRiverDryBag_13LBuckle_DullGold_2048x2048_f8db706b-0048-4c9c-865a-d1630adb4509.jpg?v=1741386654',
      'https://seatosummit.com/cdn/shop/products/BigRiverDryBag5LDullGold.jpg?v=1741386654',
      'https://seatosummit.com/cdn/shop/products/00_BigRiverDryBagDullGoldFamily.jpg?v=1675210098',
      'https://seatosummit.com/cdn/shop/products/00_BigRiverDryBagDullGoldOpen.jpg?v=1741386654',
      'https://seatosummit.com/cdn/shop/products/00_BigRiverDryBagWaterproof.jpg?v=1741386654',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=rOsD_XK08ng',
    inStock: true,
    sku: 'STS-ASG040031',
    brand: 'Sea to Summit',
    deliveryTime: '5–7 ימי עסקים',
    sourceUrl: 'https://seatosummit.com/products/the-big-river-dry-bag',
    tags: ['שק אטום', 'Sea to Summit', 'Big River', 'ספורט מים', 'אחסון'],
    relatedSlugs: ['sts-ultra-sil-dry-bag-8l', 'sts-lightweight-dry-bag-20l', 'ortlieb-dry-bag-10l'],
  },
  {
    id: 'prod-804',
    name: 'שק דחיסה Sea to Summit Evac Compression Dry Bag UL 8L',
    slug: 'sts-evac-compression-dry-bag-8l',
    category: 'אחסון וארגון',
    categorySlug: 'storage-organization',
    price: 199,
    rating: 4.7,
    shortDescription: 'שק דחיסה אטום Evac UL של Sea to Summit — פנימי אוויר יוצא, מים לא נכנסים.',
    description:
      'ה-Evac Compression Dry Bag UL הוא פתרון ייחודי: בד Evac מאפשר לאוויר לצאת תוך כדי שמים נשמרים בחוץ — ללא ולבים. מדחס שק שינה, בגדים ומצנח ב-50–80% מהנפח המקורי, תוך שמירה מלאה על אטימות. מגיע ב-3L, 5L, 8L, 13L, 20L. עשוי מבד Evac + ניילון 70D.',
    benefits: [
      'דחיסה עד 80% ללא ולב דחיסה',
      'אטום לחלוטין — אוויר יוצא, מים לא נכנסים',
      'קל מבדים דחיסה קלאסיים',
      'מתאים לשק שינה, ביגוד ומצנח',
      'סגירת Roll-Top כפולה',
    ],
    specs: [
      { label: 'נפח', value: '8 ל׳' },
      { label: 'חומר', value: 'Evac + ניילון 70D' },
      { label: 'דחיסה', value: 'עד 80% מהנפח המקורי' },
      { label: 'אטימות', value: 'אוויר יוצא, מים לא נכנסים' },
      { label: 'סגירה', value: 'Roll-Top כפול' },
    ],
    faqs: [
      {
        question: 'האם ניתן לדחוס שק שינה פוך בלחיסה?',
        answer: 'כן — אפשרי, אך מומלץ שלא לאחסן שק פוך דחוס לאורך זמן כדי לשמור על בידוד הדאון.',
      },
    ],
    seoTitle: 'Sea to Summit Evac Compression Dry Bag UL — שק דחיסה אטום 8L',
    seoDescription:
      'שק דחיסה אטום Sea to Summit Evac UL 8L — דחיסה עד 80%, אטום לחלוטין. לרכישה בTrailNest.',
    image:
      'https://seatosummit.com/cdn/shop/products/EvacCompressionDryBagUL3LHighRiseCombo.jpg?v=1678248818',
    images: [
      'https://seatosummit.com/cdn/shop/products/EvacCompressionDryBagUL3LHighRiseCombo.jpg?v=1678248818',
      'https://seatosummit.com/cdn/shop/products/00_EvacCompressionDryBagUL_Family.jpg?v=1675206239',
      'https://seatosummit.com/cdn/shop/products/EvacCompressionDryBagUL_DetailBuckle.jpg?v=1678248813',
      'https://seatosummit.com/cdn/shop/products/EvacCompressionDryBagUL_DetailCompressionStrap.jpg?v=1678248818',
      'https://seatosummit.com/cdn/shop/products/EvacCompressionDryBagUL_DetailWaterproof.jpg?v=1678248818',
    ],
    videoUrl: null,
    inStock: true,
    sku: 'STS-ASG061031',
    brand: 'Sea to Summit',
    deliveryTime: '5–7 ימי עסקים',
    sourceUrl: 'https://seatosummit.com/products/evac-compression-dry-bag-ul',
    tags: ['שק דחיסה', 'Sea to Summit', 'Evac', 'אטום', 'אחסון'],
    relatedSlugs: ['sts-ultra-sil-dry-bag-8l', 'sts-lightweight-dry-bag-20l', 'sts-big-river-dry-bag-13l'],
  },
  {
    id: 'prod-805',
    name: 'שק אטום ORTLIEB Dry-Bag 10L — תוצרת גרמניה',
    slug: 'ortlieb-dry-bag-10l',
    category: 'אחסון וארגון',
    categorySlug: 'storage-organization',
    price: 229,
    rating: 4.9,
    badge: 'bestseller',
    shortDescription: 'שק אטום ORTLIEB Dry-Bag 10L — PU Taffeta 210D, אטום לחלוטין, מיוצר בגרמניה.',
    description:
      'ה-ORTLIEB Dry-Bag הוא סטנדרט תעשייתי לאטימות מלאה — מיוצר בגרמניה מבד PU Taffeta 210D עם תפרים מרותכים. סגירת Roll-Top עם אבזם פלסטי הופכת אותו לאטום לחלוטין. משמש ל-25 שנה אצל נוסעי קאיאק ורוכבי אופניים. מגיע ב-5–109 ל׳. צבע: Slate. מק"ט: K4151.',
    benefits: [
      'תוצרת גרמניה — איכות בלתי מתפשרת',
      'PU Taffeta 210D — עמיד לשפשוף',
      'תפרים מרותכים לאטימות מוחלטת',
      'מחזיק ב-25 שנה של שימוש',
      'זמין ב-5L עד 109L',
    ],
    specs: [
      { label: 'נפח', value: '10 ל׳' },
      { label: 'חומר', value: 'PU Taffeta 210D' },
      { label: 'תפרים', value: 'מרותכים — אטימות מוחלטת' },
      { label: 'מק"ט', value: 'K4151' },
      { label: 'מדינת ייצור', value: 'גרמניה' },
    ],
    faqs: [
      {
        question: 'האם השק אטום לחלוטין גם בסחף מים?',
        answer: 'כן — התפרים המרותכים ובד ה-PU מספקים אטימות מלאה גם בשקיעה ממושכת.',
      },
    ],
    seoTitle: 'ORTLIEB Dry-Bag 10L — שק אטום גרמני PU Taffeta',
    seoDescription:
      'שק אטום ORTLIEB Dry-Bag 10L — תפרים מרותכים, PU Taffeta 210D, תוצרת גרמניה. לרכישה בTrailNest.',
    image:
      'https://us.ortlieb.com/cdn/shop/files/productimage-k4151-front.jpg?v=1737541614',
    images: [
      'https://us.ortlieb.com/cdn/shop/files/productimage-k4151-front.jpg?v=1737541614',
      'https://us.ortlieb.com/cdn/shop/files/productimage-k4151-back.jpg?v=1737541614',
      'https://us.ortlieb.com/cdn/shop/files/productimage-k4151-inside.jpg?v=1737541614',
      'https://us.ortlieb.com/cdn/shop/files/productimage-k4151-detail.jpg?v=1737541614',
      'https://us.ortlieb.com/cdn/shop/files/productimage-dry-bag-10855.jpg?v=1737541624',
    ],
    videoUrl: null,
    inStock: true,
    sku: 'ORTLIEB-K4151',
    brand: 'ORTLIEB',
    deliveryTime: '7–10 ימי עסקים',
    sourceUrl: 'https://us.ortlieb.com/products/dry-bag',
    tags: ['שק אטום', 'ORTLIEB', 'גרמניה', 'אחסון', 'קאיאקינג'],
    relatedSlugs: ['sts-ultra-sil-dry-bag-8l', 'sts-big-river-dry-bag-13l', 'sts-evac-compression-dry-bag-8l'],
  },

  /* ── 6. Sea to Summit Hydraulic Dry Bag 20L ──────────────────────── */
  {
    id: 'prod-806',
    name: 'שק אטום כבד Sea to Summit Hydraulic Dry Bag 20 ל׳',
    slug: 'sts-hydraulic-dry-bag-20l',
    category: 'אחסון וארגון',
    categorySlug: 'storage-organization',
    price: 299,
    originalPrice: 379,
    rating: 4.8,
    reviewCount: 167,
    badge: 'new',
    inStock: true,
    sku: 'STS-AHY020',
    brand: 'Sea to Summit',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://seatosummit.com/products/hydraulic-dry-bag',
    image: 'https://seatosummit.com/cdn/shop/products/durable-welded-waterproof-hydraulic-dry-bag.jpg?v=1621527060',
    images: [
      'https://seatosummit.com/cdn/shop/products/durable-welded-waterproof-hydraulic-dry-bag.jpg?v=1621527060',
    ],
    videoUrl: null,
    shortDescription: 'שק אטום כבד-משימה Sea to Summit Hydraulic 20 ל׳ — 420D אקספוד, ידית נשיאה, כתפיות. לאוברלנדינג ולקאיאקינג.',
    description: 'Sea to Summit Hydraulic Dry Bag 20L — שק אטום ממשפחת ה-Hydraulic, עשוי מ-420D Nylon Ripstop בציפוי אקספוד. ידית נשיאה + כתפיות ניתקות. סגירת Roll-Top כפולה. דירוג מים 20,000 מ"מ. לאוברלנדינג, לקאיאקינג ולאחסון בגג הרכב.',
    benefits: [
      '420D — עמיד לשפשוף ולחיתוך',
      'כתפיות ניתקות — נשיאה כתרמיל',
      'Roll-Top כפול — אטימה מרבית',
      '20 ל׳ — מחליף ילקוט שלם',
    ],
    specs: [
      { label: 'נפח', value: '20 ל׳' },
      { label: 'חומר', value: '420D Nylon Ripstop + Ecopak' },
      { label: 'דירוג מים', value: '20,000 מ"מ' },
      { label: 'סגירה', value: 'Roll-Top כפול' },
      { label: 'ידיות', value: 'נשיאה + כתפיות' },
    ],
    faqs: [
      {
        question: 'מה ההבדל מה-Ultra-Sil?',
        answer: 'Ultra-Sil: קל מאוד (43 גרם), עמיד פחות. Hydraulic: כבד יותר אך עמיד הרבה יותר לשפשוף — מתאים לאוברלנדינג ולסיורים קשים.',
      },
    ],
    seoTitle: 'שק אטום Sea to Summit Hydraulic 20 ל׳ | 420D | CampIL',
    seoDescription: 'Sea to Summit Hydraulic Dry Bag 20L, 420D, 20,000מ"מ. ₪299.',
    tags: ['שק אטום', 'Sea to Summit', 'Hydraulic', 'אוברלנדינג'],
    relatedSlugs: ['sts-ultra-sil-dry-bag-8l', 'sts-big-river-dry-bag-13l', 'ortlieb-dry-bag-10l'],
  },

  /* ── 7. Ortlieb Dry Bag PD350 13L ────────────────────────────────── */
  {
    id: 'prod-807',
    name: 'שק אטום Ortlieb Dry Bag PD350 13 ל׳ — עמיד במיוחד',
    slug: 'ortlieb-dry-bag-pd350-13l',
    category: 'אחסון וארגון',
    categorySlug: 'storage-organization',
    price: 239,
    originalPrice: 299,
    rating: 4.9,
    reviewCount: 213,
    badge: 'bestseller',
    inStock: true,
    sku: 'ORTLIEB-K4651',
    brand: 'ORTLIEB',
    deliveryTime: '7–10 ימי עסקים',
    sourceUrl: 'https://us.ortlieb.com/products/dry-bag-pd350',
    image: 'https://us.ortlieb.com/cdn/shop/files/productimage-k4651-front.jpg?v=1737541614',
    images: [
      'https://us.ortlieb.com/cdn/shop/files/productimage-k4651-front.jpg?v=1737541614',
      'https://us.ortlieb.com/cdn/shop/files/productimage-k4651-back.jpg?v=1737541614',
      'https://us.ortlieb.com/cdn/shop/files/productimage-k4651-inside.jpg?v=1737541614',
    ],
    videoUrl: null,
    shortDescription: 'שק אטום Ortlieb PD350 13 ל׳ — PE/PI 350מ"י, עמיד לחבטות. לציוד אלקטרוני, מסמכים ובגדים.',
    description: 'Ortlieb Dry Bag PD350 — קשיח יותר מהדגם הרגיל בזכות PE/PI 350מ"י. עמיד לשפשוף, חבטות וקרעים. מחליק פחות בתוך שק תרמיל. מיוצר בגרמניה. מתאים לציוד יקר: אלקטרוניקה, מסמכים, מצלמות.',
    benefits: [
      'PE/PI 350מ"י — קשיח ועמיד לחבטות',
      'מיוצר בגרמניה — איכות בת-קיימא',
      'מתאים לאלקטרוניקה ומסמכים',
      'אטימה Roll-Top עם קליפס',
    ],
    specs: [
      { label: 'נפח', value: '13 ל׳' },
      { label: 'חומר', value: 'PE/PI 350מ"י' },
      { label: 'אטימה', value: 'Roll-Top + קליפס' },
      { label: 'מדינת ייצור', value: 'גרמניה' },
    ],
    faqs: [
      {
        question: 'מה ה-PD350 לעומת PS10?',
        answer: 'PD350: חומר קשיח יותר (PE/PI) — עמיד לחבטות. PS10: גמיש יותר, קל יותר — לנשיאה. PD350 לציוד יקר, PS10 לבגדים.',
      },
    ],
    seoTitle: 'שק אטום Ortlieb Dry Bag PD350 13 ל׳ | גרמניה | CampIL',
    seoDescription: 'Ortlieb Dry Bag PD350 13L. PE/PI 350מ"י, גרמניה. ₪239.',
    tags: ['שק אטום', 'ORTLIEB', 'PD350', 'ציוד אלקטרוני'],
    relatedSlugs: ['ortlieb-dry-bag-10l', 'sts-ultra-sil-dry-bag-8l', 'sts-hydraulic-dry-bag-20l'],
  },

  /* ── 8. Sea to Summit OPSAK Odor-Proof Bag 2L ────────────────────── */
  {
    id: 'prod-808',
    name: 'שקיות חסינות ריח LOKSAK OPSAK — ממריאות דובים, 2+4 ל׳',
    slug: 'sts-opsak-odor-proof-2l',
    category: 'אחסון וארגון',
    categorySlug: 'storage-organization',
    price: 89,
    originalPrice: 119,
    rating: 4.7,
    reviewCount: 289,
    inStock: true,
    sku: 'LOKSAK-OPSAK-2-4L',
    brand: 'LOKSAK',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://loksak.com/products/opsak',
    image: 'https://loksak.com/wp-content/uploads/2016/12/opsak-header-image.jpg',
    images: [
      'https://loksak.com/wp-content/uploads/2016/12/opsak-header-image.jpg',
      'https://loksak.com/wp-content/uploads/2025/12/feQta5D6.png',
    ],
    videoUrl: null,
    shortDescription: 'שקיות חסינות ריח Sea to Summit OPSAK — ממריאות דובים, חיות ומזיקים. ב-2+4 ל׳. לאחסון מזון ופסולת.',
    description: 'Sea to Summit OPSAK — שקיות ריק-ריח מפלסטיק HDPE 4mil. חוסמות 100% ריחות מזון — מרתיעות דובים, שממיות ומכרסמים. ניתן לחזרה שימוש, לשטיפה. מגיעות בסט 2+4 ל׳ לאחסון מנות שונות.',
    benefits: [
      'חוסמות ריחות 100% — מרתיעות חיות',
      'HDPE 4mil — עמיד ולא מרשים ריחות',
      'לשימוש חוזר — שוטפים ומשתמשים שוב',
      'סט 2+4 ל׳ — לאחסון מנות שונות',
    ],
    specs: [
      { label: 'נפחים', value: '2 ל׳ + 4 ל׳ (בסט)' },
      { label: 'חומר', value: 'HDPE 4mil' },
      { label: 'אטימת ריח', value: '100% (tested)' },
      { label: 'שימוש חוזר', value: 'כן — לשטיפה' },
    ],
    faqs: [
      {
        question: 'מחליפות חבית דוב (bear canister)?',
        answer: 'לא בכל גן לאומי. OPSAK מוכרת לשימוש ב-Ursack בחלק מהגנים — בדקו תקנות ספציפיות לפני הטיול.',
      },
    ],
    seoTitle: 'שקית חסינת ריח Sea to Summit OPSAK | ממריאת דובים | CampIL',
    seoDescription: 'Sea to Summit OPSAK 2+4ל׳. חוסמת ריחות 100%, HDPE 4mil. ₪89.',
    tags: ['שקית חסינת ריח', 'Sea to Summit', 'OPSAK', 'אחסון מזון'],
    relatedSlugs: ['sts-ultra-sil-dry-bag-8l', 'sts-big-river-dry-bag-13l'],
  },

  /* ── 9. Eagle Creek Pack-It Original Cube Set S+M ────────────────── */
  {
    id: 'prod-809',
    name: 'ארגוניות לגיר Eagle Creek Pack-It Original Cube Set — S+M',
    slug: 'eagle-creek-pack-it-cube-set',
    category: 'אחסון וארגון',
    categorySlug: 'storage-organization',
    price: 249,
    originalPrice: 299,
    rating: 4.6,
    reviewCount: 412,
    badge: 'bestseller',
    inStock: true,
    sku: 'EC-ECA0A48S',
    brand: 'Eagle Creek',
    deliveryTime: '7–10 ימי עסקים',
    sourceUrl: 'https://www.eaglecreek.com/products/pack-it-original-cube-set-s-m',
    image: 'https://eaglecreek.com/cdn/shop/files/EC040406_064_a.jpg?v=1751311347',
    images: [
      'https://eaglecreek.com/cdn/shop/files/EC040406_064_a.jpg?v=1751311347',
    ],
    videoUrl: null,
    shortDescription: 'ארגוניות Eagle Creek Pack-It Original Cube S+M — לניהול בגדים ברגיל ובאוהל. 100 גרם לסט, רשת ריח.',
    description: 'Eagle Creek Pack-It Original Cube — קוביות ארגון לבגדים. S (23×32 ס"מ) לחולצות, M (28×38 ס"מ) לג׳ינסים ומכנסיים. רוכסן כפול, פאנל רשת לאוורור. מסדרות את תכולת התרמיל תוך שניות. 100 גרם לסט.',
    benefits: [
      'S+M — מכסות רוב הבגדים לטיול',
      'רשת אוורור — ממזערת ריח בגדים',
      '100 גרם לסט — לא מוסיפות משקל',
      'מוצאים בגדים מיד — לא הופכים תרמיל',
    ],
    specs: [
      { label: 'גדלים', value: 'S: 23×32 ס"מ / M: 28×38 ס"מ' },
      { label: 'חומר', value: 'ניילון 210D + רשת' },
      { label: 'משקל', value: '~100 גרם לסט' },
      { label: 'רוכסן', value: 'YKK כפול' },
    ],
    faqs: [
      {
        question: 'עובדות גם לחכיות וכלי שטח?',
        answer: 'כן — המטיילים שלנו משתמשים בהן לכבלים, כלי אוכל, עדשות ומגהץ שיניים. כל מה שמוצאים מיד.',
      },
    ],
    seoTitle: 'ארגוניות Eagle Creek Pack-It Original Cube S+M | CampIL',
    seoDescription: 'Eagle Creek Pack-It Original S+M. ניילון 210D, 100 גרם, YKK. ₪149.',
    tags: ['ארגוניות', 'Eagle Creek', 'Pack-It', 'בגדים'],
    relatedSlugs: ['sts-ultra-sil-dry-bag-8l', 'sts-evac-compression-dry-bag-8l'],
  },

  /* ── 10. Ortlieb Gear-Pack 25L ───────────────────────────────────── */
  {
    id: 'prod-810',
    name: 'תרמיל אטום Ortlieb Atrack 25 ל׳ — נפתח כמו תיק נסיעה',
    slug: 'ortlieb-gear-pack-25l',
    category: 'אחסון וארגון',
    categorySlug: 'storage-organization',
    price: 1299,
    originalPrice: 1599,
    rating: 4.8,
    reviewCount: 134,
    badge: 'new',
    inStock: true,
    sku: 'ORTLIEB-R7005',
    brand: 'ORTLIEB',
    deliveryTime: '7–10 ימי עסקים',
    sourceUrl: 'https://us.ortlieb.com/products/atrack',
    image: 'https://us.ortlieb.com/cdn/shop/files/productimage-r7005-front.jpg?v=1764346130',
    images: [
      'https://us.ortlieb.com/cdn/shop/files/productimage-r7005-front.jpg?v=1764346130',
      'https://us.ortlieb.com/cdn/shop/files/productimage-r7005-back.jpg?v=1764345997',
      'https://us.ortlieb.com/cdn/shop/files/productimage-r7005-side.jpg?v=1764346001',
    ],
    videoUrl: null,
    shortDescription: 'תרמיל אטום Ortlieb Atrack 25 ל׳ — נפתח לרוחב כמו מזוודה. PU אטום 100%. לאוברלנדינג, טיסות ואוהל.',
    description: 'Ortlieb Atrack 25L — תרמיל אטום ייחודי שנפתח לרוחב כמו תיק נסיעה (לא מלמעלה). גישה מלאה לתכולה. PU אטום 100%. רצועות כתף מרופדות. מיוצר בגרמניה. מתאים לטיסות (carry-on), לאוברלנדינג ולקמפינג עם ציוד יקר.',
    benefits: [
      'פתיחה לרוחב — גישה מלאה לתכולה',
      'PU אטום 100% — שוקע בנהר, יוצא יבש',
      'carry-on — מתאים לתא הכבודה',
      'מיוצר בגרמניה — איכות לחיים',
    ],
    specs: [
      { label: 'נפח', value: '25 ל׳' },
      { label: 'אטימה', value: 'PU 100%' },
      { label: 'פתיחה', value: 'לרוחב (כמו מזוודה)' },
      { label: 'ידיות כתף', value: 'מרופדות ומתכווננות' },
      { label: 'מדינת ייצור', value: 'גרמניה' },
    ],
    faqs: [
      {
        question: 'מה ההבדל מתרמיל רגיל עם הגנת גשם?',
        answer: 'Atrack: אטום 100% — אפשר לשקוע. תרמיל רגיל + מגן גשם: לא מחזיק ספריי אינטנסיבי ולא שקיעה.',
      },
    ],
    seoTitle: 'תרמיל אטום Ortlieb Atrack 25 ל׳ | גרמניה | CampIL',
    seoDescription: 'Ortlieb Atrack 25L, PU אטום, נפתח לרוחב, גרמניה. ₪499.',
    tags: ['תרמיל אטום', 'ORTLIEB', 'Atrack', 'אוברלנדינג'],
    relatedSlugs: ['ortlieb-dry-bag-10l', 'sts-hydraulic-dry-bag-20l', 'ortlieb-dry-bag-pd350-13l'],
  },
];
