import type { Product } from '../types';

export const vehicleTravelProducts: Product[] = [

  /* ── 1. מדפלטורים אוטומטיים (מוצר קיים) ──────────────────────── */
  {
    id: 'prod-003',
    name: 'מדפלטורים אוטומטיים — ערכת 4',
    slug: 'medeflatorm',
    category: 'ציוד לרכבי שטח',
    categorySlug: 'vehicle-gear',
    price: 149,
    originalPrice: 199,
    rating: 4.9,
    reviewCount: 312,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-VEH-001',
    brand: 'ARB',
    deliveryTime: '5–10 ימי עסקים',
    sourceUrl: 'https://store.arbusa.com/e-z-tire-deflator-kit-with-psi-gauge-arb505/',
    image: 'https://cdn11.bigcommerce.com/s-wg9nennc1z/images/stencil/1035x1035/products/11653/13138811/arb-e-z-tire-deflator-psi-gauge-arb505__82265.1749196890.jpg?c=1',
    images: [
      'https://cdn11.bigcommerce.com/s-wg9nennc1z/images/stencil/1035x1035/products/11653/13138811/arb-e-z-tire-deflator-psi-gauge-arb505__82265.1749196890.jpg?c=1',
      'https://cdn11.bigcommerce.com/s-wg9nennc1z/images/stencil/1035x1035/products/11653/13137438/arb-e-z-tire-deflator-psi-gauge-arb505__20973.1749194601.jpg?c=1',
      'https://cdn11.bigcommerce.com/s-wg9nennc1z/images/stencil/1035x1035/products/11653/13136331/arb-e-z-tire-deflator-psi-gauge-arb505__11257.1749193023.jpg?c=1',
      'https://cdn11.bigcommerce.com/s-wg9nennc1z/images/stencil/1035x1035/products/11653/13138664/arb-e-z-tire-deflator-psi-gauge-arb505__11440.1749196647.jpg?c=1',
      'https://cdn11.bigcommerce.com/s-wg9nennc1z/images/stencil/1035x1035/products/11653/13138295/arb-e-z-tire-deflator-psi-gauge-arb505__53096.1749196003.jpg?c=1',
    ],
    videoUrl: null,
    shortDescription: "הורדת לחץ אוטומטית ל-4 צמיגים בו-זמנית. מכווננים מראש ל-18 PSI. לג'ימני, ג'יפ, הילוקס ו-D-Max.",
    description: `יש בדיוק רגע אחד שכל בעל ג'ימני, ג'יפ, הילוקס, או D-Max מכיר: חמש דקות לפני שיוצאים לשטח, שוכבים על הברכיים ומנסים להוריד לחץ מארבעה צמיגים. המדפלטורים פותרים את זה — מחברים ל-4 צמיגים, ממתינים 3–4 דקות, מפסיקים לבד.`,
    benefits: [
      'ל-4 צמיגים בו-זמנית — חוסכים 10 דקות בכל יציאה',
      'מכווננים מראש ל-18 PSI — אידיאלי לשטח ישראלי',
      'מפסיקים לבד בלחץ הנכון',
      'גוף אלומיניום CNC — לא נשבר, לא מחליד',
    ],
    specs: [
      { label: 'חומר', value: 'אלומיניום CNC' },
      { label: 'לחץ מוגדר', value: '18 PSI (ניתן לכיוון)' },
      { label: 'טווח כיוון', value: '10–30 PSI' },
      { label: 'כמות', value: '4 יחידות + נרתיק' },
      { label: 'תאימות', value: 'שסתום Schrader סטנדרטי' },
    ],
    faqs: [
      {
        question: 'אפשר לשנות את ה-PSI?',
        answer: 'כן — פתיחה קלה של הגוף מאפשרת כיוון בין 10 ל-30 PSI.',
      },
    ],
    seoTitle: "מדפלטורים אוטומטיים ערכת 4 | ג'ימני ג'יפ הילוקס | CampIL",
    seoDescription: "מדפלטורים אוטומטיים 4 יח' אלומיניום CNC, 18 PSI מוגדר מראש. ₪149.",
    tags: ['מדפלטורים', 'הורדת לחץ', "ג'ימני", 'שטח ישראל'],
    relatedSlugs: ['air-compressor-12v', 'kinetic-strap-9m'],
  },

  /* ── 2. מדחס אוויר נייד 12V ────────────────────────────────────── */
  {
    id: 'prod-301',
    name: 'מדחס אוויר נייד 12V 150 PSI',
    slug: 'air-compressor-12v',
    category: 'ציוד לרכבי שטח',
    categorySlug: 'vehicle-gear',
    price: 229,
    originalPrice: 299,
    rating: 4.8,
    reviewCount: 241,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-VEH-002',
    brand: 'VIAIR',
    deliveryTime: '5–10 ימי עסקים',
    image: 'https://viaircorp.com/cdn/shop/files/40043-1.jpg?crop=center&height=1200&v=1713388661&width=1200',
    images: [
      'https://viaircorp.com/cdn/shop/files/40043-1.jpg?crop=center&height=1200&v=1713388661&width=1200',
      'https://viaircorp.com/cdn/shop/files/Lifesyle_40043-5.jpg?crop=center&height=1200&v=1713388661&width=1200',
      'https://viaircorp.com/cdn/shop/files/Lifesyle_40043-7.jpg?crop=center&height=1200&v=1713388661&width=1200',
      'https://viaircorp.com/cdn/shop/files/Lifesyle_40043-8.jpg?crop=center&height=1200&v=1713388661&width=1200',
    ],
    videoUrl: null,
    shortDescription: 'מדחס אוויר נייד 12V, עד 150 PSI, 2.3 CFM. מחזיר צמיגי 35" מ-15 ל-30 PSI תוך 2 דקות. עמיד IP54.',
    description: 'מדחס אוויר נייד 12V עם מנוע Direct-Drive חזק. מגיע ל-150 PSI, 2.3 CFM. עמיד IP54 לאבק ומים. כולל צינור 10 מטר, מנוחמר, אינדיקטור LED. מתחבר לסוללת הרכב עם כבלי תנין.',
    benefits: [
      '2.3 CFM — מהיר פי-2 ממדחסים זולים',
      'עמיד IP54 — עובד בשטח אבק ורטיבות',
      '150 PSI — מספיק לכל צמיג רכב שטח',
      'כולל צינור 10 מטר ומנומטר',
    ],
    specs: [
      { label: 'לחץ מקסימלי', value: '150 PSI' },
      { label: 'ספיקה', value: '2.3 CFM' },
      { label: 'חיבור', value: '12V DC (כבלי תנין)' },
      { label: 'עמידות', value: 'IP54' },
      { label: 'משקל', value: '3.2 ק"ג' },
    ],
    faqs: [
      {
        question: 'כמה זמן לוקח למלא צמיג 35" מ-18 ל-34 PSI?',
        answer: 'כ-2 דקות לצמיג — כ-8 דקות ל-4 צמיגים בזה אחר זה. מוסיף אוורור בין צמיגים.',
      },
    ],
    seoTitle: 'מדחס אוויר נייד 12V 150PSI | שטח ואוברלנדינג | CampIL',
    seoDescription: 'מדחס אוויר נייד 12V 150PSI 2.3CFM. IP54, כולל צינור 10מ׳. ₪229.',
    tags: ['מדחס אוויר', 'ציוד שטח', 'אוברלנדינג'],
    relatedSlugs: ['medeflatorm', 'recovery-boards-2pk'],
  },

  /* ── 3. לוחות חילוץ MaxTrax סט 2 ──────────────────────────────── */
  {
    id: 'prod-302',
    name: 'לוחות חילוץ MaxTrax MKII — סט 2',
    slug: 'recovery-boards-2pk',
    category: 'ציוד לרכבי שטח',
    categorySlug: 'vehicle-gear',
    price: 249,
    originalPrice: 329,
    rating: 4.9,
    reviewCount: 178,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-VEH-003',
    brand: 'Maxtrax',
    deliveryTime: '7–14 ימי עסקים',
    image: 'https://americanadventurelab.com/wp-content/uploads/2022/03/maxtrax-mkii-orange-traction-recovery-boards-1158x800.jpg',
    images: [
      'https://americanadventurelab.com/wp-content/uploads/2022/03/maxtrax-mkii-orange-traction-recovery-boards-1158x800.jpg',
      'https://www.rhinoadventuregear.com/cdn/shop/products/maxtrax-rugged-teeth.jpeg?v=1618517256',
      'https://www.rhinoadventuregear.com/cdn/shop/products/maxtrax-recovery-board-sand.jpeg?v=1618517256',
    ],
    videoUrl: null,
    shortDescription: 'לוחות חילוץ MaxTrax MKII מניילון מחוזק, 3.4 ק"ג כל לוח. לחילוץ עצמי מחול, בוץ ושלג. עיצוב אוסטרלי מקורי.',
    description: 'לוחות חילוץ MaxTrax MKII מניילון מחוזק UV-stabilized. השיניים הייחודיות מספקות אחיזה מרבית בחול, בוץ ושלג. 3.4 ק"ג לכל לוח. מאושר על ידי צבאות ושירותי חירום ברחבי העולם.',
    benefits: [
      'MaxTrax המקורי — לא כפל, לא זיוף',
      'ניילון מחוזק UV — עמיד לשמש ישראלית',
      'שיניים ייחודיות — אחיזה בחול, בוץ, שלג',
      'קל מספיק לנשיאה על גג הרכב',
    ],
    specs: [
      { label: 'חומר', value: 'ניילון מחוזק UV-stabilized' },
      { label: 'משקל לכל לוח', value: '3.4 ק"ג' },
      { label: 'ממדים', value: '119 × 33 × 4.8 ס"מ' },
      { label: 'עומס מקסימלי', value: '4 טון לרכב' },
      { label: 'כמות', value: '2 לוחות' },
    ],
    faqs: [
      {
        question: 'עובדים בחול הנגב?',
        answer: 'כן — MaxTrax פותחו במיוחד לחול. עובדים היטב בנגב ובמדבר יהודה.',
      },
    ],
    seoTitle: 'לוחות חילוץ MaxTrax MKII סט 2 | חול ובוץ | CampIL',
    seoDescription: 'לוחות חילוץ MaxTrax MKII ניילון מחוזק, 3.4 ק"ג, עומס 4 טון. ₪249.',
    tags: ['לוחות חילוץ', 'MaxTrax', 'שטח ישראל', 'חילוץ'],
    relatedSlugs: ['kinetic-strap-9m', 'air-compressor-12v', 'hi-lift-jack-48'],
  },

  /* ── 4. רצועת חילוץ קינטית 9 מ׳ ───────────────────────────────── */
  {
    id: 'prod-303',
    name: 'רצועת חילוץ קינטית ARB 8 טון — 9 מ׳',
    slug: 'kinetic-strap-9m',
    category: 'ציוד לרכבי שטח',
    categorySlug: 'vehicle-gear',
    price: 99,
    originalPrice: 139,
    rating: 4.8,
    reviewCount: 134,
    inStock: true,
    sku: 'CAMP-VEH-004',
    brand: 'ARB',
    deliveryTime: '5–10 ימי עסקים',
    image: 'https://s7ap1.scene7.com/is/image/arbprod/ARB710_v2.jpg',
    images: [
      'https://s7ap1.scene7.com/is/image/arbprod/ARB710_v2.jpg',
    ],
    videoUrl: null,
    shortDescription: 'רצועת חילוץ קינטית ARB 9 מ׳ עם עומס שבירה 8 טון. ניילון קינטי שסופג הלם. לחילוץ ע"י רכב שני.',
    description: 'רצועת חילוץ קינטית ARB מניילון קינטי מתמתח — סופגת אנרגיית חילוץ ולא קורעת. אורך 9 מ׳, עומס שבירה 8 טון. כולל שקית אחסון. תוצרת ניילון קינטי MBS 8,000 ק"ג.',
    benefits: [
      'ניילון קינטי — מתמתח ולא קורע בעת חילוץ',
      'עומס שבירה 8 טון — לרכבי שטח כבדים',
      '9 מ׳ — מרחק בטוח בין הרכבים',
      'כולל שקית אחסון',
    ],
    specs: [
      { label: 'אורך', value: '9 מטר' },
      { label: 'עומס שבירה', value: '8 טון (MBS 8,000 ק"ג)' },
      { label: 'חומר', value: 'ניילון קינטי' },
      { label: 'קצוות', value: 'לולאות מחוזקות × 2' },
    ],
    faqs: [
      {
        question: 'מה ההבדל בין רצועה קינטית לכבל חילוץ?',
        answer: 'רצועה קינטית מתמתחת ב-20% ומשחררת אנרגיה — מחלצת בעדינות. כבל פלדה קורע בבת אחת ומסוכן.',
      },
    ],
    seoTitle: 'רצועת חילוץ קינטית ARB 9 מ׳ | 8 טון | CampIL',
    seoDescription: 'רצועת חילוץ קינטית ARB 9 מ׳, 8 טון. ניילון קינטי, לולאות מחוזקות. ₪99.',
    tags: ['רצועת חילוץ', 'ציוד שטח', 'חילוץ ARB'],
    relatedSlugs: ['recovery-boards-2pk', 'hi-lift-jack-48'],
  },

  /* ── 5. ג'ק Hi-Lift 48 אינץ' ───────────────────────────────────── */
  {
    id: 'prod-304',
    name: 'ג\'ק שטח Hi-Lift Cast/Steel 48 אינץ\'',
    slug: 'hi-lift-jack-48',
    category: 'ציוד לרכבי שטח',
    categorySlug: 'vehicle-gear',
    price: 199,
    originalPrice: 269,
    rating: 4.8,
    reviewCount: 156,
    badge: 'new',
    inStock: true,
    sku: 'CAMP-VEH-005',
    brand: 'Hi-Lift',
    deliveryTime: '5–10 ימי עסקים',
    image: 'https://hi-lift.com/wp-content/uploads/2020/01/hl-484-product-1024x1024.jpg',
    images: [
      'https://hi-lift.com/wp-content/uploads/2020/01/hl-484-product-1024x1024.jpg',
      'https://hi-lift.com/wp-content/uploads/2016/07/4J7A0174-e1474027241720-1024x492.jpg',
      'https://hi-lift.com/wp-content/uploads/2016/07/HL-Lift-880x1024.jpg',
    ],
    videoUrl: null,
    shortDescription: 'ג\'ק שטח Hi-Lift 48 אינץ\' ברזל יצוק. מרים עד 3 טון, גם כציר ומחלץ. ציוד חובה לכל רכב שטח.',
    description: 'ג\'ק Hi-Lift המקורי Cast/Steel 48 אינץ\' — ציוד חובה לכל רכב שטח. גוף ברזל יצוק, מרים עד 3 טון, גובה הרמה 122 ס"מ. שימושים: הרמה לחילוץ, ציר וינץ\', הזזת רכב. מוצר מקורי Hi-Lift ארה"ב.',
    benefits: [
      'Hi-Lift המקורי — יוצר בארה"ב מ-1905',
      'ברזל יצוק — עמיד לתנאי שטח קשים',
      '3 שימושים: הרמה, ציר, וינץ\'',
      'גובה הרמה 122 ס"מ — מחלץ גם מחפרים עמוקים',
    ],
    specs: [
      { label: 'אורך', value: '48 אינץ\' (122 ס"מ)' },
      { label: 'עומס מקסימלי', value: '3 טון' },
      { label: 'גובה הרמה', value: '0–122 ס"מ' },
      { label: 'חומר', value: 'ברזל יצוק + פלדה' },
      { label: 'משקל', value: '7.7 ק"ג' },
    ],
    faqs: [
      {
        question: 'האם עובד על כל רכב שטח?',
        answer: 'כן — אבל הרכב חייב לקרש שדה או נקודת הרמה קשיחה. לא מתאים לרכבים עם פגוש פלסטיק בלבד.',
      },
    ],
    seoTitle: "ג'ק שטח Hi-Lift 48 אינץ' | 3 טון | CampIL",
    seoDescription: `ג'ק Hi-Lift Cast/Steel 48 אינץ', 3 טון, גובה 122 ס"מ. ציוד חובה לשטח. ₪199.`,
    tags: ["ג'ק שטח", 'Hi-Lift', 'חילוץ', 'ציוד שטח'],
    relatedSlugs: ['kinetic-strap-9m', 'recovery-boards-2pk'],
  },

  /* ── 6. מקרר/מקפיא נייד 12V 36 ל׳ ────────────────────────────── */
  {
    id: 'prod-305',
    name: 'מקרר נייד Dometic CFX3 12V — 36 ל׳',
    slug: 'car-fridge-12v-40l',
    category: 'ציוד לרכבי שטח',
    categorySlug: 'vehicle-gear',
    price: 549,
    originalPrice: 699,
    rating: 4.9,
    reviewCount: 89,
    badge: 'new',
    inStock: true,
    sku: 'CAMP-VEH-006',
    brand: 'Dometic',
    deliveryTime: '7–10 ימי עסקים',
    image: 'https://www.dometic.com/media/catalog/product/cache/5e86c224dde0af116b83ea127ee979a6/9/6/96794-primary_1.png',
    images: [
      'https://www.dometic.com/media/catalog/product/cache/5e86c224dde0af116b83ea127ee979a6/9/6/96794-primary_1.png',
      'https://www.dometic.com/media/catalog/product/cache/5e86c224dde0af116b83ea127ee979a6/9/3/93483_1.jpg',
      'https://www.dometic.com/media/catalog/product/cache/5e86c224dde0af116b83ea127ee979a6/9/7/97668_1.png',
    ],
    videoUrl: null,
    shortDescription: 'מקרר/מקפיא נייד Dometic CFX3 36 ל׳. עובד על 12V/24V/220V. מגיע ל-18°C מתחת לאפס. אפליקציה לשליטה מרחוק.',
    description: 'מקרר Dometic CFX3 36 ל׳ — המקרר הנייד המוביל בשוק. מקרר ומקפיא בו-זמנית, עובד על 12V/24V ו-220V, מגיע ל-18°C מתחת לאפס. הגנת סוללה 3 שלבים. אפליקציה לניטור וכיוון מרחוק.',
    benefits: [
      'מקרר + מקפיא — ב-36 ל׳ אחד',
      '12V/24V/220V — ברכב, בסוללה ובביתן',
      'עד 18°C מתחת לאפס — קרח אמיתי בשטח',
      'אפליקציה לניטור טמפרטורה מרחוק',
    ],
    specs: [
      { label: 'נפח', value: '36 ל׳' },
      { label: 'טמפרטורה', value: '-18°C עד +20°C' },
      { label: 'חיבור', value: '12V / 24V DC + 100-240V AC' },
      { label: 'צריכת חשמל', value: '45W ממוצע' },
      { label: 'משקל', value: '16.5 ק"ג' },
    ],
    faqs: [
      {
        question: 'כמה זמן מחזיק על סוללת 100Ah?',
        answer: 'כ-25–35 שעות בטמפרטורת קירור רגילה (4°C), תלוי בטמפרטורת הסביבה ובהצללה.',
      },
    ],
    seoTitle: 'מקרר נייד Dometic CFX3 12V 36 ל׳ | מקפיא | CampIL',
    seoDescription: 'מקרר נייד Dometic CFX3 36 ל׳. 12V/220V, מקפיא -18°C, אפליקציה. ₪549.',
    tags: ['מקרר נייד', 'Dometic', 'ציוד שטח', 'אוברלנדינג'],
    relatedSlugs: ['air-compressor-12v', 'medeflatorm'],
  },

  /* ── 7. מד לחץ צמיגים דיגיטלי ─────────────────────────────────── */
  {
    id: 'prod-306',
    name: 'מד לחץ צמיגים דיגיטלי 150 PSI',
    slug: 'tire-gauge-digital',
    category: 'ציוד לרכבי שטח',
    categorySlug: 'vehicle-gear',
    price: 49,
    originalPrice: 69,
    rating: 4.6,
    reviewCount: 892,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-VEH-007',
    brand: 'AstroAI',
    deliveryTime: '5–10 ימי עסקים',
    image: 'https://cdn.astroai.com/cdn-cgi/image/format=webp,width=602,quality=,dpr=/astroai-banner/product/1d49a99c-6da8-ec91-c92d-5c6b6cf0c4c2_20250121.webp',
    images: [
      'https://cdn.astroai.com/cdn-cgi/image/format=webp,width=602,quality=,dpr=/astroai-banner/product/1d49a99c-6da8-ec91-c92d-5c6b6cf0c4c2_20250121.webp',
      'https://cdn.astroai.com/cdn-cgi/image/format=webp,width=1440,quality=,dpr=/astroai-banner/product/b38d6703-82fc-4da4-8c44-955f524acbd7_20240905.webp',
      'https://cdn.astroai.com/cdn-cgi/image/format=webp,width=1440,quality=,dpr=/astroai-banner/product/4efe1118-4218-6131-7bb5-3c3a3c115ceb_20240905.webp',
    ],
    videoUrl: null,
    shortDescription: 'מד לחץ צמיגים דיגיטלי 0–150 PSI. תצוגת LCD מוארת, דיוק ±1 PSI, 4 יחידות מדידה. כולל סוללה.',
    description: 'מד לחץ צמיגים דיגיטלי עם תצוגת LCD מוארת לקריאה בלילה ובחושך. דיוק ±1 PSI, 4 יחידות: PSI, kPa, Bar, kgf/cm². כיבוי אוטומטי בחיסכון בסוללה. תואם לכל שסתומי Schrader.',
    benefits: [
      'דיוק ±1 PSI — מדויק יותר ממד אנלוגי',
      'תצוגת LCD מוארת — קריאה בחושך',
      '4 יחידות מדידה לבחירה',
      'כיבוי אוטומטי לחיסכון בסוללה',
    ],
    specs: [
      { label: 'טווח מדידה', value: '0–150 PSI' },
      { label: 'דיוק', value: '±1 PSI' },
      { label: 'יחידות', value: 'PSI / kPa / Bar / kgf/cm²' },
      { label: 'תאורת LCD', value: 'כן' },
      { label: 'סוללה', value: 'AAA × 2 (כלולה)' },
    ],
    faqs: [
      {
        question: 'עובד לצמיגי 4×4 עם לחץ גבוה?',
        answer: 'כן — טווח 0-150 PSI מכסה גם צמיגי משאיות וג\'יפים בלחץ גבוה.',
      },
    ],
    seoTitle: 'מד לחץ צמיגים דיגיטלי 150 PSI | LCD | CampIL',
    seoDescription: 'מד לחץ צמיגים דיגיטלי 0-150 PSI, LCD מואר, ±1 PSI. ₪49.',
    tags: ['מד לחץ צמיגים', 'ציוד רכב', 'אוברלנדינג'],
    relatedSlugs: ['medeflatorm', 'air-compressor-12v'],
  },

  /* ── 8. רצועות הידוק Ratchet ערכת 4 ───────────────────────────── */
  {
    id: 'prod-307',
    name: 'רצועות הידוק Ratchet 500 ק"ג — ערכת 4',
    slug: 'ratchet-straps-4pk',
    category: 'ציוד לרכבי שטח',
    categorySlug: 'vehicle-gear',
    price: 79,
    originalPrice: 109,
    rating: 4.7,
    reviewCount: 445,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-VEH-008',
    brand: 'Rhino USA',
    deliveryTime: '5–10 ימי עסקים',
    image: 'https://www.rhinousainc.com/cdn/shop/files/hd-ratchetkit-4pk.main.jpg?v=1739980133',
    images: [
      'https://www.rhinousainc.com/cdn/shop/files/hd-ratchetkit-4pk.main.jpg?v=1739980133',
      'https://www.rhinousainc.com/cdn/shop/files/td-gc1.6x15-blk.01_4fe9901c-9021-40e8-a854-3e1f7cb49907.jpg?v=1739980133',
      'https://www.rhinousainc.com/cdn/shop/files/td-gc1.6x15-blk.02_f34cd9e1-f843-4ec7-ab27-a8818e660796.jpg?v=1739980133',
      'https://www.rhinousainc.com/cdn/shop/files/td-gc1.6x15-blk.03_0fd535ec-3409-40f7-ace0-06c5cd5a0cf9.jpg?v=1739980133',
    ],
    videoUrl: null,
    shortDescription: 'ערכת 4 רצועות הידוק Ratchet 4.5 מ׳, עוצמת שבירה 500 ק"ג. לאבטחת ציוד על גג, טריילר ומשאית.',
    description: 'ערכת 4 רצועות הידוק Ratchet מנירוסטה + פוליאסטר. אורך 4.5 מ׳ ליחידה, עוצמת שבירה 500 ק"ג (כ"א). ווים J-Hook, מנגנון Ratchet נוח להדקה ולשחרור. כולל שקית אחסון.',
    benefits: [
      '500 ק"ג לרצועה — לציוד כבד על גג ומוביל',
      'ווים J-Hook — מתחברים לכל מסגרת',
      'מנגנון Ratchet — הידוק בלי מאמץ',
      'ערכת 4 עם שקית אחסון',
    ],
    specs: [
      { label: 'עוצמת שבירה', value: '500 ק"ג לרצועה' },
      { label: 'אורך', value: '4.5 מ׳ × 4' },
      { label: 'רוחב', value: '2.5 ס"מ' },
      { label: 'חיבור', value: 'J-Hook' },
      { label: 'חומר', value: 'פוליאסטר + מנגנון מתכת' },
    ],
    faqs: [
      {
        question: 'מתאים לגג של SUV?',
        answer: 'כן — עובד עם כל רכות גג או גג ישיר. הווים J-Hook מתחברים לסורג, למוביל ולמשאית.',
      },
    ],
    seoTitle: 'רצועות הידוק Ratchet 500 ק"ג ערכת 4 | CampIL',
    seoDescription: 'ערכת 4 רצועות Ratchet 4.5מ׳, 500 ק"ג, J-Hook. לגג ומוביל. ₪79.',
    tags: ['רצועות הידוק', 'ציוד רכב', 'אחסון גג'],
    relatedSlugs: ['roof-bag-cargo', 'ratchet-straps-4pk'],
  },

  /* ── 9. ערכת חירום לרכב ────────────────────────────────────────── */
  {
    id: 'prod-308',
    name: 'ערכת חירום לרכב 60 חלקים',
    slug: 'emergency-car-kit',
    category: 'ציוד לרכבי שטח',
    categorySlug: 'vehicle-gear',
    price: 89,
    originalPrice: 129,
    rating: 4.7,
    reviewCount: 334,
    badge: 'new',
    inStock: true,
    sku: 'CAMP-VEH-009',
    brand: 'Thrive',
    deliveryTime: '5–10 ימי עסקים',
    image: 'https://thrivebrandproducts.com/cdn/shop/files/Heroooooo_large.jpg?v=1727354931',
    images: [
      'https://thrivebrandproducts.com/cdn/shop/files/Heroooooo_large.jpg?v=1727354931',
      'https://thrivebrandproducts.com/cdn/shop/files/Heroooo_large.jpg?v=1727354931',
      'https://thrivebrandproducts.com/cdn/shop/files/2_large.jpg?v=1727355652',
      'https://thrivebrandproducts.com/cdn/shop/files/81GGjnPJXDL._AC_SL1500_large.jpg?v=1727355651',
    ],
    videoUrl: null,
    shortDescription: 'ערכת חירום לרכב 60 חלקים: כבלי טעינה, משולשי אזהרה, פנס, חגורת בטיחות, עזרה ראשונה ועוד.',
    description: 'ערכת חירום מלאה לרכב — 60 פריטים בתיק פטנט קומפקטי. כוללת: כבלי טעינה 3.5 מ׳, 2 משולשי אזהרה מחזירי אור, פנס LED, גלגל עזרה ראשונה 22 פריטים, קאטר חגורת בטיחות, חלון שבר ועוד.',
    benefits: [
      '60 פריטים — כל מה שצריך לתקרית בכביש',
      'כבלי טעינה 3.5 מ׳ — מגיעים לכל חיבור סוללה',
      'תיק פטנט קומפקטי — נכנס לתא כפפות',
      'ערכת עזרה ראשונה 22 פריטים כלולה',
    ],
    specs: [
      { label: 'כמות פריטים', value: '60' },
      { label: 'כבלי טעינה', value: '3.5 מ׳ / 400A' },
      { label: 'משולשי אזהרה', value: '2 (מחזירי אור)' },
      { label: 'ערכת עזרה ראשונה', value: '22 פריטים' },
      { label: 'נרתיק', value: 'תיק רוכסן קומפקטי' },
    ],
    faqs: [
      {
        question: 'מה כולל ערכת העזרה ראשונה?',
        answer: 'גזה, פלסטרים, נייר עטיפה, חוסם עורקים, גלגל חבינה, ועוד 17 פריטים.',
      },
    ],
    seoTitle: 'ערכת חירום לרכב 60 חלקים | כבלי טעינה | CampIL',
    seoDescription: 'ערכת חירום לרכב 60 פריטים. כבלי טעינה, משולשים, עזרה ראשונה. ₪89.',
    tags: ['ערכת חירום', 'ציוד רכב', 'בטיחות דרכים'],
    relatedSlugs: ['medeflatorm', 'tire-gauge-digital'],
  },

  /* ── 10. מצלמת דרכים 4K GPS ────────────────────────────────────── */
  {
    id: 'prod-309',
    name: 'מצלמת דרכים Vantrue N4 Pro 4K GPS',
    slug: 'dashcam-4k-gps',
    category: 'ציוד לרכבי שטח',
    categorySlug: 'vehicle-gear',
    price: 249,
    originalPrice: 329,
    rating: 4.8,
    reviewCount: 267,
    badge: 'new',
    inStock: true,
    sku: 'CAMP-VEH-010',
    brand: 'Vantrue',
    deliveryTime: '5–10 ימי עסקים',
    image: 'https://www.vantrue.com/cdn/shop/files/74b96dbb2d19db9758ba306fc55ad040.jpg?v=1739004862&width=1600',
    images: [
      'https://www.vantrue.com/cdn/shop/files/74b96dbb2d19db9758ba306fc55ad040.jpg?v=1739004862&width=1600',
      'https://www.vantrue.com/cdn/shop/files/N4Pro-2.jpg?v=1739004862&width=1600',
      'https://www.vantrue.com/cdn/shop/files/B1_dc688242-c0d4-4ced-9331-c0e97bba2de2.jpg?v=1739004862&width=1200',
      'https://www.vantrue.com/cdn/shop/files/fea6243fecb39d591aabb70723cc4062.jpg?v=1739004862&width=1200',
    ],
    videoUrl: null,
    shortDescription: 'מצלמת דרכים Vantrue N4 Pro 4K+1080P. 3 עדשות: קדמי, פנימי ואחורי. GPS, WiFi, ראיית לילה STARVIS 2.',
    description: 'מצלמת דרכים Vantrue N4 Pro עם 3 ערוצי הקלטה: קדמי 4K, פנימי 1080P, אחורי 1080P. חיישן Sony STARVIS 2 לראיית לילה. GPS מובנה, WiFi, מצב חניה 24/7. תואמת כרטיס SD עד 256GB.',
    benefits: [
      '4K קדמי — פרטי לוחית רישוי ברורים',
      '3 עדשות — קדמי, פנימי ואחורי בו-זמנית',
      'Sony STARVIS 2 — ראיית לילה מצוינת',
      'GPS + WiFi — מיקום ומשיכה לסמארטפון',
    ],
    specs: [
      { label: 'רזולוציה קדמי', value: '4K 3840×2160' },
      { label: 'רזולוציה פנימי/אחורי', value: '1080P × 2' },
      { label: 'חיישן', value: 'Sony STARVIS 2 IMX678' },
      { label: 'זווית קדמי', value: '170°' },
      { label: 'חיבור', value: 'WiFi 5GHz / GPS מובנה' },
    ],
    faqs: [
      {
        question: 'כמה זיכרון צריך?',
        answer: 'מינימום 64GB SD. מומלץ 128GB לנסיעות ארוכות. תואם UHS-I Class 10 ומעלה.',
      },
    ],
    seoTitle: 'מצלמת דרכים Vantrue N4 Pro 4K GPS | 3 עדשות | CampIL',
    seoDescription: 'מצלמת דרכים Vantrue N4 Pro 4K, 3 עדשות, STARVIS 2, GPS/WiFi. ₪249.',
    tags: ['מצלמת דרכים', 'דשקם', 'ציוד רכב', '4K'],
    relatedSlugs: ['usb-car-adapter', 'emergency-car-kit'],
  },

  /* ── 11. סל גג Yakima LoadWarrior ──────────────────────────────── */
  {
    id: 'prod-310',
    name: 'סל גג Yakima LoadWarrior — 43×43 אינץ׳',
    slug: 'roof-bag-cargo',
    category: 'ציוד לרכבי שטח',
    categorySlug: 'vehicle-gear',
    price: 349,
    originalPrice: 449,
    rating: 4.8,
    reviewCount: 214,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-VEH-011',
    brand: 'Yakima',
    deliveryTime: '7–10 ימי עסקים',
    sourceUrl: 'https://yakima.com/products/loadwarrior',
    image: 'https://yakima.com/cdn/shop/files/09462252-265d-4984-8e94-314fd9abae1c_300x300.png?v=1743016367',
    images: [
      'https://yakima.com/cdn/shop/files/09462252-265d-4984-8e94-314fd9abae1c_300x300.png?v=1743016367',
      'https://yakima.com/cdn/shop/files/dedd7f40-a87e-49d4-884a-4fd3f2dba30c_300x300.png?v=1718143272',
      'https://yakima.com/cdn/shop/files/c3577907-cede-49e9-a004-e5050ed97b7a_300x300.png?v=1718143275',
      'https://yakima.com/cdn/shop/files/eeeab6a1-1862-4a5b-b908-8f84b0cab3a6_300x300.png?v=1718143278',
      'https://yakima.com/cdn/shop/files/88cc7e1c-3a08-4e0b-aeee-4911549e3633_300x300.png?v=1718143281',
    ],
    videoUrl: null,
    shortDescription: 'סל גג Yakima LoadWarrior 43×43 אינץ׳. מסגרת פלדה, אגד SKS כלול. נושא קיאקים, אופניים, מזוודות וציוד מחנאות.',
    description: 'Yakima LoadWarrior — סל הגג הכי נמכר בארה"ב לרכבי שטח ו-SUV. מסגרת פלדה תעשייתית, שטח עומס 43×43 אינץ׳. מתכוון עם מוטות SKS לכל גרוף גג סטנדרטי. אידיאלי לקיאקים, אופניים, בגז, תיבות, ולוחות גלישה. ₪349.',
    benefits: [
      'מסגרת פלדה — לא פלסטיק, לא מתעקם',
      '43×43 אינץ׳ — מספיק לכל ציוד מחנאות',
      'SKS כלול — תואם Yakima, Thule ורוב הגרופים',
      'גובה 6 אינץ׳ — מחזיק עומס בצורה יציבה',
    ],
    specs: [
      { label: 'ממדים', value: '43 × 43 אינץ׳ (109 × 109 ס"מ)' },
      { label: 'גובה דפנות', value: '6 אינץ׳ (15 ס"מ)' },
      { label: 'חומר', value: 'פלדה מגולוונת' },
      { label: 'עומס מקסימלי', value: '150 ל"ב (68 ק"ג) דינמי' },
      { label: 'תאימות', value: 'כל מוטות גג סטנדרטיים + SKS כלול' },
    ],
    faqs: [
      {
        question: 'מתאים לכל רכב?',
        answer: 'כן — עם ערכת SKS כלולה, מתאים לכל מוטות גג סטנדרטיים: Yakima, Thule, Rhino, ועוד.',
      },
      {
        question: 'אפשר להוסיף אביזרים?',
        answer: 'כן — LoadWarrior תואם לכל אביזרי Yakima: RocketBox, FrontLoader, SkyBox ועוד.',
      },
    ],
    seoTitle: 'סל גג Yakima LoadWarrior 43×43 אינץ׳ | פלדה | CampIL',
    seoDescription: 'סל גג Yakima LoadWarrior, פלדה, 43×43 אינץ׳, 68 ק"ג. SKS כלול. ₪349.',
    tags: ['סל גג', 'Yakima', 'ציוד רכב', 'גרוף גג'],
    relatedSlugs: ['ratchet-straps-4pk', 'dashcam-4k-gps'],
  },

  /* ── 12. מטען USB לרכב 3 יציאות ────────────────────────────────── */
  {
    id: 'prod-311',
    name: 'מטען USB-C לרכב Anker 3 יציאות 167W',
    slug: 'usb-car-adapter',
    category: 'ציוד לרכבי שטח',
    categorySlug: 'vehicle-gear',
    price: 59,
    originalPrice: 89,
    rating: 4.8,
    reviewCount: 671,
    badge: 'bestseller',
    inStock: true,
    sku: 'CAMP-VEH-012',
    brand: 'Anker',
    deliveryTime: '5–10 ימי עסקים',
    image: 'https://cdn.shopify.com/s/files/1/0493/9834/9974/files/B27370A1_29c0ef29-c680-457e-b009-50e4e1d53a03_1600x.png?v=1728527108',
    images: [
      'https://cdn.shopify.com/s/files/1/0493/9834/9974/files/B27370A1_29c0ef29-c680-457e-b009-50e4e1d53a03_1600x.png?v=1728527108',
      'https://cdn.shopify.com/s/files/1/0493/9834/9974/files/B27370A1_Richimage_TD02_US_V1_1600x.jpg?v=1725346829',
      'https://cdn.shopify.com/s/files/1/0493/9834/9974/files/B27370A1_Richimage_TD03_US_V1_1600x.jpg?v=1725346830',
      'https://cdn.shopify.com/s/files/1/0493/9834/9974/files/B27370A1_Richimage_TD04_US_V1_1600x.jpg?v=1725346830',
    ],
    videoUrl: null,
    shortDescription: 'מטען USB-C לרכב Anker 3 יציאות, עד 167W כולל. USB-C A×2 + USB-A. PPS, PD 3.1. נכנס לשקע הסיגריות.',
    description: 'מטען Anker Nano 3 יציאות לרכב. 100W ביציאת USB-C הראשית, 30W בשנייה ו-22.5W ב-USB-A. תואם PD 3.1, PPS, Apple Fast Charge, Samsung Super Fast Charge. קומפקטי — לא חוסם יציאות אחרות.',
    benefits: [
      '167W כולל — טוען לפטופ, iPad וטלפון בו-זמנית',
      '100W ביציאה ראשית — מטען מחשב נייד',
      'קומפקטי — לא חוסם שקעים סמוכים',
      'תואם לכל פרוטוקולי טעינה מהירה',
    ],
    specs: [
      { label: 'יציאה 1 (USB-C)', value: '100W PD 3.1' },
      { label: 'יציאה 2 (USB-C)', value: '30W PD' },
      { label: 'יציאה 3 (USB-A)', value: '22.5W SFC' },
      { label: 'כולל', value: '167W' },
      { label: 'חיבור', value: 'שקע סיגריות 12V/24V' },
    ],
    faqs: [
      {
        question: 'טוען מחשב נייד?',
        answer: 'כן — 100W ביציאה הראשית מספיק לרוב המחשבים הניידים (MacBook Pro, Dell, Lenovo).',
      },
    ],
    seoTitle: 'מטען USB-C לרכב Anker 3 יציאות 167W | CampIL',
    seoDescription: 'מטען Anker לרכב 3 יציאות 167W. USB-C 100W, PD 3.1. ₪59.',
    tags: ['מטען רכב', 'USB-C', 'טעינה מהירה', 'ציוד רכב'],
    relatedSlugs: ['dashcam-4k-gps', 'emergency-car-kit'],
  },
];
