import type { Product, Category } from './types';

export const categories: Category[] = [
  { id:'cat-1', name:'Camp Kitchen',          slug:'camp-kitchen',          description:'Cook like a pro wherever the trail takes you.',                    productCount:2, icon:'utensils', accentColor:'#D6C2A1' },
  { id:'cat-2', name:'Lighting',              slug:'lighting',              description:'Illuminate every campsite with reliable off-grid lighting.',        productCount:2, icon:'zap',      accentColor:'#F5D76E' },
  { id:'cat-3', name:'Vehicle Gear',          slug:'vehicle-gear',          description:'Equip your rig for the toughest overland missions.',                productCount:2, icon:'truck',    accentColor:'#B8D4C8' },
  { id:'cat-4', name:'Sleeping',              slug:'sleeping',              description:'Rest deep and wake ready. Sleep systems for every condition.',       productCount:1, icon:'moon',     accentColor:'#C8B8D4' },
  { id:'cat-5', name:'Water & Shower',        slug:'water-shower',          description:'Stay clean and hydrated anywhere on the trail.',                    productCount:1, icon:'droplets', accentColor:'#B8D0D4' },
  { id:'cat-6', name:'Storage & Organization',slug:'storage-organization',  description:'Keep your camp and vehicle mission-ready at all times.',            productCount:2, icon:'package',  accentColor:'#D4C8B8' },
];

export const products: Product[] = [

  /* ─── 1. Portable Camping Shower ──────────────── */
  {
    id: 'prod-001',
    name: 'Portable Camping Shower',
    slug: 'portable-camping-shower',
    category: 'Water & Shower',
    categorySlug: 'water-shower',
    price: 89.99,
    originalPrice: 119.99,
    rating: 4.8,
    reviewCount: 342,
    badge: 'bestseller',
    shortDescription: '20-litre solar-heated pressure shower with a reinforced hose, adjustable head, and integrated thermometer. Hot water in 3 hours — anywhere.',
    description: `The TrailNest Portable Camping Shower turns any backcountry site into a fully functional wash station. Fill the 20L heavy-duty PVC bag, lay it in direct sunlight, and the integrated solar heating panel brings water to a comfortable shower temperature in as little as 3 hours. A high-flow pressure pump delivers consistent water pressure without batteries, and the adjustable multi-mode showerhead lets you switch between mist, spray, and full flow on demand.\n\nBuilt for the demands of overlanding, the bag features double-sealed seams, a UV-stabilised exterior that resists cracking and fading, and a heavy-duty brass tap that won't strip after a season of hard use. The 1.5 m reinforced hose stores inside the bag for compact packing, and the integrated temperature gauge tells you exactly when your shower is ready.`,
    benefits: [
      '20L capacity — enough for two full showers',
      'Solar heating reaches 45°C in ~3 hours of sun',
      'High-flow pump — no electricity or batteries required',
      'Adjustable showerhead: mist, spray, full flow',
      'Double-sealed seams — leak-proof guaranteed',
      'Integrated temperature gauge for comfort accuracy',
      'Compact folded size fits inside any roof box or overlanding drawer',
    ],
    specs: [
      { label: 'Capacity',         value: '20 Litres' },
      { label: 'Material',         value: 'Heavy-duty PVC, UV-stabilised' },
      { label: 'Hose length',      value: '1.5 m reinforced' },
      { label: 'Pump type',        value: 'Manual high-flow pressure pump' },
      { label: 'Heating method',   value: 'Solar (integrated black absorber panel)' },
      { label: 'Max water temp',   value: '45°C' },
      { label: 'Packed dimensions',value: '40 × 28 × 4 cm' },
      { label: 'Weight',           value: '620 g (empty)' },
      { label: 'Flow rate',        value: '6–8 L/min' },
      { label: 'Showerhead modes', value: 'Mist / Spray / Full Flow' },
    ],
    faqs: [
      { question:'How long does it take to heat up?', answer:'In direct summer sun, the water reaches a comfortable 35–42°C in approximately 2.5–3 hours. Overcast conditions may extend this to 5–6 hours.' },
      { question:'Can I use it in cold climates?', answer:'Yes. In colder climates simply allow extra heating time, or pour pre-heated water in before use. The double-sealed bag retains heat well once warmed.' },
      { question:'Does the bag hang easily from a tree or roof rack?', answer:'Absolutely. The reinforced hanging loop is rated to 25 kg and works with any hook, carabiner, or roof-rack rung.' },
      { question:'Is it suitable for kids?', answer:'Yes. The adjustable showerhead and temperature gauge make it safe and easy for children to use under adult supervision.' },
      { question:'How do I clean and store it?', answer:'Rinse with clean water after each use, partially inflate with air to dry, then fold flat for storage. Avoid storing with stagnant water inside.' },
    ],
    seoTitle: 'Portable Camping Shower 20L Solar Heated | TrailNest',
    seoDescription: 'Hot showers anywhere off-grid. The TrailNest 20L Portable Camping Shower heats solar to 45°C in 3 hours, features a high-flow pump and adjustable head. Free shipping.',
    image: 'shower',
    inStock: true,
    sku: 'TN-WS001',
    tags: ['camping shower','overlanding','solar shower','portable shower'],
    relatedSlugs: ['rechargeable-led-lantern','waterproof-storage-bag'],
  },

  /* ─── 2. Rechargeable LED Lantern ─────────────── */
  {
    id: 'prod-002',
    name: 'Rechargeable LED Lantern',
    slug: 'rechargeable-led-lantern',
    category: 'Lighting',
    categorySlug: 'lighting',
    price: 49.99,
    rating: 4.9,
    reviewCount: 517,
    badge: 'bestseller',
    shortDescription: '1000-lumen collapsible LED lantern with 5 lighting modes, 60-hour runtime, and USB-C recharging. The last lantern you\'ll ever buy.',
    description: `The TrailNest Rechargeable LED Lantern is engineered around one principle: reliable light when you need it most. A 10,000 mAh lithium battery delivers an extraordinary 60 hours of runtime on low mode — enough light for an entire week-long expedition on a single charge. The 1000-lumen maximum output floods an entire campsite with crisp, shadow-free light.\n\nThe telescoping design collapses to just 14 cm for packing and extends to 24 cm for maximum light dispersal. Five modes — high, medium, low, warm glow, and emergency strobe — cover every use case from cooking dinner to distress signalling. IPX6 waterproofing means it keeps working through rain, splash, and humid conditions, and the magnetic base sticks to any steel surface for hands-free mounting.`,
    benefits: [
      '1000 lumens maximum — floods an 8m radius campsite',
      '60-hour runtime on low, 8 hours on full brightness',
      '5 modes: High / Medium / Low / Warm Glow / SOS Strobe',
      'USB-C rechargeable — full charge in 4 hours',
      'Can charge your phone as a 10,000 mAh power bank',
      'IPX6 waterproof — rated for driving rain',
      'Magnetic base + carry handle + hanging hook',
      'Collapsible: 14 cm packed, 24 cm extended',
    ],
    specs: [
      { label: 'Max brightness',   value: '1000 lumens' },
      { label: 'Battery capacity', value: '10,000 mAh Li-ion' },
      { label: 'Runtime',          value: '8 h (high) / 60 h (low)' },
      { label: 'Charging',         value: 'USB-C, 5V/2A (4 h full charge)' },
      { label: 'Power bank output',value: 'USB-A 5V/2.1A' },
      { label: 'Light modes',      value: 'High / Medium / Low / Warm Glow / SOS' },
      { label: 'Waterproof rating',value: 'IPX6' },
      { label: 'Collapsed height', value: '14 cm' },
      { label: 'Extended height',  value: '24 cm' },
      { label: 'Weight',           value: '340 g' },
      { label: 'Material',         value: 'ABS + PC with rubberised grip' },
    ],
    faqs: [
      { question:'Can I use it while charging?', answer:'Yes. The lantern operates normally while connected to a power source, which is useful for extended static camps with solar panel access.' },
      { question:'How long does a full charge last in real-world use?', answer:'At medium brightness (400 lumens), expect 20–22 hours. Most campers get 3–4 nights from a single charge used 4–5 hours per night.' },
      { question:'Is the warm glow mode suitable for reading in a tent?', answer:'Yes. The warm glow mode outputs approximately 80 lumens at 3000K colour temperature — ideal for reading without disrupting night vision.' },
      { question:'Does the magnetic base hold on aluminium roof racks?', answer:'No — magnets don\'t adhere to aluminium. It adheres to steel surfaces. For roof racks, use the hanging loop instead.' },
    ],
    seoTitle: 'Rechargeable LED Lantern 1000 Lumens | 60-Hour Runtime | TrailNest',
    seoDescription: 'The last camping lantern you\'ll ever buy. 1000 lumens, 60-hour runtime, USB-C rechargeable with power bank. IPX6 waterproof. Shop TrailNest.',
    image: 'lantern',
    inStock: true,
    sku: 'TN-LT001',
    tags: ['camping lantern','LED lantern','rechargeable lantern','overlanding lights'],
    relatedSlugs: ['solar-camping-light','portable-camping-shower'],
  },

  /* ─── 3. Foldable Camping Table ────────────────── */
  {
    id: 'prod-003',
    name: 'Foldable Camping Table',
    slug: 'foldable-camping-table',
    category: 'Camp Kitchen',
    categorySlug: 'camp-kitchen',
    price: 129.99,
    originalPrice: 159.99,
    rating: 4.7,
    reviewCount: 289,
    badge: 'sale',
    shortDescription: 'Aircraft-grade aluminium roll-up table. 80 × 60 cm cook surface, 30 kg load rating, sets up in 45 seconds flat. Your camp kitchen anchored.',
    description: `The TrailNest Foldable Camping Table is the camp kitchen anchor you've been looking for. Aircraft-grade 6061 aluminium legs and frame support a 30 kg static load while weighing just 2.1 kg — lighter than most competitors' steel equivalent. The 80 × 60 cm tabletop is formed from high-density HDPE: food-safe, easy to clean, resistant to cuts, heat up to 100°C, and UV-stabilised against brittleness.\n\nFour independently adjustable legs each offer three height positions (45 / 55 / 65 cm) so you can level the table on any surface, from packed dirt to sloped rock shelves. Setup and teardown takes under 45 seconds, and the entire table rolls into a supplied carry bag that straps to the outside of any pack or into an overlanding drawer.`,
    benefits: [
      '30 kg static load capacity — handles full camp kitchen gear',
      'Aircraft-grade 6061 aluminium legs — 2.1 kg total weight',
      '80 × 60 cm HDPE surface — food-safe and heat-resistant to 100°C',
      'Three adjustable height settings per leg: 45 / 55 / 65 cm',
      'Sets up in under 45 seconds with no tools required',
      'Rolls into compact carry bag (62 × 14 cm)',
      'Non-slip foot pads protect surfaces and prevent movement',
    ],
    specs: [
      { label: 'Tabletop size',     value: '80 × 60 cm' },
      { label: 'Height settings',   value: '45 / 55 / 65 cm' },
      { label: 'Load capacity',     value: '30 kg static' },
      { label: 'Frame material',    value: '6061 Aircraft-grade aluminium' },
      { label: 'Tabletop material', value: 'High-density HDPE' },
      { label: 'Max surface temp',  value: '100°C' },
      { label: 'Packed dimensions', value: '62 × 14 cm (rolled)' },
      { label: 'Weight',            value: '2.1 kg' },
      { label: 'Setup time',        value: '< 45 seconds' },
      { label: 'Carry bag',         value: 'Included (600D polyester)' },
    ],
    faqs: [
      { question:'Can I use a camp stove directly on the surface?', answer:'We recommend placing a stove heat mat (sold separately) under gas burners. The HDPE surface handles incidental heat to 100°C but prolonged contact with a hot stove base can leave marks.' },
      { question:'Will the legs sink into soft ground?', answer:'The foot diameter is 28 mm, which distributes load well on firm ground. On very soft sand or mud, use the included foot pads or place timber offcuts under each leg.' },
      { question:'Is the table dishwasher safe?', answer:'The tabletop panel is dishwasher-safe (top rack, no heat dry). The aluminium frame should be wiped down rather than submerged to maintain the anodising.' },
    ],
    seoTitle: 'Foldable Camping Table Aluminium 80×60cm | 30kg Rated | TrailNest',
    seoDescription: 'Aircraft-grade aluminium camping table. 80×60 cm, 30 kg load, 3 height settings, sets up in 45 sec. Packs into compact carry bag. Free shipping. TrailNest.',
    image: 'table',
    inStock: true,
    sku: 'TN-CK001',
    tags: ['camping table','folding table','camp kitchen','overlanding table'],
    relatedSlugs: ['camping-cookware-set','car-side-awning'],
  },

  /* ─── 4. Car Side Awning ───────────────────────── */
  {
    id: 'prod-004',
    name: 'Car Side Awning 2.5m',
    slug: 'car-side-awning',
    category: 'Vehicle Gear',
    categorySlug: 'vehicle-gear',
    price: 349.99,
    rating: 4.8,
    reviewCount: 198,
    badge: 'new',
    shortDescription: '2.5 m × 2 m quick-deploy vehicle awning. 270 g/m² ripstop canvas, integrated LED strip, deploys solo in under 60 seconds. Roof-rack universal fit.',
    description: `Stop hiding in your vehicle when weather rolls in. The TrailNest Car Side Awning gives you 5 square metres of instant shelter that deploys in under 60 seconds — solo, without assistance. The 270 g/m² ripstop canvas is coated for 3000 mm hydrostatic head waterproofing, UV50+ sun blocking, and mould resistance, making it a genuine four-season shelter solution.\n\nThe aluminium extrusion rail system clamps to any roof rack, crossbar, or roof-mounted awning bracket with a 65–80 mm fitting channel. Stainless steel adjustment knuckles let you angle the canopy from flat to 45° to manage runoff, and the two 2 m telescopic aluminium poles pack inside the awning bag. A pre-installed, dimmable 2 m LED strip (USB-powered) turns your awning into a lit outdoor living room after sunset.`,
    benefits: [
      '5 m² of instant shade and rain shelter',
      'Solo deployment in under 60 seconds',
      '3000 mm HH waterproof + UV50+ canvas',
      'Integrated dimmable 2 m LED strip (USB-C powered)',
      'Adjustable angle: flat to 45° for runoff management',
      'Universal roof rack fit: 65–80 mm channel',
      'Mould-resistant and UV-stabilised for year-round use',
      'Includes carry bag, 4 guy ropes, and 8 pegs',
    ],
    specs: [
      { label: 'Awning dimensions',  value: '2.5 m (out) × 2 m (length)' },
      { label: 'Coverage area',      value: '5 m²' },
      { label: 'Canvas weight',      value: '270 g/m² ripstop' },
      { label: 'Waterproof rating',  value: '3000 mm hydrostatic head' },
      { label: 'UV rating',          value: 'UPF 50+' },
      { label: 'Pole material',      value: '6061 aluminium, 30 mm diameter' },
      { label: 'Pole length',        value: '2 m (telescopic, 2 pieces)' },
      { label: 'Rack compatibility', value: 'Universal 65–80 mm channel' },
      { label: 'LED strip',          value: 'Warm white 2700K, dimmable, USB-C' },
      { label: 'Packed dimensions',  value: '170 × 30 × 20 cm' },
      { label: 'Weight',             value: '8.4 kg (inc. poles and bag)' },
    ],
    faqs: [
      { question:'Will this fit my specific roof rack?', answer:'The clamp system fits any rack rail or crossbar with a 65–80 mm channel or tube diameter, which covers the vast majority of aftermarket racks including ARB, Rhino-Rack, Thule, and Yakima.' },
      { question:'Can one person deploy it?', answer:'Yes. The assisted-fold spring mechanism holds the awning open while you extend the poles and stake the guy ropes. Most users complete solo deployment in 45–60 seconds.' },
      { question:'What wind speed is it rated to?', answer:'The canvas and frame are rated to a 40 km/h sustained wind with two guy ropes staked. In stronger gusts, deploy additional guy ropes and reduce angle to 15–20°.' },
      { question:'Is the LED strip waterproof?', answer:'The LED strip is rated IP65 (dust-tight and splash-resistant) and is designed to remain fitted during light rain. Remove for heavy rain or long-term storage.' },
    ],
    seoTitle: 'Car Side Awning 2.5m Waterproof | Roof Rack Universal Fit | TrailNest',
    seoDescription: '5m² instant shelter for overlanders. 2.5m ripstop canvas awning with built-in LED strip, 3000mm waterproof rating, universal roof rack fit. TrailNest.',
    image: 'awning',
    inStock: true,
    sku: 'TN-VG001',
    tags: ['car awning','side awning','overlanding awning','4x4 awning','roof rack awning'],
    relatedSlugs: ['foldable-camping-table','portable-air-compressor'],
  },

  /* ─── 5. Waterproof Storage Bag ────────────────── */
  {
    id: 'prod-005',
    name: 'Waterproof Dry Bag 30L',
    slug: 'waterproof-storage-bag',
    category: 'Storage & Organization',
    categorySlug: 'storage-organization',
    price: 39.99,
    rating: 4.7,
    reviewCount: 423,
    shortDescription: '30-litre heavy-duty TPU dry bag. Fully submersible to 10 m, triple-roll top seal, crush-proof exterior. Keeps your critical gear dry in any conditions.',
    description: `The TrailNest Waterproof Dry Bag is built for overlanders who can't afford to lose gear to water. The 500D TPU exterior is twice the thickness of standard dry bags, providing genuine puncture and abrasion resistance when you're loading and unloading across rocky terrain. The triple-roll top closure creates an airtight, submersible seal rated to 10 metres depth — well beyond any water crossing or flash-flood scenario you're likely to encounter.\n\nAt 30 litres, the bag holds a full set of spare clothes, sleeping bag liner, electronics, first aid kit, and essential documents with room to spare. Compression straps allow you to compress the bag down when partially filled, and the external D-rings let you lash it to roof racks, cargo nets, or tailgate mounts.`,
    benefits: [
      'Submersible to 10 m — survives river crossings and flooding',
      '500D TPU exterior — resists punctures and abrasion',
      'Triple-roll top seal: airtight and waterproof',
      '30 L capacity — full kit in one bag',
      'External D-ring lash points for racks and cargo nets',
      'Compression straps prevent gear shifting',
      'Transparent window lets you ID contents without opening',
      'Available in high-vis orange for easy location',
    ],
    specs: [
      { label: 'Capacity',          value: '30 Litres' },
      { label: 'Material',          value: '500D TPU-coated PVC' },
      { label: 'Waterproof rating', value: 'IPX8 — submersible to 10 m' },
      { label: 'Seal type',         value: 'Triple-roll top with buckle' },
      { label: 'D-rings',           value: '4 × heavy-duty (2 top, 2 side)' },
      { label: 'Dimensions (open)', value: '80 × 40 cm' },
      { label: 'Weight',            value: '480 g' },
      { label: 'Colours',           value: 'Olive / Orange / Black' },
    ],
    faqs: [
      { question:'Is this truly waterproof or just water-resistant?', answer:'Truly waterproof. The 500D TPU shell and triple-roll closure create an airtight seal that is independently tested to IPX8 (10 m submersion). This is not a splashproof bag.' },
      { question:'Will it float if it falls overboard?', answer:'Yes, when sealed correctly with air inside, the bag will float. The compression straps let you remove excess air if you need it to stay submerged in a cargo net.' },
      { question:'Can I store electronics in it?', answer:'Absolutely. Laptop computers, cameras, phones, and tablets are routinely stored in dry bags during water crossings and wet conditions.' },
    ],
    seoTitle: 'Waterproof Dry Bag 30L | IPX8 Submersible | TrailNest',
    seoDescription: 'Keep critical gear dry on any adventure. TrailNest 30L dry bag is IPX8-rated, 500D TPU, triple-roll seal. Perfect for overlanding river crossings. Free shipping.',
    image: 'drybag',
    inStock: true,
    sku: 'TN-SO001',
    tags: ['dry bag','waterproof bag','overlanding storage','camping bag'],
    relatedSlugs: ['vehicle-seat-organizer','portable-camping-shower'],
  },

  /* ─── 6. Portable Air Compressor ──────────────── */
  {
    id: 'prod-006',
    name: 'Portable Air Compressor 12V',
    slug: 'portable-air-compressor',
    category: 'Vehicle Gear',
    categorySlug: 'vehicle-gear',
    price: 119.99,
    rating: 4.8,
    reviewCount: 267,
    badge: 'bestseller',
    shortDescription: '12V dual-motor compressor with 150 PSI output, digital gauge, and auto-stop. Inflates a 35" tyre from 15 to 35 PSI in under 3 minutes.',
    description: `Airing down for a sand crossing is half the off-road equation — the TrailNest Portable Air Compressor is the other half. With a 150 PSI maximum output and dual 12V motors running in parallel, this compressor inflates a 35" all-terrain tyre from 15 PSI to 35 PSI in under 3 minutes. The digital pressure gauge is accurate to ±0.5 PSI and the programmable auto-stop function means you set your target pressure and walk away — no over-inflating.\n\nAt a continuous duty cycle of 100% (no cooldown required), you can inflate all four tyres plus a spare in a single session. The 3.5 m power cable plugs into any 12V cigarette lighter or Anderson connector, and the heavy-duty 4.5 m air hose reaches every corner of a full-size truck. An automatic thermal cutoff protects the motors in extreme ambient temperatures.`,
    benefits: [
      '150 PSI maximum — handles 4x4 tyres up to 40" with ease',
      'Dual 12V motors in parallel — fastest inflation in class',
      '35" tyre from 15–35 PSI in under 3 minutes',
      '100% continuous duty cycle — no cooldown required',
      'Digital gauge accurate to ±0.5 PSI',
      'Programmable auto-stop at target pressure',
      '4.5 m air hose — reaches all four corners of any vehicle',
      'Thermal auto-cutoff protects motors in extreme heat',
    ],
    specs: [
      { label: 'Max pressure',       value: '150 PSI / 10.3 bar' },
      { label: 'Motor',              value: 'Dual 12V brushless motors' },
      { label: 'Power draw',         value: '25A at full load' },
      { label: 'Power connection',   value: '12V cigarette / Anderson 50A (both cables included)' },
      { label: 'Cable length',       value: '3.5 m power / 4.5 m air hose' },
      { label: 'Duty cycle',         value: '100% continuous' },
      { label: 'Gauge accuracy',     value: '±0.5 PSI' },
      { label: 'Inflation speed',    value: '35" tyre 15→35 PSI < 3 min' },
      { label: 'Noise level',        value: '~72 dB at 1 m' },
      { label: 'Dimensions',         value: '28 × 16 × 12 cm' },
      { label: 'Weight',             value: '2.8 kg' },
    ],
    faqs: [
      { question:'Will it work directly off my vehicle battery?', answer:'Yes. Connect via the included Anderson 50A lead directly to the battery terminals for maximum current supply and fastest inflation. The cigarette lighter plug works for regular 4WD sockets (15A or higher).' },
      { question:'Can it be used for tyres larger than 35"?', answer:'Absolutely. The 150 PSI maximum and dual motors handle tyres up to 42" in diameter. Inflation time increases proportionally with tyre volume.' },
      { question:'Does it work for inflating camping mattresses and kayaks?', answer:'Yes. Three inflation adapters are included (Schrader, Presta, needle) for tyres, inflatables, and sports equipment.' },
      { question:'Is there a built-in light for night use?', answer:'Yes. A 200-lumen LED work light is built into the top of the unit with its own on/off switch, independent of the compressor function.' },
    ],
    seoTitle: 'Portable 12V Air Compressor 150PSI | 4x4 Off-Road | TrailNest',
    seoDescription: '150 PSI dual-motor compressor with auto-stop digital gauge. Inflates 35" tyre in 3 min. 100% duty cycle. Perfect for overlanding and 4x4. Free shipping.',
    image: 'compressor',
    inStock: true,
    sku: 'TN-VG002',
    tags: ['air compressor','12v compressor','tyre inflator','overlanding','4x4'],
    relatedSlugs: ['car-side-awning','waterproof-storage-bag'],
  },

  /* ─── 7. Inflatable Camping Pillow ────────────── */
  {
    id: 'prod-007',
    name: 'Inflatable Camping Pillow',
    slug: 'inflatable-camping-pillow',
    category: 'Sleeping',
    categorySlug: 'sleeping',
    price: 24.99,
    rating: 4.6,
    reviewCount: 389,
    badge: 'new',
    shortDescription: 'Ultra-compact ergonomic pillow. Inflates in 3 breaths, packs to a fist. 40D ripstop with a 380 gsm velvet cover. Sleep quality that follows you anywhere.',
    description: `Most camping pillows feel like sleeping on a balloon. The TrailNest Inflatable Camping Pillow is different. The dual-layer internal bladder — soft TPU inner with a micro-fibre regulation layer — distributes support evenly across the full contact surface, eliminating the "hard patch" you feel with single-layer designs. The removable 380 gsm velvet cover provides the same tactile softness as a household pillow while being machine washable.\n\nInflate in 3–4 breaths using the whisper-quiet one-way valve, no pump required. Adjust firmness in seconds by letting out small amounts of air to dial in exactly the support you need. Packed into its own integrated stuff sack, it compresses to 12 × 9 cm and weighs 88 g — you genuinely won't notice it in your kit.`,
    benefits: [
      'Dual-layer TPU bladder eliminates "hard patch" feel',
      'Removable + machine-washable 380 gsm velvet cover',
      'Inflates in 3–4 breaths via one-way whisper valve',
      'Adjustable firmness — fine-tune support without a pump',
      'Packed size: 12 × 9 cm / 88 g — virtually weightless',
      'Ergonomic contoured shape supports head and neck alignment',
      'Works as a lumbar support cushion for long drives',
    ],
    specs: [
      { label: 'Inflated dimensions', value: '40 × 30 × 10 cm' },
      { label: 'Packed dimensions',   value: '12 × 9 cm' },
      { label: 'Weight',              value: '88 g (with cover and stuff sack)' },
      { label: 'Bladder material',    value: '40D ripstop TPU (dual-layer)' },
      { label: 'Cover material',      value: '380 gsm micro-velvet (removable)' },
      { label: 'Valve type',          value: 'One-way whisper valve (no-blow-back)' },
      { label: 'Inflation method',    value: 'Breath only (3–4 breaths)' },
      { label: 'Temperature rating',  value: '-20°C to 50°C' },
    ],
    faqs: [
      { question:'Will I wake up with a flat pillow?', answer:'The one-way whisper valve holds inflation perfectly for 8+ hours without measurable pressure loss under normal use. The bladder has been tested to 2000 inflation cycles without valve degradation.' },
      { question:'Is the cover machine washable?', answer:'Yes. The velvet cover removes via hidden zip and is machine washable on a gentle cycle. Do not tumble dry. The bladder itself should be wiped clean only.' },
      { question:'Can I use it without the cover?', answer:'Yes. The bladder surface is smooth TPU, which is comfortable to sleep on directly. Some users find the cover adds warmth in cold conditions.' },
    ],
    seoTitle: 'Inflatable Camping Pillow Ultralight | 88g Ergonomic | TrailNest',
    seoDescription: 'Sleep comfortably anywhere. 88g inflatable camping pillow with dual-layer TPU and velvet cover. Packs to 12×9cm, inflates in 3 breaths. TrailNest.',
    image: 'pillow',
    inStock: true,
    sku: 'TN-SL001',
    tags: ['camping pillow','inflatable pillow','backpacking pillow','lightweight camping'],
    relatedSlugs: ['rechargeable-led-lantern','waterproof-storage-bag'],
  },

  /* ─── 8. Solar Camping Light ───────────────────── */
  {
    id: 'prod-008',
    name: 'Solar String Lights 10m',
    slug: 'solar-camping-light',
    category: 'Lighting',
    categorySlug: 'lighting',
    price: 34.99,
    rating: 4.6,
    reviewCount: 276,
    shortDescription: '10 m waterproof LED string lights with integrated solar panel and 2000 mAh battery. 8 modes. Transforms any campsite into a warm, welcoming space.',
    description: `There's a reason the TrailNest Solar String Lights appear in more campsite photos than any other single piece of kit in our range. Thirty warm-white Edison-style LED bulbs are strung across 10 m of weatherproof copper wire, powered by a 5W monocrystalline solar panel that charges the onboard 2000 mAh battery through a full day of sun exposure. Eight lighting modes — including steady warm, slow fade, and party flash — mean the same set of lights works for a quiet family dinner and a lively evening around the fire.\n\nEach bulb is individually sealed to IP65 waterproof rating, and the rubberised cable withstands temperatures from -20°C to 60°C, making these lights viable across every season and climate. The remote control and built-in timer add to the set-and-forget convenience.`,
    benefits: [
      '30 Edison-style LED bulbs across 10 m',
      '5W solar panel — fully charges in 6 hours of direct sun',
      '2000 mAh built-in battery — up to 10 hours of runtime',
      '8 lighting modes including warm, fade, flash, and timer',
      'IP65 waterproof — each bulb individually sealed',
      'Works from -20°C to 60°C (year-round)',
      'Includes wireless remote with 5 m range',
      'Built-in 6/8-hour auto-off timer',
    ],
    specs: [
      { label: 'Total length',      value: '10 m (12 m with solar lead)' },
      { label: 'Number of bulbs',   value: '30 × warm white LED (2700K)' },
      { label: 'Solar panel',       value: '5W monocrystalline' },
      { label: 'Battery capacity',  value: '2000 mAh' },
      { label: 'Runtime',           value: 'Up to 10 hours (fully charged)' },
      { label: 'Charge time',       value: '~6 hours direct sun' },
      { label: 'Lighting modes',    value: '8 modes + remote + timer' },
      { label: 'Waterproof rating', value: 'IP65 (each bulb)' },
      { label: 'Operating temp',    value: '-20°C to 60°C' },
      { label: 'Cable type',        value: 'Rubberised copper, UV-resistant' },
    ],
    faqs: [
      { question:'Do they work on cloudy days?', answer:'Yes, but runtime will be reduced. In overcast conditions the 5W panel charges at roughly 30–40% efficiency, giving 3–4 hours of runtime from a cloudy-day charge. You can supplement with the included USB-C charging cable.' },
      { question:'Can I extend two sets together?', answer:'Yes. Each set has a standard connector that allows daisy-chaining up to three sets for 30 m of lights from one solar panel (expect reduced battery life per string).' },
      { question:'Will the bulbs break if packed tightly?', answer:'Each bulb has a shatter-resistant polycarbonate housing. The set packs into a soft cotton carry pouch and is designed for regular pack/unpack cycles without damage.' },
    ],
    seoTitle: 'Solar Camping String Lights 10m | 30 LED Waterproof | TrailNest',
    seoDescription: 'Warm ambience anywhere off-grid. 10m, 30 bulb solar camping string lights with 8 modes, IP65, and built-in timer. Powers a full night from one day of sun.',
    image: 'stringlights',
    inStock: true,
    sku: 'TN-LT002',
    tags: ['solar lights','camping string lights','outdoor lights','overlanding lights'],
    relatedSlugs: ['rechargeable-led-lantern','foldable-camping-table'],
  },

  /* ─── 9. Camping Cookware Set ──────────────────── */
  {
    id: 'prod-009',
    name: 'Camping Cookware Set 10-Piece',
    slug: 'camping-cookware-set',
    category: 'Camp Kitchen',
    categorySlug: 'camp-kitchen',
    price: 79.99,
    rating: 4.7,
    reviewCount: 312,
    badge: 'bestseller',
    shortDescription: 'Non-stick 10-piece hard-anodised aluminium cookware set with silicone handles. Every piece nests inside the large pot for compact storage. Feeds 4 people easily.',
    description: `The TrailNest Camping Cookware Set is what happens when a camp cook helps design kitchen equipment. Ten pieces — everything you need to prepare a full hot meal for four people — nest together inside the 3 L main pot to form a single compact package that fits into the included mesh carry bag.\n\nThe hard-anodised aluminium construction is twice as hard as stainless steel and conducts heat far more evenly than budget cookware sets, eliminating hot-spots that burn rice and beans. A PFOA-free non-stick interior coating makes cooking and cleaning dramatically easier, and the folding silicone handles are heat-rated to 230°C and double-locked to prevent accidental collapse during cooking.`,
    benefits: [
      '10 pieces nest into the 3L pot — single compact package',
      'Hard-anodised aluminium: harder than steel, lighter than cast iron',
      'PFOA-free non-stick — no harmful chemicals',
      'Even heat distribution — no hot spots',
      'Silicone handles rated to 230°C, double-lock folding',
      'Compatible with gas, induction, electric, and open flame',
      'Mesh carry bag included for ventilation during storage',
      'Feeds 4 comfortably — enough for a full camp crew',
    ],
    specs: [
      { label: 'Set contents',       value: '3L pot, 2L pot, 26cm frying pan, 2 lids, 2 bowls, 1 ladle, 1 spatula, 1 spork' },
      { label: 'Main pot capacity',  value: '3 Litres' },
      { label: 'Small pot capacity', value: '2 Litres' },
      { label: 'Frying pan diameter',value: '26 cm' },
      { label: 'Material',           value: 'Hard-anodised 3003 aluminium' },
      { label: 'Coating',            value: 'PFOA-free non-stick (Ilag 2-layer)' },
      { label: 'Handle material',    value: 'Heat-resistant silicone to 230°C' },
      { label: 'Compatible hobs',    value: 'Gas, induction, electric, open flame' },
      { label: 'Packed dimensions',  value: '22 × 22 × 17 cm' },
      { label: 'Total set weight',   value: '1.35 kg' },
    ],
    faqs: [
      { question:'Is it dishwasher safe?', answer:'The pots and lids are dishwasher safe (top rack). However, hand washing extends the life of the non-stick coating significantly. The silicone utensils are dishwasher safe.' },
      { question:'Will it work on a campfire or open coals?', answer:'Yes. The hard-anodised exterior handles open flame well. Position the pot on stable rocks or a pot stand above the coals rather than directly on burning wood.' },
      { question:'How many pieces can cook simultaneously?', answer:'The two pots can be used simultaneously on any dual-burner camp stove, while the frying pan occupies a third burner or a separate single-burner stove.' },
    ],
    seoTitle: 'Camping Cookware Set 10-Piece | Non-Stick Aluminium | Feeds 4 | TrailNest',
    seoDescription: '10-piece hard-anodised camping cookware set. PFOA-free non-stick, 3L + 2L pots, frying pan, all nesting in one compact package. Feeds 4. TrailNest.',
    image: 'cookware',
    inStock: true,
    sku: 'TN-CK002',
    tags: ['camping cookware','camp kitchen','camping pots','overlanding kitchen'],
    relatedSlugs: ['foldable-camping-table','rechargeable-led-lantern'],
  },

  /* ─── 10. Vehicle Seat Organizer ──────────────── */
  {
    id: 'prod-010',
    name: 'Vehicle Seat Organizer Pro',
    slug: 'vehicle-seat-organizer',
    category: 'Storage & Organization',
    categorySlug: 'storage-organization',
    price: 44.99,
    rating: 4.5,
    reviewCount: 198,
    shortDescription: 'Heavy-duty 600D Oxford seat-back organizer with 14 pockets, tablet sleeve, and MOLLE webbing. Fits any vehicle. Your co-pilot\'s mission control.',
    description: `Long-distance overlanders know that an organised vehicle is a faster, safer vehicle. The TrailNest Vehicle Seat Organizer transforms the back of any front seat into a fully equipped mission control centre. Fourteen pockets in various sizes accommodate everything from water bottles and tablets to maps, recovery gear, and first aid supplies, while the external MOLLE webbing lets you attach additional pouches, holsters, and gear carriers as your kit evolves.\n\nConstructed from 600D Oxford polyester with reinforced PVC-backed panels, the organizer handles the vibration, dust, and UV exposure of extended off-road travel without sagging or tearing. Universal adjustable straps fit any seat headrest from compact SUVs to full-size trucks, and the non-slip backing ensures zero movement on the seat back even on rough corrugated roads.`,
    benefits: [
      '14 pockets — a place for everything in your daily-carry kit',
      'Padded tablet/iPad sleeve up to 10"',
      'MOLLE webbing front panel for modular expansion',
      'Water bottle pockets hold up to 1.5L bottles',
      '600D Oxford construction — military-grade durability',
      'Non-slip PVC backing — zero movement on rough terrain',
      'Universal fit: adjustable straps for any headrest',
      'Document pocket with transparent PVC window',
    ],
    specs: [
      { label: 'Dimensions',         value: '45 × 35 cm (mounted)' },
      { label: 'Main material',      value: '600D Oxford polyester' },
      { label: 'Backing',            value: 'Non-slip PVC-reinforced' },
      { label: 'Number of pockets',  value: '14 (varies by size and type)' },
      { label: 'Tablet sleeve size', value: 'Up to 10" (iPad or equivalent)' },
      { label: 'Water bottle pocket',value: 'Elastic, fits up to 1.5L bottles' },
      { label: 'Attachment',         value: 'Adjustable headrest straps (universal)' },
      { label: 'MOLLE rows',         value: '4 rows × 6 loops' },
      { label: 'Weight',             value: '420 g' },
      { label: 'Colour',             value: 'Black / Olive / Coyote Tan' },
    ],
    faqs: [
      { question:'Will it fit the back of a car seat with integrated headrests?', answer:'Yes. The top strap is adjustable and also features a clip-over option for integrated headrest seats. Fits all Toyota Land Cruisers, Defenders, Hiluxes, and Jeep Wranglers tested.' },
      { question:'Can I use it in the front passenger seat?', answer:'Absolutely, and this is the most popular configuration. Facing the rear passenger, it becomes a rear-seat activity organizer for children or passengers.' },
      { question:'Can I add extra pouches to the MOLLE webbing?', answer:'Yes. Any standard MOLLE-compatible accessory — magazine pouches, medical pouches, tool holsters — attaches to the webbing rows using the standard MOLLE weave system.' },
    ],
    seoTitle: 'Vehicle Seat Organizer Pro | 14 Pockets + MOLLE | Overlanding | TrailNest',
    seoDescription: 'Keep your 4x4 organised on any mission. 14-pocket seat organizer with MOLLE webbing, tablet sleeve, and universal fit. 600D Oxford. TrailNest.',
    image: 'organizer',
    inStock: true,
    sku: 'TN-SO002',
    tags: ['seat organizer','car organizer','overlanding storage','4x4 organization'],
    relatedSlugs: ['waterproof-storage-bag','portable-air-compressor'],
  },
];

export function getProductBySlug(slug: string) { return products.find(p => p.slug === slug); }
export function getProductsByCategory(slug: string) { return products.filter(p => p.categorySlug === slug); }
export function getBestSellers() { return products.filter(p => p.badge === 'bestseller'); }
export function getRelatedProducts(slugs: string[]) { return products.filter(p => slugs.includes(p.slug)).slice(0, 4); }
